### ISSUE TITLE
Enhanced suport for nested subdomains

### ISSUE THREAD

**Issue by drk1wi** [drk1wi/Modlishka#1]
In some cases, nested subdomains will raise a SSL certificate warning. This will be fixed in the upcoming releases.

**Comment by CyberTheReape** [comment]
First of all thank you for this beautiful project..I will have some questions for you.I created a wildcard certificate through another site ..now I have 3 different certificate files.

certificate.crt
private.key
ca_bundle.crt

which one should I convert to pem file now ? i am reading english words with google translate.this part looks a little confused.I did a process for the pem file but I don't know if I did it right

openssl genrsa -out private.key 2048
openssl req -x509 -new -nodes -key private.key -sha256 -days 1024 -out private.pem

I just converted the private.key file into the private.pem file. if i did it right i will import private.pem certificate into my own browser ?but i don't know what to do with other certificates ?

only the certificate section of the post on wiki does not translate correctly by google translate

can you tell me what to do ?

**Comment by drk1wi** [comment]
If you have CA signed certificates, then you should be able to use them directly in the tool. just `awk '{printf "%s\\n", $0}' file` and place them in the relevant json config file parameters. 

If you are using self signed CA certificate then you will have to add it to your trusted CA certificate store (either in the browser or at your OS level), but in that case you should use the 'autocert' plugin.

**Comment by enema-combatant** [comment]
Hi drk1wi, very promising work, much respect.

Question I have is for the following:
-> my site: example.me
-> target site: example.com

Problem is the target site does a redirect:
-> example.com -> new-example.com

Must my obtained site (and cert) match the domain portion after redirect to ensure the 1-1 mapping functionality works?

ec

**Comment by drk1wi** [comment]
@enema-combatant the domain for your certificate can be arbitrary and you can point directly the tool to the domain after the redirect : new-example.com. this way you should achieve 1:1 subdomain mapping.
