### ISSUE TITLE
How to use SayHello2Modlishka

### ISSUE THREAD

**Issue by uemahra** [drk1wi/Modlishka#10]
Hi drk1wi,

I'm using Modlishka and it can work, but I don't know how and where to see the password I got. I tried it on the clinet, there is no such information but only have the GUI, and tried it on server https://127.0.0.1/SayHello2Modlishka and got no display.

**Comment by drk1wi** [comment]
You should have all of your credentials in the log file, but in order to use the "control_panel" plugin you will also have to create regular expressions that will capture them . Please check the WIKI for the "credParams" description

**Comment by uemahra** [comment]
Got the pwd, thank you, great job!
