### ISSUE TITLE
 http: TLS handshake error from 127.0.0.1:35874: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by hrishi9890** [drk1wi/Modlishka#100]
2019/03/16 23:01:30 http: TLS handshake error from 127.0.0.1:35874: tls: first record does not look like a TLS handshake
please someone help me 
i even changed my listening port but cant load http://loopback.modlishka.io

**Comment by drk1wi** [comment]
please paste in your config file.

**Comment by drk1wi** [comment]
This is resolved in v1.1
