### ISSUE TITLE
GSUITE - login form not loading

### ISSUE THREAD

**Issue by gianluca8989** [drk1wi/Modlishka#102]
Hi drk1wi,
first of all congratulations for the excellent work. I’ve a problem only with gsuite account. In particular, when I try to access through modlishka to my gsuite account, the login form is not loaded. Apparently the are no error in the log file. I tried passing all the resources through the parameter “targetResources” in json template, but the problem persist. 

Do you have any suggestion to try fo fix this situation?

Thanks,
Gianluca

Configuration:

 - Modlishka configuration:
      -JSON config:
{
  "phishingDomain": "loopback.modlishka.io",
  "listeningPort": "443",
  "listeningAddress": "127.0.0.1",
  "target": "https://www.google.com/",
  "targetResources": "mail.google.com,ok6static.oktacdn.com,login.okta.com,content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ogs.google.com,accounts.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com,accounts.google.com",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "useTls": true,
  "jsRules":"",
  "debug": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "Target.log",
  "plugins": "all",
  "credParams": "dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert": "",
  "certKey": "",
  "certPool": ""
}

Command line: ./dist/proxy -config templates/gsuite.json -debug

 - Browser: firefox, chrome
 - OS: kali
 - Plugin: autocert

**Comment by gianluca8989** [comment]
Hi  drk1wi,
I think the problem could be the following:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://5pamjk08mxnu2enr3jah2n0jdhtg.loopback.modlishka.io/assets/js/mvc/loginpage/initLoginPage.pack.b616a6e9213b6a42aa89129f892548c4.js?v=1' with computed SHA-256 integrity 'eO7tX9/IFcGd8LAvvDWZEpzCev6NAoKCKrNqPPPqiR4='. The resource has been blocked.

I tried to pass  -targetRules "aW50ZXJncml0eT0ic2hh,aW50ZXJncmlhdHk9InNoYQ==" but the problem still persist. When I try to pass -targetRules through the json, receive this error: 

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/drk1wi/Modlishka/core.SetCoreRuntimeConfig(0xc00008ac50, 0xc00008ac60, 0xc00008ac70, 0xc00008ac80, 0xc00008ac90, 0xc00008acc0, 0xc00008acd0, 0xc00008aca0, 0xc00008acb0, 0xc00008ace0, ...)
	/root/go/src/github.com/drk1wi/Modlishka/core/variable.go:106 +0x8b1
main.main()
	/root/go/src/github.com/drk1wi/Modlishka/main.go:71 +0x1d1

Thanks for the support,
Gianluca

**Comment by gianluca8989** [comment]
Hi,
sorry for the "spam" but i really interested in this nice project.
I able to bypass integrity attribute through burp match and replace options. When set a targetRules through the json configuration file or via command line -targetRules "aW50ZXJncml0eT0ic2hh,aW50ZXJncmlhdHk9InNoYQ==“, it seem not work properly. I tried different combinations using the targetRules but none worked properly.

Thanks,
Gianluca

**Comment by drk1wi** [comment]
Hi Gianluca,
You should be using the rules parameter. That will work :-)

**Comment by gianluca8989** [comment]
Hi,
thank for quick reply. In json config file there is no "rules" parameter but only "targetResources, targetRules, jsRules". Reading the documentation the only parameter useful for this scenario is "targetRules" but it seem not working.  Probably something wrong in the configuration of this parameter. Could you give me some more detailed information on how to set it up?

Thank for the support,
Gianluca

**Comment by drk1wi** [comment]
You are right, it should be 'targetRules'. Rules is currently deprecated.
 There's an example template here: https://github.com/drk1wi/Modlishka/blob/master/templates/office365.json with what you are trying to achieve. From what i can see, you parameter is missing ':'.

**Comment by leo8084** [comment]
please boss i am having thesame issue
