### ISSUE TITLE
Why is the page displayed like this?

### ISSUE THREAD

**Issue by KennyTe** [drk1wi/Modlishka#105]
![1](https://user-images.githubusercontent.com/48878720/54877397-34562100-4e2f-11e9-9716-4cf63f4afd8b.png)
![Безымянный](https://user-images.githubusercontent.com/48878720/54877416-839c5180-4e2f-11e9-927b-e8c97886f091.png)

**Comment by KennyTe** [comment]
In the debugger, I found this "failed to load the style sheet" and a request for a link https://212nj0b4gjf94hmrq0pxpjr0k0.mydomain/assets/github-52cbcc40dcd4c1570226a72b3df60ecf.css. What this "212nj0b4gjf94hmrq0pxpjr0k0"?

**Comment by drk1wi** [comment]
this FQDN is actually an example why it is possible to support multiple origins over a single domains. This is why the tool works so well.  
@KennyTe  check errors in the console. there's probably something blocking the resources.
