### ISSUE TITLE
office365 template not bringing result

### ISSUE THREAD

**Issue by saddawe2424** [drk1wi/Modlishka#106]
i setup modlishka on ubuntu server and setup with paid domain when i login on my phishing page i not see my login info on admin panel..i am using your office365 template i not edit it ...than why i facing this i try 3 time but still not get any info..

**Comment by patrick4real83** [comment]
I can help you. Send me your Skype id.

**Comment by saddawe2424** [comment]
email me i will talk you on email saddawe2424@gmail.com

**Comment by drk1wi** [comment]
marked as resolved, due to lack of feedback.
