### ISSUE TITLE
gsuite problem

### ISSUE THREAD

**Issue by bojanrodic** [drk1wi/Modlishka#108]
**Describe the bug**
First, when i try to log in, it logs me in but puts this info 
http: superfluous response.WriteHeader call
**Expected behavior**
Than it should allow me to take "session" on Control Panel

I upload picture to show you everything.
Anyway, it grabs username and password (username sometimes not)
it is not point i need gmail, but i am currious why it does not work, want to try to fix it to work properly.
![modlishka](https://user-images.githubusercontent.com/36294417/55707945-0eab4900-59e5-11e9-9e6a-87cd2b9e8559.png)

**Comment by drk1wi** [comment]
The session in control panel is in beta state. It requires some improvement.

**Comment by bojanrodic** [comment]
I did not come to troll ;)
**Tool is awezome**, but it would be cool that we make it even better.
I am testing config with my sites, it is not big problem to make it work, but with google it is little harder to make it perfect.

**Comment by drk1wi** [comment]
can you check with v.1.1 ?
