### ISSUE TITLE
Invalid domain for site key

### ISSUE THREAD

**Issue by KBlame** [drk1wi/Modlishka#109]
Hello! The problem is, captcha does not work on Yahoo, you said that you need to use the appropriate JS code.
Could you tell us in more detail about what code is being spoken? 
https://www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__en.js ?

**Comment by drk1wi** [comment]
Sorry, I can't work on this :-)  not enough time to patch all of the JS code. Usually you have to patch relevant part of the JS code, deobfuscate it and understand the logic.
