### ISSUE TITLE
ANID cookie missing

### ISSUE THREAD

**Issue by kennyyy53** [drk1wi/Modlishka#110]
Hi!

I install the tool and everything is working well except once. When I get the information which appear in the pannel and I try to click on "Impersonate user" an error message appears on my scrren to say to me that the cookies that I get and the google's needed cookies to connect myself with the account didn't match. Indeed when I go see in my parameters I see that a categorie is missing in the cookie that I get: the ANID. I don't know why I didn't get it and would also to know how to resolve this problem,

Regards,

Kenny
![1](https://user-images.githubusercontent.com/48528907/55758524-566ab880-5a57-11e9-88ed-7206cf9070db.JPG)
![2](https://user-images.githubusercontent.com/48528907/55758525-566ab880-5a57-11e9-9e54-e08a5e47b84a.JPG)
![3](https://user-images.githubusercontent.com/48528907/55758526-57034f00-5a57-11e9-93cf-1bf8b7886006.JPG)

**Comment by GregorioSecurity** [comment]
@kennyyy53 Did you ever figure it out?

**Comment by imemyself9327** [comment]
how did you resolved this issue i am facing the same problem
