### ISSUE TITLE
evilginx2 reverse proxy like (enhancement)

### ISSUE THREAD

**Issue by HsounaZinoubi** [drk1wi/Modlishka#114]
can you add a feature like https://github.com/kgretzky/evilginx2 
in phishlets we have to put only the input name to be captured
or even better in command line arg
example --input1="username" --input2="password" 
in evilginx capturing creds is like this in conf file:
credentials:
username:
key: 'email'
search: '(.)'
type: 'post'
password:
key: 'password'
search: '(.)'
type: 'post'
we have to set the input name and a general regex to capture it like '(.*)'
it will be more easy if that will be the same here with command line arg and conf file if you can do it without the base64 encoding of corse.
and it will be better of you use xpath insteade of regex because it is more easy

and please make us an example of "credParams" i spend all day figuring it out no luck
i have 2 input:
userLoginId=blabla%40gmail.com&password=sellypassword123&rememberMe=true&
so it will be :
userLoginId=([^\W]+)&?password=([^\W]+)&
i did :
echo "userLoginId=([^\W]+)&?password=([^\W]+)&" |base64
it give me:
dXNlckxvZ2luSWQ9KFteXFddKykmP3Bhc3N3b3JkPShbXlxXXSspJgo=
i put it in credParams but with no luck nothing appear in admin panel or in stdout 
what is wrong ?

**Comment by drk1wi** [comment]
Hi, Sorry for late response. I will be going through all of the issues soon along with a new release of the tool.
It seems like you have an error in the echo "userLoginId=([^\W]+)&?password=([^\W]+)&" |base64
should be echo -n "userLoginId=([^\W]+)&?password=([^\W]+)&" |base64 without a new line.

**Comment by pretech86** [comment]
@HsounaZinoubi  do you have google phishlet ?
