### ISSUE TITLE
Control Plugin issues 

### ISSUE THREAD

**Issue by imemyself9327** [drk1wi/Modlishka#120]
make
go test -v main.go main_test.go
# github.com/drk1wi/Modlishka/plugin
plugin/control.go:37:6: ExtendedControlConfiguration redeclared in this block
	previous declaration at plugin/autocert.go:37:6
plugin/control.go:42:6: ControlConfig redeclared in this block
	previous declaration at plugin/autocert.go:42:6
plugin/control.go:49:6: RequetCredentials redeclared in this block
	previous declaration at plugin/autocert.go:49:6
plugin/control.go:54:7: URL redeclared in this block
	previous declaration at plugin/autocert.go:54:13
plugin/control.go:56:5: htmltemplate redeclared in this block
	previous declaration at plugin/autocert.go:56:5
plugin/control.go:119:5: iframetemplate redeclared in this block
	previous declaration at plugin/autocert.go:119:5
plugin/control.go:187:6: Victim redeclared in this block
	previous declaration at plugin/autocert.go:187:6
plugin/control.go:193:6: Cookie redeclared in this block
	previous declaration at plugin/autocert.go:193:6
plugin/control.go:202:6: CookieJar redeclared in this block
	previous declaration at plugin/autocert.go:202:6
plugin/control.go:206:5: credentialParameters redeclared in this block
	previous declaration at plugin/autocert.go:206:5
plugin/control.go:206:5: too many errors
FAIL	command-line-arguments [build failed]
make: *** [Makefile:23: test] Error 2

Also in my custom json template  when i write control in plugin path it says no control plugin found 
root@kali:~/go/src/github.com/drk1wi/Modlishka# ./dist/proxy -config templates/mycustom.json
[Sat Apr 20 23:51:33 2019]  ERR  Plugin control not found
[Sat Apr 20 23:51:33 2019]  INF  

>>>> "Modlishka" Piotr Duszynski @drk1wi - Reverse Proxy started <<<<

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

Listening on: [0.0.0.0:443] 
this is my config for custom template

  "phishingDomain": "xxxxxxxxxxxx.com",
  "listeningPort": "443",
  "listeningAddress": "0.0.0.0",
  "target": "https://xxxxxxxxxxxxxxx.com",
  "targetResources": "",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "id",
  "trackingParam": "id",
  "useTls": true,
  "jsRules":"",
  "debug": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "lb.log",
  "plugins": "control",
  "cert": "-----BEGIN CERTIFICATE-----\nMIIGXjCCBUagAwIBAgISA3BbfXFSMu5

**Comment by drk1wi** [comment]
Weird... I haven't seen this one before. Can you try again with 1.1 ?

**Comment by drk1wi** [comment]
closing as resolved.
