### ISSUE TITLE
Office 365 page

### ISSUE THREAD

**Issue by secnewb** [drk1wi/Modlishka#121]
Hi guys, I can use this tool for Gmail without any issue and it captures username and password.
i am trying to do same thing for office 365 but it just gives me blank page and nothing happens. if i add "login" prefix in URL before loopback, i am able to see the office 365 and access it without any issue but tool doesn't capture username or password. I am using default template. does anyone know if i need to do anything extra to use Modishka for office 365?
Thanks

**Comment by moamoha** [comment]
> Hi guys, I can use this tool for Gmail without any issue and it captures username and password.
> i am trying to do same thing for office 365 but it just gives me blank page and nothing happens. if i add "login" prefix in URL before loopback, i am able to see the office 365 and access it without any issue but tool doesn't capture username or password. I am using default template. does anyone know if i need to do anything extra to use Modishka for office 365?
> Thanks
hi friend can you please explain more on method how you us it with gmail ?

**Comment by drk1wi** [comment]
You will have to update the regex used to extract login and password from the responses. Please check out the WIKI page.
