### ISSUE TITLE
How to change the loopback.modlishka.io domain to localhost for portforwarding with ngrok?

### ISSUE THREAD

**Issue by Pholonius** [drk1wi/Modlishka#122]
Hi I was wondering if it is possible to change the default phisingdomain loopback.modlishka.io to localhost or the IP of your machine so i portforward my local IP with Ngrok to the WAN? 

Kind regards,

**Comment by drk1wi** [comment]
I haven't tried ngrok, but theoretically if you forward the connection and force the proxy to use your visible IP address, the it should work.

**Comment by a-bilal10** [comment]
Hi, i wanted to know if it worked as i have used cloudflared tunnel to do it. It forwards the link but doesn't log the response to the log file. Any help?

**Comment by a-bilal10** [comment]
> Hi I was wondering if it is possible to change the default phisingdomain loopback.modlishka.io to localhost or the IP of your machine so i portforward my local IP with Ngrok to the WAN?
> 
> Kind regards,

Hi, i wanted to know if it worked as i have used cloudflared tunnel to do it. It forwards the link but doesn't log the response to the log file. Any help?

**Comment by 080Busybrain** [comment]
Report that on the Creator's GitHub page
