### ISSUE TITLE
Can't get username with period

### ISSUE THREAD

**Issue by GregorioSecurity** [drk1wi/Modlishka#126]
Whenever I try to specify a username with a period it doesn't collect the username. I know I have to change the regex of ([^\W]+) to (\S+) but I can't seem to find where to do that. I tried editing the credParams in the google template from the default `dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=`
to 
`dHJ1ZVxdLCIoXFMrKSJdCg==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=` but now I can't collect any usernames. Can someone please tell me where to change the regex? @drk1wi

**Comment by GregorioSecurity** [comment]
I got it! Change the credParams in the template from
`dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=`
to
`dHJ1ZVxdLCIoKD86XHcrW1wuXC1cX10pezAsfVx3KykiXQ==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=`

**Comment by abouhad** [comment]
How did you do it?

**Comment by GregorioSecurity** [comment]
In ./templates/google.com_gsuite.json change the credParams field from ```dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=```
to
```dHJ1ZVxdLCIoKD86XHcrW1wuXC1cX10pezAsfVx3KykiXQ==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=```
https://github.com/drk1wi/Modlishka/blob/a89b3e5ccf465d45e450afa5a78c77716d489c92/templates/google.com_gsuite.json#L22
