### ISSUE TITLE
Empty data in Modlishka control panel

### ISSUE THREAD

**Issue by ghost** [drk1wi/Modlishka#127]
Hi!
I install this awesome tool. All right.
Launch phishing domain
All proxy via my phishing domain
I send my phishing url (with google template) to aim, then him enter login adn password, and enter into gmail
But I have not anything data in control panel: mydaomain.com/SayHello2Modlishka?
Maybe I have wong config google template
Here my google config file

{
  "phishingDomain": "may-domen.xyz",
  "listeningPort": "443",
  "listeningAddress": "0.0.0.0",
  "target": "https://google.com",
  "targetResources": "content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ogs.google.com,accounts.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "https://mail.google.com/",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "useTls": true,
  "jsRules":"",
  "debug": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "all",
  "credParams": "",
  "cert": "",
  "certKey": "",
  "certPool": ""
}
And I don't uderstand where I can get unical url for different aims?
Thx

**Comment by greyredfox** [comment]
I think my problem with "credParams"
What parameters I need put there for google template?
Thx!
Help me

**Comment by greyredfox** [comment]
Maybe some body can help me?

**Comment by patrick4real83** [comment]
Hi Everyone. Please who can teach me setup Modlishka or evilginx2. No knowledge is free. I will pay.

**Comment by drk1wi** [comment]
please check out the example config files in the /templates dir

**Comment by patrick4real83** [comment]
Yes I have see them but I need more guide line bro. I don’t mind to reward you by paying you per hours we spend. Let me know what you think

**Comment by patrick4real83** [comment]
If I can get the full coding. I will learn more about it.

**Comment by drk1wi** [comment]
Try the latest template in https://github.com/drk1wi/Modlishka/blob/master/templates/google.com_gsuite.json it works quite well. credParams are base64 encoded regular expressions: https://www.aivosto.com/articles/regex.html
