### ISSUE TITLE
Missing required configuration to start the proxy

### ISSUE THREAD

**Issue by tokiijnr** [drk1wi/Modlishka#128]
modlishka not starting

![Screenshot from 2019-05-13 11-52-47](https://user-images.githubusercontent.com/49600154/57616957-25ddd900-7545-11e9-9216-8a92589cbf04.png)

**Comment by tokiijnr** [comment]
pls help @drk1wi

**Comment by HsounaZinoubi** [comment]
@tokiijnr you miss the - before config
correct command:
./dist/proxy -config template/google.com_gsuite.json

**Comment by tokiijnr** [comment]
![Screenshot from 2019-05-13 12-18-00](https://user-images.githubusercontent.com/49600154/57617952-ab628880-7547-11e9-8b92-01e0dae93af6.png)

**Comment by tokiijnr** [comment]
ive  tried that now but i get this new error

![Screenshot from 2019-05-13 12-22-00](https://user-images.githubusercontent.com/49600154/57618066-072d1180-7548-11e9-8bd7-1815462cdccb.png)

**Comment by tokiijnr** [comment]
@HsounaZinoubi

**Comment by HsounaZinoubi** [comment]
@tokiijnr  sorry the word "template" is missing "s"
the correct command:
./dist/proxy -config templates/google.com_gsuite.json

**Comment by drk1wi** [comment]
closing as resolved.
