### ISSUE TITLE
Pointing Modlishka to Phishing Domain

### ISSUE THREAD

**Issue by ShmokeHack** [drk1wi/Modlishka#130]
Hello Boss, 

great work!

Kindly assist to give step-wise instruction on how to point Modlishka to phishing domain.

Thanks in advance.

**Comment by drk1wi** [comment]
Hi, Thank you. 
Try the parameter 'proxyDomain' in the v.1.1, some of the parameter names have changed . 
Check out the -h flag or the example templates .

**Comment by ShmokeHack** [comment]
Thank you for your reply Boss! 

Though I'd like to act like I understand the instructions you explained above, but I don't. I know you are a very busy man, but if you don't mind, can you give stepwise codes/instructions on how to make Modlishka accessible through a web address e.g www.myfakephishingdomain.com

Please Boss, you are very busy, but without this, I am totally stuck and I speak not for myself only but for a large category of users.

Thanks in advance!

ShMoKe.

**Comment by drk1wi** [comment]
Hi, Please follow the : https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial and https://github.com/drk1wi/Modlishka/wiki/How-to-use. I hope that these will be helpful. is something is unclear please let me know.

**Comment by ShmokeHack** [comment]
Thank you for your assistance. Please how can I contact you directly and how do I make donation this project.

I am still having issues with pointing the Modlishka to domain.

I'd appreciate your urgent reply.

Thanks

**Comment by ali5634432** [comment]
Hello I want to make the same think, let me know if you solved the problem

**Comment by eZh3lp** [comment]
"phishingDomain": "www.myfakephishingdomain.com",
"listeningPort": "443",
"listeningAddress": "0.0.0.0",
"target": "https://yourtargetdomain.com",
"...
you will need to create a new template file for your target domain and add what you need in the json file
