### ISSUE TITLE
Modlishka can't handle 302, 307 redirect.

### ISSUE THREAD

**Issue by macroflacko** [drk1wi/Modlishka#132]
Modlishka works without problem, but anytime there's 302 or 307 it redirects to the real domain instead of my domain.

The website I'm using Modlishka on uses 302 for all redirects, so for example after i log in, it redirects to the real domain instead of mirroring into mine domain.

It has to do something with the "handle 302" function. Not sure what's wrong.

I think runtime.RealURLtoPhish should be my -phishingDomain but instead it sets it to the target domain.
So what I'm getting is Rewriting Location Header [http://target.com] to [target.com]

**Comment by drk1wi** [comment]
Hm, weird. "Handle 302" is basically checking if there's a location header in the response and then it translates it. Can you try with v.1.1 (the new parameter name is proxyDomain instead of the phishingDomain)

		oldLocation := httpResponse.Header.Get("Location")
		newLocation := runtime.RegexpUrl.ReplaceAllStringFunc(string(oldLocation), runtime.RealURLtoPhish)

**Comment by romeorip** [comment]
Having the same problem for certain sites.
I'm testing modlishka on .onion sites, but i'm sure this is same for clearnet sites. Will test and update on that.
Here is my configuration:
`
{
  "proxyDomain": "utufkopjj3tf4jv6.onion",
  "listeningAddress": "127.0.0.1",
  "listeningPort": "80",
  "proxyAddress": "socks5://127.0.0.1:9050",
  "target": "dreadditevelidot.onion",
  "targetResources": "",
  "targetRules": "ZHJlYWRkaXRldmVsaWRvdC5vbmlvbg==:dXR1ZmtvcGpqM3RmNGp2Ni5vbmlvbg==",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "",
  "trackingParam": "",
  "useTls": false,
  "jsRules": "",
  "debug": true,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "",
  "plugins": "all",
  "credParams": "",
  "cert": "",
  "certKey": "",
  "certPool": ""
}
`
The first visit, I get redirect to the original domain. Then after some session/cookies have been set, the site doesn't do a redirect anymore, so Modlishka works without problem. But the first visit when the page gives redirect it can't handle it properly it seems.
Having the exactly same problem as above.
Here's the log:
`
Listening on [127.0.0.1:443]
Proxying HTTPS [dreadditevelidot.onion] via [https://utufkopjj3tf4jv6.onion]
Listening on [127.0.0.1:80]
Proxying HTTP [dreadditevelidot.onion] via [http://utufkopjj3tf4jv6.onion]
[Mon May 27 19:44:59 2019]  DBG  [RP] Checking domain: dreadditevelidot.onion
[Mon May 27 19:44:59 2019]  DBG  [P] Proxying target [http://dreadditevelidot.onion] via domain [utufkopjj3tf4jv6.onion]
[Mon May 27 19:44:59 2019]  DBG  Patching request Cookies [ab=1077fda9cc8226137c9909ee738dcfc2] -> [ab=1077fda9cc8226137c9909ee738dcfc2]
[Mon May 27 19:44:59 2019]  DBG  PatchHeaders: HTTPRequest took 453.882µs
[Mon May 27 19:44:59 2019]  DBG  rewriteRequest took 594.848µs
[Mon May 27 19:45:04 2019]  DBG  Rewriting Set-Cookie Flags: from
[dread=pjgbvp4pll46eanag8ut0b3nbl; path=/; HttpOnly]
 -->
[dread=pjgbvp4pll46eanag8ut0b3nbl; path=/; HttpOnly]
[Mon May 27 19:45:04 2019]  DBG  PatchHeaders: HTTPResponse took 763.991µs
[Mon May 27 19:45:04 2019]  DBG  [rw] Rewriting Response Body for (http://dreadditevelidot.onion): status[200] type[text/html; charset=UTF-8] encoding[gzip] uncompressedBody[76 bytes]
[Mon May 27 19:45:04 2019]  DBG  rewriteResponse took 1.825587ms
[Mon May 27 19:45:05 2019]  DBG  [RP] Checking domain: dreadditevelidot.onion
[Mon May 27 19:45:05 2019]  DBG  [P] Proxying target [http://dreadditevelidot.onion] via domain [utufkopjj3tf4jv6.onion]
[Mon May 27 19:45:05 2019]  DBG  PatchHeaders: HTTPRequest took 1.058µs
[Mon May 27 19:45:05 2019]  DBG  rewriteRequest took 57.893µs
[Mon May 27 19:45:05 2019]  DBG  [Proxy error][Error: context canceled]
[Mon May 27 19:45:05 2019]  DBG  [RP] Checking domain: dreadditevelidot.onion
[Mon May 27 19:45:05 2019]  DBG  [P] Proxying target [http://dreadditevelidot.onion] via domain [utufkopjj3tf4jv6.onion]
[Mon May 27 19:45:05 2019]  DBG  Patching request Cookies [ab=1077fda9cc8226137c9909ee738dcfc2; dread=pjgbvp4pll46eanag8ut0b3nbl] -> [ab=1077fda9cc8226137c9909ee738dcfc2; dread=pjgbvp4pll46eanag8ut0b3nbl]
[Mon May 27 19:45:05 2019]  DBG  PatchHeaders: HTTPRequest took 285.989µs
[Mon May 27 19:45:05 2019]  DBG  rewriteRequest took 652.57µs
[Mon May 27 19:45:06 2019]  DBG  [Proxy error][Error: context canceled]
`
This site works good except the first visit, but on some sites it get broken completely, first visit redirect then after login it redirects to original domain as-well.
And same error as above Rewriting Location Header [http://target.onion] to [target.onion]
Can try to write an example in PHP but I think this is self-explanatory.
As I said, only tried onion so far but going to try mirroring .onion target to loopback. We'll see if same problem occurs.

**Comment by drk1wi** [comment]
I haven't tried proxying anything through TOR yet, but I can see here several challenges here:
- proxy would have to be able to resolve .onion domains (you should make this possible at the OS level through example dnsmasq)
- Also try to  enable -disableSecurity option, it might be causing the redirects because of the DNS resolve errors or enable -dynamicMode
- you are also listening on the 127.0.0.1 only interface, not sure if it matters though.

[Proxy error][Error: context canceled] - this looks like there's something wrong with the remote connection.
