### ISSUE TITLE
GO lang problem

### ISSUE THREAD

**Issue by ArunDinfinity** [drk1wi/Modlishka#133]
golang.org/x/net/internal/socket
go/src/golang.org/x/net/internal/socket/rawconn.go:17: undefined: syscall.RawConn
$go version
go version go1.7.4 linux/amd64
but i actually installed go 1.11.1
when i use the following command 
$go get -u .......
i unstalled the older go version by 
rm -rf /usr/bin/local
i have a folder named go in my root directory should i need to remove it??

**Comment by ArunDinfinity** [comment]
does any can get me a already compiled version of modlishka

**Comment by ArunDinfinity** [comment]
> golang.org/x/net/internal/socket
> go/src/golang.org/x/net/internal/socket/rawconn.go:17: undefined: syscall.RawConn
> $go version
> go version go1.7.4 linux/amd64
> but i actually installed go 1.11.1
> when i use the following command
> $go get -u .......
> i unstalled the older go version by
> rm -rf /usr/bin/local
> i have a folder named go in my root directory should i need to remove it??
While using make
____________________________________________________________
:~/go/src/github.com/drk1wi/Modlishka# make
go test -v main.go main_test.go
# golang.org/x/net/internal/socket
../../../golang.org/x/net/internal/socket/rawconn.go:17: undefined: syscall.RawC                                                                                                             onn
FAIL    command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by ArunDinfinity** [comment]
already refer #39 but didnt work

**Comment by drk1wi** [comment]
can you try to update to : go version go1.12.1 darwin/amd64 and do go get -u all

**Comment by drk1wi** [comment]
I guess it worked. closing as resolved.

**Comment by Jae876** [comment]
Please does modlishka still work I've been trying to install it doesn't go get

**Comment by Jae876** [comment]
The command go get GitHub.com/drk1wi/modlishka doesn't run 
I've been trying

**Comment by Kiwi317** [comment]
Doesn't work prob

**Comment by drk1wi** [comment]
you have to read the docs.

**Comment by Jae876** [comment]
Where are the docs , didn't see any

**Comment by drk1wi** [comment]
https://github.com/drk1wi/Modlishka#installation
