### ISSUE TITLE
Connection header is missing

### ISSUE THREAD

**Issue by CG-root** [drk1wi/Modlishka#138]
I am trying to phish a Citrix login page but it is not working.
I compared two requests , one with Modlishka which is working and one without, which is not working.
I have noticed that the following header is missing:
Connection: keep-alive
Is it by purpose?

**Comment by drk1wi** [comment]
Hm. It shouldn't affect the target app. With the Connection header it works?

**Comment by CG-root** [comment]
I cannot be sure. but anyway, in my opinion, requests must stay identical and that's also including the headers order.
Can you kindly see what can be the cause for that?
thanks.
