### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by ali5634432** [drk1wi/Modlishka#140]
Hello there, thanks for your work, could you help me how to set up the modlishka to my custom domain, ex: mydomain.com , I have an VPS and i don't know how to set it up. Thanks.!! What A records I should put, and what I should write on the modlishka app. For ex: my domain: domainmodlishka.net, and the vps : 192.168.1.85

**Comment by drk1wi** [comment]
Hi, there's a WIKI page about this: https://github.com/drk1wi/Modlishka/wiki/How-to-use
