### ISSUE TITLE
i can't catch uuid!

### ISSUE THREAD

**Issue by CyberTheReape** [drk1wi/Modlishka#15]
I did everything right, but I still can't catch uuid . 

![yeni](https://user-images.githubusercontent.com/42475284/51078223-18adfc00-16c3-11e9-93de-c9d88c170d68.png)
![yeni3](https://user-images.githubusercontent.com/42475284/51078248-60cd1e80-16c3-11e9-9c05-6b7c1612aab5.png)
![yeni4](https://user-images.githubusercontent.com/42475284/51078259-91ad5380-16c3-11e9-9a8e-c1a346652e21.png)

**Comment by drk1wi** [comment]
what is the URL you are using to set the uuid?

**Comment by CyberTheReape** [comment]
I added this when the above method didn't work >> 
trackingParam : "/?ident=a0af4141-0e72-4407-b483-3ab65bd8c14e"

but did not work again.

**Comment by drk1wi** [comment]
it should work for the phishing_domain/?ident=a0af4141-0e72-4407-b483-3ab65bd8c14e. open new private window and check if ident cookie is set.

**Comment by CyberTheReape** [comment]
Something came to mind after turning off the computer..

Does the uuid number need to be preceded by a site name?

Example ;

loopback.modlishka.Something came to mind after turning off the computer..

Does the uuid number need to be preceded by a site name?

Example ;
Loopback.modlishka.io/?ident=uuid number

İt is true?

**Comment by CyberTheReape** [comment]
Ok i will try

**Comment by CyberTheReape** [comment]
Omg.. 2. Do I need a local domain address?

**Comment by CyberTheReape** [comment]
Omg..Do I need a local domain address?
I've watched your video again and you use 2 domains..
Do I need a local domain name for "tracking Param"?

**Comment by drk1wi** [comment]
trackingParam in your config should be "ident".  Believe me it works ;-)

**Comment by CyberTheReape** [comment]
yesssssssssssssssss... workeddd :)

thank you so much

**Comment by Decompiler** [comment]
@CyberTheReape Were you able to get it to work with TLS? I get the same issue you had without TLS but when I try TLS all the links on the sign in page are dead (in a private window). When not in a private window I get the same thing.
