### ISSUE TITLE
Cannot make

### ISSUE THREAD

**Issue by Jack-Rossy** [drk1wi/Modlishka#150]
I am getting this error when I use the make command:

go test -v main.go main_test.go
# github.com/drk1wi/Modlishka/plugin
plugin/control.go:259:11: undefined: http.SameSite
FAIL    command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

I can't figure out why http.SameSite is causing this command not to run.

Any help would be appreciated

**Comment by drk1wi** [comment]
You have to update to the latest Go version.

**Comment by lerrykayy** [comment]
> You have to update to the latest Go version.

Sir, I have latest GO version still stuck with this issue on my VPS but not on local machine running Kali
