### ISSUE TITLE
Handshake error with gsuite template

### ISSUE THREAD

**Issue by ProtoSync** [drk1wi/Modlishka#151]
When I login to a Gmail account with no 2FA on the loopback.modlishka.io URL, I get the following errors:

2019/06/23 15:33:21 http: TLS handshake error from 127.0.0.1:51166: EOF
2019/06/23 15:33:21 http: TLS handshake error from 127.0.0.1:51166: EOF

Command line: ./dist/proxy -config templates/google.com_gsuite.json

[JSON config]:

{
  "proxyDomain": "loopback.modlishka.io",
  "listeningAddress": "0.0.0.0",
  "proxyAddress": "",
  "target": "google.com",
  "targetResources": "content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ogs.google.com,accounts.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com",
  "rules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "jsRules":"",
  "jsReflectParam": "reflect",
  "debug": false,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "autocert,hijack",
  "credParams": "dHJ1ZVxdLCIoKD86XHcrW1wuXC1cX10pezAsfVx3KykiXQ==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert": "",
  "certKey": "",
  "certPool": ""
}

Browser: Firefox 68.0b12
OS: Kali Linux 2019.2 VirtualBox

I followed all the instructions given in this video: 
https://www.youtube.com/watch?v=BU-nONtY8O4

**Comment by morenikejiolawaletimothy** [comment]
having the same issue

**Comment by mrWhiteCrow** [comment]
Same.

**Comment by solomon-ey** [comment]
inbox for solution chieflyx@gmail.com
