### ISSUE TITLE
No captured credentials or control panel

### ISSUE THREAD

**Issue by brohan** [drk1wi/Modlishka#154]
Received a wildcard  Let's Encrypt cert  using acme (acme.sh --issue -d <mydomain> -d "*.<mydomain>" --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please). Placed the received .cer and .key in the appropriate variables in the plugin/autocert.go then made the executable file with no errors.

I then started the proxy with sudo ./dist/proxy -config templates/google.com_gsuite.json It appears to start fine. When I connect to the proxy VM from an outside IP, the connection goes through to Google,where I can navigate and enter my login credentials. Upon entering my credentials I am not seeing anything captured on the proxy VM. Also upon start-up I am not seeing any indication of a control panel startup. FWIW I did not get any certificate warning, indicating that the certs placed in the autocert are correct.

I noticed that the order of the IP's that are shown after starting the proxy are reversed from successful videos that I have watched.

The 2nd screenshot shows what happens when I try the microsoft template, which doesn't take me anywhere.

Thank you for your advice.

![Google_Success](https://user-images.githubusercontent.com/350410/61412156-f0cf6900-a89c-11e9-8197-fcde3a041f28.png)
![Orig_Screeshot](https://user-images.githubusercontent.com/350410/61412157-f0cf6900-a89c-11e9-9f61-9686d47b7097.png)

**Comment by joshfinley** [comment]
Sorry if this is a little after the fact... But did you ever figure out the problem? I'm experiencing something similar

**Comment by morenikejiolawaletimothy** [comment]
im experience somthing similar

**Comment by sabu2011** [comment]
![Screenshot_2019-12-17_23-05-38](https://user-images.githubusercontent.com/57928610/71779520-ffd9dd00-2fdc-11ea-945a-d9ead3ba8949.png)
any idea about this certificate error

**Comment by sabu2011** [comment]
![Screenshot_2019-12-17_23-05-38](https://user-images.githubusercontent.com/57928610/71836003-03528e80-30d9-11ea-97e3-e58e06b66e18.png)
can anyone solve this error
