### ISSUE TITLE
Couldn't sign you in

### ISSUE THREAD

**Issue by Incognito00** [drk1wi/Modlishka#156]
Hello! After authorization such notification takes off:
![53укаау](https://user-images.githubusercontent.com/53401121/62007476-5e9d4f80-b13d-11e9-8486-a340cae4d778.jpg)

After re-entering the data again -Couldn't sign you in
Help me to understand!

**Comment by siir4ever** [comment]
@Incognito00  do yo have any news about this error ?

**Comment by Incognito00** [comment]
Do I have one such problem?

**Comment by Incognito00** [comment]
{
  "proxyDomain": "****.***",
  "listeningAddress": "0.0.0.0",
  "proxyAddress": "http://***********2",
  "target": "account.google.com",
  "targetResources": "content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ssl.google-analytics.com,ogs.google.com,accounts.google.com,play.google.com,apis.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com",
  "rules": "",
  "terminateTriggers": "https://mail.google.com/",
  "terminateRedirectUrl": "https://mail.google.com/",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "jsRules":"",
  "jsReflectParam": "reflect",
  "debug": true,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "autocert,hijack",
  "credParams":

**Comment by siir4ever** [comment]
@Incognito00  do you have any update on this problem

**Comment by chiefofcoding** [comment]
i have a way out of this, chieflyx@gmail.com
