### ISSUE TITLE
plugin/control.go:263:11: undefined: http.SameSite FAIL    command-line-arguments [build failed]

### ISSUE THREAD

**Issue by newskl007** [drk1wi/Modlishka#157]
**Describe the bug**

**Expected behavior**

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).

**Screenshots**

**Additional context**
i keep getting this error 

 make
go test -v main.go main_test.go
# github.com/drk1wi/Modlishka/plugin
../go/src/github.com/drk1wi/Modlishka/plugin/control.go:263:11: undefined: http.SameSite
FAIL    command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

Anyone can help pls.

**Comment by safdar-sulthan-khan** [comment]
It's most likely about the go version you are using. Check `go version` to confirm.
I had the same issue, just upgraded it, had a successful build after.

**Comment by newskl007** [comment]
safdar-sulthan-khan what go version are you using ?

Do you have ICQ?

**Comment by newskl007** [comment]
I upgraded and am getting this now

 make
go test -v main.go main_test.go
# runtime/cgo
exec: "gcc": executable file not found in $PATH
FAIL    command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by iamtelo** [comment]
> safdar-sulthan-khan what go version are you using ?
> 
> Do you have ICQ?

bro can you set this up? i can pay a fee. do you have icq

**Comment by bhaktibhoj** [comment]
Just update go version to 1.11

**Comment by ad0nis** [comment]
@newskl007: Is this still reproducible on a current stable version of go? (I'm running builds reliably on go 1.14.4.)
