### ISSUE TITLE
 Domain + DNS

### ISSUE THREAD

**Issue by abouhad** [drk1wi/Modlishka#159]
I changed my proxyDomain = myurl.com
Set DNS "A" to "Host IP Modlishka"

Why it isn't working?

If I have a domain with SSL included I need the autocert plugin?

Thanks!

**Comment by jaredxx1** [comment]
You have to also add a CNAME record (wildcard).
eg: CNAME * myurl.com

**Comment by abouhad** [comment]
Solved

**Comment by lerrykayy** [comment]
> Solved

Can u help with installation please ?
