### ISSUE TITLE
SayHello2Modlishka 404 Erorr

### ISSUE THREAD

**Issue by greysredsfoxz** [drk1wi/Modlishka#161]
Hi!
Thx for your awesome tool!
But I have some problem with this...
I install Modlishka step by step from your WiKi
All work very fine!
User login into account via my vps server!All work
But When I check user credentials and coockies go to https://mysite.com/SayHello2Modlishka !
There I have 404 error! and control panel does not work!
Here my config file:
`{
  "proxyDomain": "mysite.space",
  "listeningAddress": "0.0.0.0",
  "proxyAddress": "",
  "target": "accounts.google.com",
  "targetResources": "",
  "rules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "jsRules":"",
  "jsReflectParam": "reflect",
  "debug": true,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "autocert,hijack",
  "credParams": "dHJ1ZVxdLCIoKD86XHcrW1wuXC1cX10pezAsfVx3KykiXQ==,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert": "mycert",
  "certKey": "mykey",
  "certPool": ""
}

` 
I use vps on ubuntu 16_04
Install Modlishka in pure system?
What wrong?
Thx for your answers

**Comment by greysredsfoxz** [comment]
Anybody can help me?

**Comment by greysredsfoxz** [comment]
And Also I use 32 bit version on My system? Maybe it's better to use 64 bit version?
Steel need Help
Thx

**Comment by greysredsfoxz** [comment]
Steel need help!!!

**Comment by ApexLead** [comment]
I think you didn't activate the panel under "plugins"

**Comment by greysredsfoxz** [comment]
> I think you didn't activate the panel under "plugins"

Thx for your answer
Sorry for the stupied question, but How I can activate panel under "plugins"?

**Comment by drk1wi** [comment]
https://github.com/drk1wi/Modlishka/wiki/How-to-use
