### ISSUE TITLE
empty panel when trying facebook

### ISSUE THREAD

**Issue by knsrky** [drk1wi/Modlishka#163]
Hello, first of all thanks for developing this program. My problem is that when I experiment with facebook, the panel appears blank.
My template configuration is:

> {
  "proxyDomain": "loopback.mydomain.com",
  "listeningAddress": "0.0.0.0",
  "proxyAddress": "",
  "target": "facebook.com",
  "targetResources": "",
  "rules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "id",
  "trackingParam": "id",
  "jsRules":"",
  "jsReflectParam": "reflect",
  "debug": true,
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "facebook.log",
  "plugins": "autocert,hijack,control_panel",
  "credParams": "email=(.*)&pass=(.*)",
  "cert": "cert",
  "certKey": "certkey",
  "certPool":"certpool"
}

When I look at the log file, all the information appears, but it is very complicated and there is a lot of log.
And my panel looks like:
![image](https://user-images.githubusercontent.com/3142380/64079979-56fe3700-ccf7-11e9-9a4f-1be3429b57a6.png)

Can you help me? Thanks again

**Comment by zenux11** [comment]
I have same issue...

**Comment by horllste** [comment]
"credParams": "email=(.)&pass=(.)",

thats where the problem is.

**Comment by ad0nis** [comment]
As the core of this issue is that creds aren't showing up in the admin panel, this appears to be user confusion about the credParams functionality, however this function also appears to have some bugs, so may effectively be another case of #213
