### ISSUE TITLE
Using Gmail's token - post login

### ISSUE THREAD

**Issue by ApexLead** [drk1wi/Modlishka#166]
Setup:
Modlishka Server - Ubuntu server
Client - Win10 VM

How can I use the session token on a different machine after a successful Gmail login through Modlishka?

**Comment by chiefofcoding** [comment]
come inbox chieflyx@gmail.com

**Comment by drk1wi** [comment]
chiefofcoding maybe you could start sharing something more than just your e-mail everywhere?

**Comment by horllste** [comment]
chief of coding don't know jack shit, I pity those who talk to him
