### ISSUE TITLE
You are trying to sign in from a browser or app that doesnt allow us to keep your account secure

### ISSUE THREAD

**Issue by StratoMusic** [drk1wi/Modlishka#167]
Getting this error now after login to Google in Modlishka, seems google released update, any fix?

**Comment by Incognito00** [comment]
https://github.com/drk1wi/Modlishka/issues/156
This notification does not always crash, if 2fa then everything is fine, also if the mail created long ago is also normal ...

**Comment by Delonorafrol** [comment]
Same issue. However, it works on the desktop version. I'm getting this error on Android.

**Comment by Delonorafrol** [comment]
Same here. I think it has to do with new security controls implemented by Google, specifically aimed at MITM attacks. You can read more about it here: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

Key Points:

"However, one form of phishing, known as “man in the middle” (MITM), is hard to detect when an embedded browser framework (e.g., Chromium Embedded Framework - CEF) or **another automation platform is being used for authentication.** 

And Again:

"Because we can’t differentiate between a legitimate sign in and a MITM attack on these platforms, we will be blocking sign-ins from embedded browser frameworks starting in June."

I'm not good enough in Golang to say whether this is the reason, or if it's another reason. That's being said, if this is the case, it's difficult to bypass.

**Comment by kennyyy53** [comment]
I got the same error as StratoMusic and don't understand how to resolve it. Has somebody the solution?

**Comment by kakanfo** [comment]
Also eager to see if anyone has a solution.

**Comment by siir4ever** [comment]
any news guys @kakanfo  @kennyyy53  @Incognito00  @StratoMusic

**Comment by devilspartner** [comment]
@StratoMusic  any solution bro please help

**Comment by kaligulaa** [comment]
> 
> 
> @StratoMusic any solution bro please help

There is a solution - telegram kaligulaaa (https://t.me/kaligulaaa)

**Comment by drk1wi** [comment]
Ok, why don't you create a PR and share with the community? I was deleting all of the comments about paid support or other advertisements, but this can't continue...

**Comment by willywilly12345** [comment]
> Ok, why don't you create a PR and share with the community? I was deleting all of the comments about paid support or other advertisements, but this can't continue...

Hello Piotr, How can i get in touch with you?

**Comment by chiefofcoding** [comment]
This is similar to gmail issue, come inbox chieflyx@gmail.com

**Comment by Blackselection** [comment]
hey guys, any solutions for this problem?

**Comment by drk1wi** [comment]
there's a solution but won't be made public for now.sorry

**Comment by equation-group** [comment]
> hey guys, any solutions for this problem?

> > Ok, why don't you create a PR and share with the community? I was deleting all of the comments about paid support or other advertisements, but this can't continue...
> 
> Hello Piotr, How can i get in touch with you?

> @StratoMusic any solution bro please help

**yes, there is, paid support, write your contact and mention me**

**Comment by ladversaire** [comment]
> > hey guys, any solutions for this problem?
> 
> > > Ok, why don't you create a PR and share with the community? I was deleting all of the comments about paid support or other advertisements, but this can't continue...
> > 
> > 
> > Hello Piotr, How can i get in touch with you?
> 
> > @StratoMusic any solution bro please help
> 
> **yes, there is, paid support, write your contact and mention me**

please help me to solve it and I will pay

**Comment by ladversaire** [comment]
> > > hey guys, any solutions for this problem?
> > 
> > 
> > > > Ok, why don't you create a PR and share with the community? I was deleting all of the comments about paid support or other advertisements, but this can't continue...
> > > 
> > > 
> > > Hello Piotr, How can i get in touch with you?
> > 
> > 
> > > @StratoMusic any solution bro please help
> > 
> > 
> > **yes, there is, paid support, write your contact and mention me**
> 
> please help me to solve it and I will pay

antoinedushaye@gmail.com

**Comment by toninikalai** [comment]
> **yes, there is, paid support, write your contact and mention me**

@eqn-group 

toninikalai@gmail.com

please write me. cheers
