### ISSUE TITLE
tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched . Terminating.

### ISSUE THREAD

**Issue by lerrykayy** [drk1wi/Modlishka#169]
TLS error pls help me. 

![image](\)

**Comment by drk1wi** [comment]
duplicate https://github.com/drk1wi/Modlishka/issues/54

**Comment by lerrykayy** [comment]
> duplicate #54

I copied the cert key to the autocert.go file.  Still acing the same issue pls is there any other workaround I could do?

**Comment by morenikejiolawaletimothy** [comment]
I copied the cert key to the autocert.go file. Still acing the same issue pls is there any other workaround I could do?

i'm facing the same issue too please kindly assist
