### ISSUE TITLE
Modlishka - Http Content Cancelled Error

### ISSUE THREAD

**Issue by Stormyworm90** [drk1wi/Modlishka#17]
Constantly getting Content Cancelled error.

**Comment by drk1wi** [comment]
I didn't see this error before. I would need some more info about your environment.

For start, try using the latest go version and ensure that you internet connection is stable.

**Comment by Stormyworm90** [comment]
Domain name: i'm using the default.
target domain: google.com
Then i launch the browser from the same machine where above configs have been done. I didn't configure any ssl certificate.

The latest go version was released when? I downloaded a go version last week.

**Comment by Stormyworm90** [comment]
Kindly see below details about  error message i'm getting i'm getting:

Listening on: [127.0.0.1:80] 
Proxying [loopback.modlishka.io:80] via --> [https://google.com] 
2019/01/14 13:53:59 http: proxy error: context canceled
[Mon Jan 14 18:54:05 2019]  WAR  rewriteResponse took 1.502860148s
2019/01/14 13:58:49 http: proxy error: context canceled
2019/01/14 13:58:49 http: proxy error: context canceled

**Comment by drk1wi** [comment]
this is related to https://github.com/golang/go/issues/20071. usually doesn't affect the proxy functionality.

**Comment by Stormyworm90** [comment]
Apart from the error messages, i'm not seeing anything. Can it work correctly with this:
"./dist/proxy   -target https://google.com -targetRes Https://google.com -phishingDomain loopback.modlishka.io -listeningPort 80"

How do i register a domain to use with Modlishka?

**Comment by drk1wi** [comment]
it should if you remove the targetRes. also set the listening address to 0.0.0.0 (as per wiki).
