### ISSUE TITLE
Error when compiling a windows file

### ISSUE THREAD

**Issue by rdbox** [drk1wi/Modlishka#171]
**Describe the bug**

**Expected behavior**

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (Windows 7).

**Screenshots**

**Additional context**
When compiling a file, an error 

![image](https://user-images.githubusercontent.com/18515862/65449769-52372980-de44-11e9-93fe-ba835229c3bb.png)

**Comment by drk1wi** [comment]
try with xgo (check out the makefile)
