### ISSUE TITLE
Not capturing post requests and how do i replace content ?

### ISSUE THREAD

**Issue by oldururw** [drk1wi/Modlishka#174]
I have a issue i tried capturing logins username and password / cookie but it dosent record them in the control panel /sayhell2mod its empty? the site itself works fine.

and how do i replace a image shown on the website with my own?

root@localhost:~/Projects/Proj1/src/github.com/drk1wi/Modlishka# sudo ./dist/proxy   -config templates/myconfig.json
[Sun Oct 19 09:47:48 2019]  INF  Enabling plugin: autocert v0.1
[Sun Oct 19 09:47:48 2019]  INF  Autocert plugin: Auto-generating xxxx
 domain TLS certificate
[Sun Oct 19 09:47:48 2019]  INF  Enabling plugin: control_panel v0.1
[Sun Oct 19 09:47:48 2019]  INF  Enabling plugin: hijack v0.1
[Sun Oct 19 09:47:48 2019]  INF  Enabling plugin: template v0.1
[Sun Oct 19 09:47:48 2019]  INF  Control Panel: SayHello2Modlishka handler registered	
[Sun Oct 19 09:47:48 2019]  INF  Control Panel URL: xxxx SayHello2Modlishka
[Sun Oct 20 09:47:48 2019]  INF  

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [127.0.0.1:443]
Proxying HTTPS [rxxxxxxxx] via [https:/xxxxxxxx]
Listening on [127.0.0.1:80]
Proxying HTTP [xxxxxxxxx] via [http:/xxxxxxxxxxxxx]

                                            File: templates/custom.json                                                      

{
  "proxyDomain": "xxxxxxxxxxxxxxxxx",
  "listeningAddress": "1xxxx",
  "proxyAddress": "soxxx",
  "target": "rxxxx",
  "targetResources": "",
  "rules": "by5zZXRBdHRyaWJ1dGUoImludGVncml0eSI=:by5zZXRBdHRyaWJ1dGUoImludGVnZHJpdHki,aW50ZWdyaXR5PQ==:aW50ZWdyaWN0eT0=,PC9oZWFkPg==:",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "cooke_id2,cookie_id2",
  "trackingParam": "",
  "credParams": "uname,Username,password",
  "jsRules":"",
  "jsReflectParam": "reflect",
  "debug": false,
  "forceHTTPS": false,
  "forceHTTP": true,
  "dynamicMode": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "2log",
  "plugins": "all",
  "cert": "",
  "certKey": "",
  "certPool": ""
}

**Comment by morenikejiolawaletimothy** [comment]
i have this same error please assist

**Comment by fraybabak** [comment]
Help

**Comment by horllste** [comment]
Hmmmnn, not for free

**Comment by solomon-ey** [comment]
email me for solution chieflyx@gmail.com

**Comment by drk1wi** [comment]
- credParams
This is parameter is registered by the 'control_panel' plugin. It's a comma separated list of username and password matching patterns using groups (regex). These values are also base64 encoded.

If you want Modlishka to automatically collect credentials, then you should create a regular expression that will pick the right value from the HTTP body. For instance:

HTTP Post body contains: " param1=test&param2=test2&password=secret&username=test ", then the regular expression for password should be: "password=([^\W]+)&" and for username "username=([^\W]+)".

- targetRules
Comma separated list of static strings and their replacements all base64 encoded. For example:

If you want to remove 'integrity' attribute from the html tag response, you would add the following parameter: -targetRules "aW50ZXJncml0eT0ic2hh,aW50ZXJncmlhdHk9InNoYQ=="

Note: This currently replaces strings in HTTP responses. If you want to modify the HTTP request check out the ./plugins/template.
