### ISSUE TITLE
Self-Signed Certificate ( loopback.modlishka.io)

### ISSUE THREAD

**Issue by ozone1864** [drk1wi/Modlishka#18]
Dear Piotr,
Thank you for this intelligent project
Everything is working fine except when
phishing google.com to the loopback.modlishka.io.
Certificates were generated successfully, inserted
to the .json config file and installed in the firefox browser.
Firefox keeps telling me ( Certificate is untrusted because its self signed)
The page is stuck in login gmail page "enter your username" and after that
doesnt go to the password field.
Can you elaborate ?
Best Regards

**Comment by drk1wi** [comment]
Hi,

How did you generate the certificate? remember that CA certificate goes to the autocert plugin (used for testing), while the final certificate (that should be also signed by a trusted CA) is set in the json file

**Comment by ozone1864** [comment]
openssl genrsa -out MyRootCA.key 2048
openssl req -x509 -new -nodes -key MyRootCA.key -sha256 -days 1024 -out MyRootCA.pem

added their values in autocert.go and converted them to base64 and inserted to .json config file
Installed the .pem certificate in the browser but still connection unsecure ( It says this certficate belongs to another domain, the certficate seems self-signed untrusted )
The question is how can I trust the certificate I generated

**Comment by drk1wi** [comment]
this should only go to the autocert plugin. it will generate the certificate for you

**Comment by ozone1864** [comment]
Certificates generated for the loopback.modlishka.io domain can't be trusted 
I tried all the ways didn't work either

**Comment by ozone1864** [comment]
in the json config file (\n instead of new lines) and in autocert.go (contents of certificates are copied and pasted without converting to base64 or inserting \n)
Thats what I did 
I will try some troubleshooting 
Thank you !

**Comment by drk1wi** [comment]
but if you are using the autocert, then you don't need to add a certificate to the JSON file (at least for testing). try removing the cert from JSON config. and trust the previously generated CA cert.

**Comment by Ekpeghre** [comment]
how can I hacked account?
