### ISSUE TITLE
[Question] Add a redirect at the end of the HTTPRequest method

### ISSUE THREAD

**Issue by k3rne1pan1c** [drk1wi/Modlishka#182]
**Question**
In plugin/control.go you define the HTTPRequest method for the interface. Would it be possible to have the http.ResponseWriter in that method too, to do a redirect to a different page? I couldn't figured out a way how i could solve this problem.

**Comment by ad0nis** [comment]
@philippklemmer I'm not sure about the area you're pointing at in the code, but it sounds like the key is that you'd like to redirect users after authentication. Are you perhaps looking for these built-in functions?
```
  -terminateTriggers string
    	Session termination: Comma separated list of URLs from target's origin which will trigger session termination
    		
  -terminateUrl string
    	URL to which a client will be redirected after Session Termination rules trigger
```
