### ISSUE TITLE
2 bug :-(

### ISSUE THREAD

**Issue by VVaReD** [drk1wi/Modlishka#185]
I have 2 bug, my first one is not username, and my second one google security error, please HELP

![IMG_0012](https://user-images.githubusercontent.com/49241224/72260006-1f42bc80-3612-11ea-8a25-7cb700e1f42f.jpg)
![IMG_0013](https://user-images.githubusercontent.com/49241224/72260015-24a00700-3612-11ea-8a58-15f043e6afc5.jpg)

**Comment by drk1wi** [comment]
You will have to work on your regular expression for the username. 
Re Google new security measure for 2FA the solution won't be published for several reasons.

**Comment by VVaReD** [comment]
hoo :-( i understand, thanx you for your reply
