### ISSUE TITLE
config template, broken link

### ISSUE THREAD

**Issue by DavidGrahambell** [drk1wi/Modlishka#19]
Hi,

Following link is broken. 

https://github.com/drk1wi/Modlishka/templates/

And just don't get the point to define certificates both in plugin file and json file..

**Comment by drk1wi** [comment]
Hi, Where is this link taken from? I will correct it.

The autocert plugin is used to automatically generate certificates for testing... which I have found extremely useful. It will take your self signed CA, that is locally trusted and generate a certificate for an arbitrary domain ... no need to do it manually.

In JSON you define your final certificate.

**Comment by DavidGrahambell** [comment]
I see..

I could not find too :) Templates can be accessible for the following link.

https://github.com/drk1wi/Modlishka/tree/master/templates
