### ISSUE TITLE
google phishlet question

### ISSUE THREAD

**Issue by horllste** [drk1wi/Modlishka#190]
the question is as simple as....

the functionalty to bypass google login security, is it something that will be done in Modlishka code itself or something that will be bypass in the phishlet.

i just want to know where to divert my attention.
thanks

**Comment by solomon-ey** [comment]
come inbox let's discuss there. chieflyx@gmail.com

**Comment by chiefofcoding** [comment]
i have got some solution about this, email: chieflyx@gmail.com

**Comment by drk1wi** [comment]
phishlets are Evilginx. Use which ever one suits you best :)
