### ISSUE TITLE
Using a different port other than 80

### ISSUE THREAD

**Issue by anoduck** [drk1wi/Modlishka#191]
I need to run Modlishka on a different port so that it does not interfere with nginx who is listening on port 80 for http traffic. I was going to use nginx to forward traffic to Modlishka for the domain I am using for the proxy (i.e. http://myproxy.example.net). So when a client connects to http://myproxy.example.net nginx will forward traffic to Modlishka to do it's magic. I noticed that port 80 and 443 is hard coded into Modlishka's source, and was wondering if there was any way to alter what port modlishka was listening on via the configuration files? Or am I going to have to modify the code and recompile modlishka?

**Comment by drk1wi** [comment]
this should be fixed

**Comment by anoduck** [comment]
Wow, that totally rocks! Thanks!
