### ISSUE TITLE
Handle 302 is broken, chaning the top domain

### ISSUE THREAD

**Issue by cube0x0** [drk1wi/Modlishka#192]
**Describe the bug**
whenever the web server makes a 302, the top domain changes
http://ct04zqjg2jamfameqqh4ytut1ee9j.loopback.modlishka.iob/index.php/login
from .io to .iob

**Expected behavior**
Expecting the redirected URL to be http://loopback.modlishka.io/index.php/login or http://ct04zqjg2jamfameqqh4ytut1ee9j.loopback.modlishka.io/index.php/login

**Configuration (please complete the following information):**
 - Modlishka configuration
./dist/proxy -target 'mydomain.lab' -proxyDomain 'loopback.modlishka.io' -listeningAddress '0.0.0.0' -debug -disableSecurity -log nextcloud.log
 - Browser
Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
 - OS
Latest kali build

Proxying HTTP [mydomain.lab] via [http://loopback.modlishka.io]
[Thu Feb 27 18:59:28 2020]  DBG  [P] Proxying target [http://mydomain.lab] via domain [loopback.modlishka.io]
[Thu Feb 27 18:59:28 2020]  DBG  Patching request Cookies [oc3sau9x3hp8=akkll1lpv4gtk2sejd8vej54dj; oc_sessionPassphrase=jN9rF7eyDTadc8zxn6YPPlTwiZIxwpDLV0IKLPrH0T8PWp9kCRNqdxXcks0IOHA58X4Lc10sZxAh0%2Fp%2FkLyXd%2FNJ%2FaacWQCju%2F4SuiJVtMe3bWSZCeNZIjodlOKtsOAJ; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true] -> [oc3sau9x3hp8=akkll1lpv4gtk2sejd8vej54dj; oc_sessionPassphrase=jN9rF7eyDTadc8zxn6YPPlTwiZIxwpDLV0IKLPrH0T8PWp9kCRNqdxXcks0IOHA58X4Lc10sZxAh0%2Fp%2FkLyXd%2FNJ%2FaacWQCju%2F4SuiJVtMe3bWSZCeNZIjodlOKtsOAJ; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true]
[Thu Feb 27 18:59:28 2020]  DBG  PatchHeaders: HTTPRequest took 109.863µs
[Thu Feb 27 18:59:28 2020]  DBG  rewriteRequest took 187.684µs
[Thu Feb 27 18:59:28 2020]  DBG  Rewriting Location Header [http://mydomain.lab/index.php/login] to [http://ct04zqjg2jamfameqqh4ytut1ee9j.loopback.modlishka.iob/index.php/login]
[Thu Feb 27 18:59:28 2020]  DBG  PatchHeaders: HTTPResponse took 106.561µs
[Thu Feb 27 18:59:28 2020]  DBG  Fallback to default compression ()
[Thu Feb 27 18:59:28 2020]  DBG  [rw] Rewriting Response Body for (http://mydomain.lab): status[302] type[text/html; charset=UTF-8] encoding[] uncompressedBody[0 bytes]
[Thu Feb 27 18:59:28 2020]  DBG  rewriteResponse took 161.966µs

**Comment by mcoincash** [comment]
ICQ here: @chiefcoder, let's fix this

**Comment by cube0x0** [comment]
Figured out that Modlishka only supports certian top domains
