### ISSUE TITLE
Lame

### ISSUE THREAD

**Issue by elis-k** [drk1wi/Modlishka#194]
This is needs more code to be complete
Wiki is trash
Its impossible to setup a working fucking ssl certificate
Better not published this at all, would've saved people efforts and time they spent trying te get this shit to work

**Comment by horllste** [comment]
hey @elis-k most times developers makes dangerous application harder to setup or install to avoid wrong people using them, you could have asked for help, reply with the preferred method of contacting you.

**Comment by icq744701700** [comment]
what is the issue are you finding solution to?

**Comment by drk1wi** [comment]
if you can't generate a valid cert you are better off somewhere else .
