### ISSUE TITLE
Madlishka backdoored

### ISSUE THREAD

**Issue by analyserdmz** [drk1wi/Modlishka#195]
**Describe the bug**
At Jan 17, 2019 the AT&T Tech Channel made a video about Madlishka, where they are saying that Madlishka is backdoored and the coder(s) behind it are getting copies of (our) the harvested credentials. Is this a fact?

**Video**
[https://youtu.be/azOJGYHANTc?t=108](https://youtu.be/azOJGYHANTc?t=108)

**Comment by drk1wi** [comment]
There was a discussion about this on twitter some time ago: https://twitter.com/vysecurity/status/1204447606190927873 . 
It's all open source.
