### ISSUE TITLE
IP address 

### ISSUE THREAD

**Issue by Raylee1** [drk1wi/Modlishka#197]
When a user logs in, it uses the VPS IP address. I was wondering whether it would be possible to have the user login using its own IP instead of the VPS IP.

I have to say, I am fairly impressed with Modlishka. 

Great work drk1wi!

**Comment by drk1wi** [comment]
hey, what do you mean by users' own IP? This info is being logged and written to a log file.

**Comment by herokucom2** [comment]
As I understand it, he meant is it possible to make it so that the end site receives the IP of the client and not the server where the Modlishka is installed, I'm also looking for a solution to this issue
