### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by ghost** [drk1wi/Modlishka#198]
After I get the git hub code and try to cd to it it says this;

cd: /src/github.com/drk1wi/Modlishka/: No such file or directory

**Comment by horllste** [comment]
cd: go/src/github.com/drk1wi/Modlishka/

**Comment by Misko2468** [comment]
> cd: go/src/github.com/drk1wi/Modlishka/

I actually think it may have messed up installation, heres a picture of the 1st 2 steps;   

https://i.stack.imgur.com/4NREO.png

**Comment by horllste** [comment]
Hmmmm, wow

**Comment by horllste** [comment]
If you need my help you will need to install teamviewer and give me your email to chat with you

**Comment by Misko2468** [comment]
Sure, do I need a mic or can we just email or what ever, I've never used teamviewer before

**Comment by Misko2468** [comment]
Oh and my email is michaelschemmel2468@gmail.com

**Comment by Misko2468** [comment]
I can do this any time
