### ISSUE TITLE
Errors with incorrect GO version

### ISSUE THREAD

**Issue by RealLinkers** [drk1wi/Modlishka#2]
I am running into a few errors when compiling with different versions of GO. Which version should be used?

**Comment by drk1wi** [comment]
I am using : go version go 1.11.1. Can you paste the errors?

**Comment by drk1wi** [comment]
This error can be related to the autocert plugin, which required a valid CA PEM certificate. Please check out the wiki page on how you can generate one.

**Comment by CyberTheReape** [comment]
@drk1wi this is path problem.. i did install go1.11.1 .. but i cant run "make"

but go1.10.1 is working
