### ISSUE TITLE
Couldn't sign you in GOOGLE.COM

### ISSUE THREAD

**Issue by s1im3rOK** [drk1wi/Modlishka#200]
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
server replacement is it decided? and how to set up your server.

**Comment by horllste** [comment]
its more complex than you think

**Comment by Yulia1991lab** [comment]
Please help me with a working google template.
Please email me at Yulia19@uymail.com

Thanks

**Comment by Blackselection** [comment]
same problem over here, any ideas?
