### ISSUE TITLE
Invalid Subdomains Prepended to URLs in Response Body

### ISSUE THREAD

**Issue by ShawnDEvans** [drk1wi/Modlishka#201]
**Describe the bug**
Modlishka is inserting superfluous subdomains into URLs within the response body of the target (proxied) site.  This prevents things like CSS, JS, and Images from loading correctly on the phishing domain.

**Expected behavior**
URLs and linked resources are translated 1:1 from target -> proxyDomain

**Configuration (please complete the following information):**
 - Modlishka configuration [JSON config]
"proxyDomain": "evil.phishing.site",
  "listeningPort": "443",
  "listeningAddress": "0.0.0.0",
  "target": "good.target.com",
  "targetResources": "",
  "targetRules": "PC9oZWFkPg==:",
  "controlURL": "WTFModlishka",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "authToken",
  "trackingParam": "authToken",
  "forceHttps": true,
  "useTls": true,
  "jsRules":"",
  "dynamicMode": true,
  "debug": true,
  "logPostOnly": true,
  "credParams": "ZW1haWxhZGRyZXNzPShbQS1aYS16MC05X1wuXSspJg==,cGFzc3dvcmQ9KFtBLVphLXowLTlfXCNcQFwhXF5cLlwkXCVcKlwrXD1cfFwsXSspJg==",
  "disableSecurity": true,
  "log": "aspen.log",
  "plugins": "core_plugin,hijack",
....snip

**Additional context**
Original URL on target (ex):

`<link href="https://good.target.com/css/bootstrap.min.css" rel="stylesheet">`

Proxy domain HTML translation:

`<link href="https://un5u62hhgj5puqegm3c0.evil.phishing.site/css/bootstrap.min.css" rel="stylesheet">`

With the injection of a superfluous subdomain "un5u62hhgj5puqegm3c0" the FQDN no longer resolves to a valid IP, and the resources don't load.

**Comment by ShawnDEvans** [comment]
I had a misconfiguration in my JSON file. Closing this one.

**Comment by magic0x00** [comment]
What was misconfigured??
