### ISSUE TITLE
panic while converting phish url to real url

### ISSUE THREAD

**Issue by jbuhacoff** [drk1wi/Modlishka#204]
**Describe the bug**
I setup Modlishka to proxy my website (A). The website (A) shows an iframe pointed at a second website (B). Modlishka auto-generates a subdomain for the second website (B) but requests fail due to an exception caused by these lines in file `runtime/func.go` function `PhishURLToRealURL`:

```
	u, _ := url.Parse(phishURL)
	out = phishURL

	// Parse both cases with http url scheme and without
	if u.Host != "" {
		host = u.Host
	} else {
		host = phishURL
	}
```

The phishURL being passed to `url.Parse` is the correct auto-generated subdomain and path (see example below) but it's missing the scheme `https://` so `u` contains nil and then checking `u.Host` throws the exception.

**Expected behavior**
Since Modlishka is written to work with both `http` and `https` schemes it seems that the `phishURL` input to that function is missing the scheme because it is expected to be automatically restored based on the request prior to parsing the URL.

**Configuration (please complete the following information):**
Here is my configuration file, omitting the base64 data for cert, certPool, or certKey:

```
{
"cert": "-----BEGIN CERTIFICATE-----\n<snip>\n-----END CERTIFICATE-----\n",
"certPool": "-----BEGIN CERTIFICATE-----\n<snip>\n-----END CERTIFICATE-----\n",
"certKey": "-----BEGIN PRIVATE KEY-----\n<snip>\n-----END PRIVATE KEY-----\n",
"target": "example.com",
"proxyDomain": "modlishka.example.tld:12345",
"listeningAddress": "192.168.1.1",
"trackingParam": "modlishka"
}
```

I tested with Chrome 81.0.4044.113 and FireFox 81.0.4044.113 on Windows 10

**Screenshots**
Here's an example URL that the browser requested which resulted in the panic:

```
https://subdomain.modlishka.example.tld:12345/path/to/content.html?color=%23ffffff&percent=100%25
```

**Additional context**
I made a small change to `runtime/func.go` to solve this issue in my environment. Will submit pull request.

**Comment by drk1wi** [comment]
You fix has been merged to the code base. Thank you for your time.
