### ISSUE TITLE
port closed

### ISSUE THREAD

**Issue by Rostiwhite** [drk1wi/Modlishka#21]
Hello! Good project!

I just have a problem with my ports. After starting the proxy my ports 443 and 80 are still closed... What can be the problem? Thank you!
![ffff](https://user-images.githubusercontent.com/46712651/51206438-b6e2d180-1910-11e9-80e5-a876c7f32f3c.png)

**Comment by drk1wi** [comment]
it's either a firewall issue or the listening address '127.0.0.1'

**Comment by Rostiwhite** [comment]
I don't have firewall and with 0.0.0.0 again ports are closed...

**Comment by drk1wi** [comment]
You probably haven't trusted the generated CA.

**Comment by Rostiwhite** [comment]
I have used acme.sh and openssl and cannot fix it. when I use open ssl after that convert files and then use it. I follow all steps since couple of days and everytime something goes wrong :)

**Comment by drk1wi** [comment]
try with an example scenario and autocert plugin. It's described on the WIKI. It's tested and works ;-)

**Comment by Rostiwhite** [comment]
Will try and will let you know. Thank you!

**Comment by Rostiwhite** [comment]
So.. I got this on the photo and after login with 2FA I got message for cookies: You don't can sign into your google account: delete cookies..... 
After cookies deleting got the same problem
![1](https://user-images.githubusercontent.com/46712651/51326445-d34d4e00-1a77-11e9-8282-291e76c0cf87.png)

**Comment by drk1wi** [comment]
I will look into this, in the meantime use https (it works).

**Comment by Rostiwhite** [comment]
Will be great if I can get step by step guide. Thank you!

**Comment by drk1wi** [comment]
please check the WIKI and the blog post, but I guess I will create an additional tutorial with all the steps in the nearest future.

**Comment by Rostiwhite** [comment]
I tried everything as possible and unsuccessful... I will wait the guide. Thank you anyway! And that is great project for all pentersters!

**Comment by drk1wi** [comment]
yes, then compile the application and trust the generated CA certificate. This will be enough

**Comment by drk1wi** [comment]
Here's the promised tutorial: https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial
