### ISSUE TITLE
no cookies captured 

### ISSUE THREAD

**Issue by pretech86** [drk1wi/Modlishka#211]
i used the last version for linux 
 sudo ./Modlishka-linux-amd64 -debug -listeningAddress 0.0.0.0 -proxyDomain MYDOMAIN.com -target https://www.google.com  

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi

Listening on [0.0.0.0:443]
Proxying HTTPS [https://www.google.com] via [https://MYDOMAIN.com]
Listening on [0.0.0.0:80]
Proxying HTTP [https://www.google.com] via [http://MYDOMAIN.com]
[Wed Jun 17 13:05:00 2020]  DBG  [RP] Checking domain: https://www.google.com
[Wed Jun 17 13:05:01 2020]  DBG  [P] Proxying target [http://https://www.google.com] via domain [MYDOMAIN.com]
[Wed Jun 17 13:05:01 2020]  DBG  Patching request Cookies [rxx=3434uht419c.1wj2h0kq&v=1] -> [rxx=3434uht419c.1wj2h0kq&v=1]
[Wed Jun 17 13:05:01 2020]  DBG  PatchHeaders: HTTPRequest took 101.457µs
[Wed Jun 17 13:05:01 2020]  DBG  rewriteRequest took 159.023µs
[Wed Jun 17 13:05:01 2020]  DBG  [Proxy error][Error: dial tcp: lookup https: no such host]
[Wed Jun 17 13:05:01 2020]  DBG  [RP] Checking domain: https://www.google.com
[Wed Jun 17 13:05:02 2020]  DBG  [P] Proxying target [http://https://www.google.com] via domain [MYDOMAIN.com]
[Wed Jun 17 13:05:02 2020]  DBG  Patching request Cookies [rxx=3434uht419c.1wj2h0kq&v=1] -> [rxx=3434uht419c.1wj2h0kq&v=1]
[Wed Jun 17 13:05:02 2020]  DBG  PatchHeaders: HTTPRequest took 28.747µs
[Wed Jun 17 13:05:02 2020]  DBG  rewriteRequest took 81.181µs
[Wed Jun 17 13:05:02 2020]  DBG  [Proxy error][Error: context canceled]
[Wed Jun 17 13:05:18 2020]  DBG  [RP] Checking domain: https://www.google.com
[Wed Jun 17 13:05:18 2020]  DBG  [P] Proxying target [https://https://www.google.com] via domain [MYDOMAIN.com]
[Wed Jun 17 13:05:18 2020]  DBG  Patching request Cookies [rxx=3434uht419c.1wj2h0kq&v=1] -> [rxx=3434uht419c.1wj2h0kq&v=1]
[Wed Jun 17 13:05:18 2020]  DBG  PatchHeaders: HTTPRequest took 37.168µs
[Wed Jun 17 13:05:18 2020]  DBG  rewriteRequest took 69.294µs
[Wed Jun 17 13:05:18 2020]  DBG  [Proxy error][Error: context canceled]

and no ccokies captured, any help please

**Comment by drk1wi** [comment]
There's a log file with all of the relevant browser session tracking info - including cookies.
