### ISSUE TITLE
bind: cannot assign requested address

### ISSUE THREAD

**Issue by encod3din** [drk1wi/Modlishka#216]
I ran `./dist/proxy -config templates/google.com_gsuite.json`
output
`listen tcp <public-ip>:443: bind: cannot assign requested address . Terminating.`

**Comment by ad0nis** [comment]
@encod3din: This is likely caused by another service already binding port 443 on your system. Ensure there are no conflicting listening services.

**Comment by drk1wi** [comment]
exactly. make sure you have sufficient rights to bind to the 80/443 ports.
