### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by Latour12** [drk1wi/Modlishka#217]
Hello, first of all thank you for the free access to your tools. I am a curious student. I wanted to use your tool to recover my old mailbox because I no longer had my sim at the time. I followed the wiki quickstart and went through all the steps. But arrived at the time to connect when I enter my email address I am blocked, it tells me that google does not allow connections on unauthorized browsers. Help me please.
![Capture d’écran_2020-08-05_10-06-28](https://user-images.githubusercontent.com/58258127/89393948-5ccc7b80-d703-11ea-8587-18e37c93a6d2.png)

**Comment by drk1wi** [comment]
this has been already discussed. Google implemented client side checks in JS, there's a bypass but won't be shared. 
Also, how do you want to recover your own account with this tool ?

**Comment by Latour12** [comment]
Hello. Thank you already for your answer. To answer your question, I had an
email account linked to my phone number that I lost three years ago. This
email address is still connected to some services and it's blocking me so
far because I lost my password. I was hoping that I could recover my
password by bypassing the 2FA verification so that I could then change the
recovery information. Thank you

Le mer. 12 août 2020 à 06:12, Piotr Duszynski <notifications@github.com> a
écrit :

**Comment by arcticmunkii** [comment]
> this has been already discussed. Google implemented client side checks in JS, there's a bypass but won't be shared.
> Also, how do you want to recover your own account with this tool ?

What's the point in even having a tool if you aren't going to update it to work? Why won't the bypass be shared?

**Comment by drk1wi** [comment]
well, you are free to not use it or provide some meaningful contribution other than complaints. 

The bypass is there, I don't see why should I share it, since the tool does what it's supposed to do. You can also check out other tools that focus on bypassing new security measures that aim to stop script kiddies...but this isn't the place where you'll get it.
