### ISSUE TITLE
This browser or app may not be secure and tls handshake error from 127.0.0.1 EOF

### ISSUE THREAD

**Issue by jaykali** [drk1wi/Modlishka#218]
I am getting problem on last step which means after i am putting the command "./dist/proxy -config templates/google.com_gsuite.json". By opening gmail it is showing as "This browser or app may not be secure". Then i used different website other than gmail to login but getting a error of "tls handshake error from 127.0.0.1 eof".

I am using Kali linux 2020.1 with firefox quantum 68.2 version.

**Comment by drk1wi** [comment]
check if the tool is listening on all ports and you will have to create your own certificate to get rid of the remaining tls related warnings.

**Comment by mandontsmile** [comment]
How do you check if its listening to all port

**Comment by vinnytroia** [comment]
Do yoiu have any more info around this? I am getting the same issue when trying to use the google template. No TLS handshake error though. I have a fully valid cert on the domain. Anything else i should be looking at?
