### ISSUE TITLE
About logs file and cookie filteration

### ISSUE THREAD

**Issue by arrange25** [drk1wi/Modlishka#221]
Hey, this tool works flawlessly and I really love it and wanted to ask if there any way to generate log files specific to user visit, rather than saving everything into 1 log file we can save logs per IP or any other way to differentiate between multiple sessions. Secondly, is there any way we can filter out cookies we need like we capture what we want in evilginx2.

**Comment by Sannimubarak** [comment]
@arrange25  hello, how are you doing? My name is sanni. I just configured modlishka on my VM everything runs fine but after visiting a target domain e.g google.com and entering an email I get this error below. Please do you know what might be the cause? Thanks in advance 🙌
ERROR:
This browser or app may not be secure. [Learn more]
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

Cookie “NID” has been rejected for invalid domain.
