### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by bojanrodic** [drk1wi/Modlishka#222]
Not sure if this is BUG really in software, maybe I do not understand how to use it.
Site works like this, it loads some pages, in meantime it uses js to hide login form, than after websockets api communicate with you several times and share some stuff than api says unhide login and than it refresh and shows login form.
i am not receiving that api packages in debug even, so i am not sure what to use to forward them?

**Comment by mandontsmile** [comment]
@bojanrodic does this tool still work

**Comment by bojanrodic** [comment]
Why it would not work, you only need to know how to use it ;)

**Comment by NaaeemMalik** [comment]
how to reverse proxy WebSocket ?
