### ISSUE TITLE
i try to use modlishka on my vps but when i run modlishka and open my webdomain i didnt get any phishing page its all same what is proble...and when i use local host still its give an erro that " link doesnt contain phishing site redirect to orignal site"

### ISSUE THREAD

**Issue by mikeyt143** [drk1wi/Modlishka#229]
i followed this steps https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing i try to use modlishka on my vps but when i run modlishka and open my webdomain i didnt get any phishing page its all same what is proble...and when i use local host still its give an erro that " link doesnt contain phishing site redirect to orignal site"

fisrt screenshot mistakly i uploded.i try url with salershub.in but it still show same result as second screenshot 

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).

**Screenshots
![Screenshot (514)](https://user-images.githubusercontent.com/65056151/97800913-f2be6680-1c5e-11eb-8dbb-cd87d9b87f2a.png)
![Screenshot (513)](https://user-images.githubusercontent.com/65056151/97800927-010c8280-1c5f-11eb-87b4-d38ce2b3cec1.png)

**Additional context**

**Comment by Bibleman1** [comment]
That step is perfect but you just have to edit your .config file well

**Comment by miarenny** [comment]
I'm having the same problem here, followed the https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing

Tutorial, still nothing shows (link doesn't show the phishing page, 
But on the website tutorial I followed
Their modlishka was working, 




Help me out here 


JSON config file

{
  "proxyDomain": "myaccess.live",
  "listeningAddress": "0.0.0.0",
  "target": "gmail.com",
  "targetResources": "",
  "targetRules":         "PC9oZWFkPg==:",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "id",
  "trackingParam": "id",
  "jsRules":"",
  "forceHTTPS": false,
  "forceHTTP": false,
  "dynamicMode": false,
  "debug": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "requests.log",
  "plugins": "all",
  "cert": "",
  "certKey": "",
  "certPool": ""
}

My ssl certificates are working just fine with the domain above, 

 Already have my cert and cert key pasted in the JSON config, 
I did a dns challenge with the above domain on my hosting provider 

Ssl (letsencrypt (acme-vo2

Pls what seems to be the problem

**Comment by miarenny** [comment]
![IMG_20201111_163003_9](https://user-images.githubusercontent.com/70172314/98933027-6d4d7880-24e0-11eb-9ec2-5287637db061.jpg)

**Comment by miarenny** [comment]
![IMG_20201111_163003_9](https://user-images.githubusercontent.com/70172314/98933364-d1703c80-24e0-11eb-82a1-7c87193df7b9.jpg)

I'm having the same problem here, followed the https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing

Tutorial, still nothing shows (link doesn't show the phishing page,
But on the website tutorial I followed
Their modlishka was working,

Help me out here

JSON config file

{
"proxyDomain": "myaccess.live",
"listeningAddress": "0.0.0.0",
"target": "gmail.com",
"targetResources": "",
"targetRules": "PC9oZWFkPg==:",
"terminateTriggers": "",
"terminateRedirectUrl": "",
"trackingCookie": "id",
"trackingParam": "id",
"jsRules":"",
"forceHTTPS": false,
"forceHTTP": false,
"dynamicMode": false,
"debug": true,
"logPostOnly": false,
"disableSecurity": false,
"log": "requests.log",
"plugins": "all",
"cert": "",
"certKey": "",
"certPool": ""
}

My ssl certificates are working just fine with the domain above,

Already have my cert and cert key pasted in the JSON config,
I did a dns challenge with the above domain on my hosting provider

Ssl (letsencrypt (acme-vo2

Pls what seems to be the problem

**Comment by kinda29487h** [comment]
Hello bro,
Same problemis this problem solved?
please contact me if you solved this problem
hagevo39@gmail.com
