### ISSUE TITLE
invalid URL port

### ISSUE THREAD

**Issue by fernandopaulista** [drk1wi/Modlishka#23]
I start the reverse proxy with the google_gsuite template and everything starts fine
but when I connect locally to loopback.modlishka.io 
all it gives me is a blank page and an error that says: invalid URL port port_number.google.com

**Comment by drk1wi** [comment]
everything works. just please follow the WIKI.

<img width="1398" alt="zrzut ekranu 2019-01-16 o 12 03 53" src="https://user-images.githubusercontent.com/2052966/51245096-05cb4e00-1987-11e9-9eea-6be5292f71d1.png">

**Comment by fernandopaulista** [comment]
![screen shot 2019-01-16 at 1 12 48 pm](https://user-images.githubusercontent.com/46745475/51245552-b0943a00-1990-11e9-84bc-8655af66fec9.png)

Hi,
This is a screenshot of the error I receive when I run the reverse proxy with the google template after adding the certificate parameters, and when I try connecting to loopback.modlishka.io I get this error

**Comment by drk1wi** [comment]
Interesting, this is an actual bug. Use 443 for now.

**Comment by fernandopaulista** [comment]
Okay thank you for your support

**Comment by Marcussk** [comment]
I second this Issue tried different parameters always encounter this bug when everything should work.

**Comment by dalbitresb12** [comment]
I tried using port 8443 because I have an instance of NGINX running on the same machine, and I also got the same bug. I had to stop NGINX while testing Modlishka.

**Comment by enema-combatant** [comment]
Also have nginx, thinking of removing it and clean testing on a new build for my other submitted issue.

**Comment by 0xa3q123** [comment]
Also have the same problem, followed wiki, used json, but for some reason it shows this error. I can't get it working on 443 either.

**Comment by drk1wi** [comment]
@0xa3q123 port 443 always worked. did you follow the quick start tutorial ?

**Comment by 0xa3q123** [comment]
Yeah i did follow the steps,in the quick start tutorial. Gonna test tonight on a clean system, but as far as for me even 443 doesnt work. Still gives the same error when i visit the website. 

2019/01/21 16:17:01 http: proxy error: invalid URL port "44.google.com"
2019/01/21 16:17:01 http: proxy error: invalid URL port "44.google.com"
2019/01/21 16:17:06 http: proxy error: invalid URL port "44.google.com"

**Comment by drk1wi** [comment]
@0xa3q123
paste the cmd line and config that you are using.

**Comment by aniketstark** [comment]
I am getting error like that
]  !!!  listen tcp 127.0.0.1:443: bind: permission denied . Terminating.

**Comment by mandontsmile** [comment]
pls pls mine its not working as for now Sep 2020 
After runing  modlishka it gives me blank page I tried it on port 443 and 80 ..... pls grant me temporarily access  to ur super brain 🙏 I need tips or if modlishka still works
