### ISSUE TITLE
i am using vps linux 18 and facing problem launching modlishka withmy domain 

### ISSUE THREAD

**Issue by testing-d-stuf** [drk1wi/Modlishka#230]
i folowed this steps https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing

**Describe the bug**
i am trying this for a week  still gating some problem when first time i use this evrything is working but nithing isshows on my domain when i visit that and now i have a error  """  !!!  Error unmarshalling JSON configuration (modlishka.json): invalid character '\n' in string literal . Terminating."'''
actualy i read coupple of qutions and i also try to do same but my problem isnt solve so thats why i amposting this question ...

1:  i try after removing comment in deffault config file 
2:: i also try use of orignle cert key pasting in .json file still same error i am posing all screen shot

![Screenshot (522)](https://user-images.githubusercontent.com/73996747/98236849-008b2900-1f8a-11eb-82ae-29ae5b3da7ce.png)
![Screenshot (519)](https://user-images.githubusercontent.com/73996747/98236873-0aad2780-1f8a-11eb-9ff3-261fd781253f.png)
![Uploading Screenshot (520).png…]()
![Screenshot (521)](https://user-images.githubusercontent.com/73996747/98236907-126ccc00-1f8a-11eb-9912-846d082ba9a2.png)
![Screenshot (523)](https://user-images.githubusercontent.com/73996747/98236997-38926c00-1f8a-11eb-9b0d-66a7fcbf5090.png)

**Comment by testing-d-stuf** [comment]
the second screen shot shows there in /n and afeter i add all deatails like third screenshot (screenshot just shows copy and pasted keys actuly i do like second screen shot ..i mean i am changed cofig file cert and pem key by as like )

but result doesnt changed

**Comment by waytehat** [comment]
You are at the wrong place 🤣🤣 tool not working, I've been trying to use it on Google which is their defult but it doesn't work

**Comment by testing-d-stuf** [comment]
ya i appericiate this answer ...but i still want answer from the community ...because this is a gret tool and its working ..ya in some cases the result isnt that as we want ....  i like this tool and want to know were i am doing mistake the contributer of this tool if you are reding pls explain ..i want to know ...this what goin wrong with my steps...

thanks

**Comment by miarenny** [comment]
You can use JSON validator to detect  the problem in your JSON config

It will show you the number that needs to be attended to

**Comment by ychauhan100** [comment]
awk '{printf "%s\\n", $0}' /etc/letsencrypt/live/domain/fullchain.pem
awk '{printf "%s\\n", $0}' /etc/letsencrypt/live/domain/privkey.pem

copy and paste to json file...do not paste in any notepad or anything

**Comment by testing-d-stuf** [comment]
.
