### ISSUE TITLE
Getting cookies error when trying to login Google

### ISSUE THREAD

**Issue by waytehat** [drk1wi/Modlishka#231]
Hi guy I'm trying to proxy through Google  , it proxies fine, but when I try to login, after writing my email and click next, it displays an error message
Please where am I getting it wrong and how do I resolve this
Thanks 💜
@dzsibi 
![IMG_20201107_014947](https://user-images.githubusercontent.com/73900744/98427314-f443c080-209c-11eb-9337-cd1df27a9fb7.jpg)

**Comment by miarenny** [comment]
Hi go to your browser settings and enable cookie 

Your browser cookie is disabled

**Comment by Bibleman1** [comment]
I don't think that's the problem cause I've done that already with different browsers, its definitely from Google

**Comment by ychauhan100** [comment]
same issue with me

**Comment by mandontsmile** [comment]
has anyone find a fix

**Comment by vinnytroia** [comment]
this happens when securityDisabled is set to true. Set it to false...

**Comment by Bibleman1** [comment]
@vinnytroia do your google templet work just fine?

**Comment by vinnytroia** [comment]
no, i can't get it to work. setting securitydisabled is just one thing, but then it causes another error. i dont think this tool works anymore

**Comment by Bibleman1** [comment]
google has many setup in place to prevent this tool i guess if u are tryna test u should use another website or another tool
@vinnytroia
