### ISSUE TITLE
My modlishka domain doesnt load up the phishing page for gmail 

### ISSUE THREAD

**Issue by miarenny** [drk1wi/Modlishka#233]
![IMG_20201111_163003_9](https://user-images.githubusercontent.com/70172314/98934592-a38bf780-24e2-11eb-8ac5-101797d405fc.jpg)
mikeyt143 opened this issue 11 days ago · 4 comments
Comments
@mikeyt143 mikeyt143 commented 11 days ago • 
i followed this steps https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing i try to use modlishka on my vps but when i run modlishka and open my webdomain i didnt get any phishing page its all same what is proble...and when i use local host still its give an erro that " link doesnt contain phishing site redirect to orignal site"

fisrt screenshot mistakly i uploded.i try url with salershub.in but it still show same result as second screenshot

Configuration (please complete the following information):

Modlishka configuration [e.g. command line flags, JSON config]
Browser [e.g. Chrome 72, Safari 12.0.0.1]
OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).
**Screenshots
Screenshot (514)
Screenshot (513)

Additional context

@mikeyt143 mikeyt143 changed the title i followed this steps https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing i try to use modlishka on my vps but when i run modlishka and open my webdomain i didnt get any phishing page its all same what is proble...and when i use local host still its give an erro that " link doesnt contain phishing site redirect to orignal site" i try to use modlishka on my vps but when i run modlishka and open my webdomain i didnt get any phishing page its all same what is proble...and when i use local host still its give an erro that " link doesnt contain phishing site redirect to orignal site" 11 days ago
@Bibleman1 Bibleman1 commented 10 days ago • 
That step is perfect but you just have to edit your .json file well

@miarenny miarenny commented 11 minutes ago
I'm having the same problem here, followed the https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing

Tutorial, still nothing shows (link doesn't show the phishing page,
But on the website tutorial I followed
Their modlishka was working,

Help me out here

JSON config file

{
"proxyDomain": "myaccess.live",
"listeningAddress": "0.0.0.0",
"target": "gmail.com",
"targetResources": "",
"targetRules": "PC9oZWFkPg==:",
"terminateTriggers": "",
"terminateRedirectUrl": "",
"trackingCookie": "id",
"trackingParam": "id",
"jsRules":"",
"forceHTTPS": false,
"forceHTTP": false,
"dynamicMode": false,
"debug": true,
"logPostOnly": false,
"disableSecurity": false,
"log": "requests.log",
"plugins": "all",
"cert": "",
"certKey": "",
"certPool": ""
}

My ssl certificates are working just fine with the domain above,

Already have my cert and cert key pasted in the JSON config,
I did a dns challenge with the above domain on my hosting provider

Ssl (letsencrypt (acme-vo2

Pls what seems to be the problem

**Comment by kinda29487h** [comment]
Hello bro,
Same problemis this problem solved?
please contact me if you solved this problem
hagevo39@gmail.com
