### ISSUE TITLE
unknown certificate authority

### ISSUE THREAD

**Issue by RonaldBrinkhuis** [drk1wi/Modlishka#234]
Dear,

I have just installed Modlishka. Followd the wiki ect...made the certificates and dit put them in the browser and trusted it. But when i start modlishka and go to https://loopback.modlishka.io it says:

TLS handshake error from 127.0.0.1:44464: remote error: tls: unknown certificate authority

Does someone know how to fix this problem? Already tried to do an complete reinstall but didn't work....

**Comment by francismbaka** [comment]
Please bro am stucked at inputting my cert in Firefox ..how did u do urs

**Comment by binarytrails** [comment]
@francismbaka you can convert the private key and certificate to p12, create password and import as p12 in firefox by providing your password
```
openssl pkcs12 -export -in server.crt -inkey server.key -out server.p12
```
