### ISSUE TITLE
Domain renaming on page

### ISSUE THREAD

**Issue by vinnytroia** [drk1wi/Modlishka#237]
**Describe the bug**
when trying to log into yahoo.com, Modlishka seems to re-write everything, including the name that is displayed on screen. 

**Expected behavior**
During Yahoo's login process, the email you entered is displayed on the screen for confirmation. It should not be renamed to your phishing domain.

**Comment by kvqymods** [comment]
are you able to get this to work for gmail / google? i can help with yahoo

**Comment by vinnytroia** [comment]
How does it work for yahoo? Once it switched pages it dies



Vinny Troia
www.nightlion.com
www.vinnytroia.com

________________________________
