### ISSUE TITLE
Acces denied

### ISSUE THREAD

**Issue by francismbaka** [drk1wi/Modlishka#238]
Hi am new to Kali linux
And the midkishka is not sure working aftersetuo
I dont know where am wrong cause i followed it by pricess. Is tgus great tool still working
Someone help me with 2020 latest versiin video setup or tut..cause i can see myca.pem
This is the error i receive
[Sun Dec 13 12:47:23 2020]  INF  Enabling plugin: autocert v0.1
[Sun Dec 13 12:47:23 2020]  INF  Autocert plugin: Auto-generating loopback.modlishka.io domain TLS certificate
[Sun Dec 13 12:47:24 2020]  INF  Enabling plugin: hijack v0.1
[Sun Dec 13 12:47:24 2020]  INF  

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [0.0.0.0:443]
Proxying HTTPS [google.com] via [https://loopback.modlishka.io]
Listening on [0.0.0.0:80]
Proxying HTTP [google.com] via [http://loopback.modlishka.io]
[Sun Dec 13 12:47:24 2020]  !!!  listen tcp 0.0.0.0:443: bind: permission denied . Terminating.

**Comment by francismbaka** [comment]
Hi anyone to helpM

**Comment by kvqymods** [comment]
hi if you can look into my ticket as well. might be able to share / help eachother

**Comment by bpsizemore** [comment]
@francismbaka the BIND error indicates that either there is already a service listening on port 443 OR you need to run modlishka as root in order to have permission to listen on that port.
