### ISSUE TITLE
couldn't sign you in 

### ISSUE THREAD

**Issue by fadelss** [drk1wi/Modlishka#240]
After I install the tool I start it and every thing look okay but the problem when I try to sing in the message showing that 
couldn't sign you in  user other app

this is after I start the tool 
1
https://mrkzgulfup.com/uploads/160961950731731.jpg

this is after I try to sign in 
2
https://mrkzgulfup.com/uploads/160962117129291.jpg

and after that I look to my terminal window
it showing 

3
 https://mrkzgulfup.com/uploads/160961950744493.jpg

**Comment by abdulwahab718** [comment]
same error anyone please help...

**Comment by abdulwahab718** [comment]
any reading i got same error but ignore google why INF is not loading of username and nothing is captured except ip i tryed on fb its not showing the usrname pass
