### ISSUE TITLE
$ go get -u github.com/drk1wi/Modlishka $ cd $GOPATH/src/github.com/drk1wi/Modlishka/

### ISSUE THREAD

**Issue by baodo1996** [drk1wi/Modlishka#243]
**Describe the bug**

**Expected behavior**

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).

**Screenshots**

**Additional context**

**Comment by knightdocomo** [comment]
I have been wrestling with Modlishka for days.
I can't proceed as I want.

In "Installation",
$ cd $ GOPATH / src / github.com/drk1wi/Modlishka/
$ make
You can't proceed from.


In the previous syntax
$ go get -u github.com/drk1wi/Modlishka
I don't know if I made a mistake or if the environment variables are bad.

It's rudimentary, but please teach me.

Thank you.
