### ISSUE TITLE
What’s the best way to redirect specific IP’s & Useragents?

### ISSUE THREAD

**Issue by epictendies** [drk1wi/Modlishka#245]
Thanks very much for Modlishka!

I would like to redirect specific hosts connecting to  my modlishka instance based on user agent or IP address.

I am trying to prevent crawlers, secure email gateways, proofpoint etc from seeing the cloned page and want to redirect them to another page on the system (a cat site created to dupe analysts or anyone/thing else that’s trying investigate the phishing site). I tried sticking nginx on the same box and doing a proxy_pass to modlishka but it didn’t work.. 

This is for sanctioned engagements, any pointers you could provide would be great.

**Comment by equation-group** [comment]
you can use nginx proxy before your main server to block google ips, crawlers and bots.

**Comment by epictendies** [comment]
> you can use nginx proxy before your main server to block google ips, crawlers and bots.

Thanks for leaving a comment! What would the redirector config / block look like to make this work?

**Comment by TomAbel** [comment]
> (a cat site created to dupe analysts or anyone/thing else that’s trying investigate the phishing site).

Better to just return a 404 code when possible. 

>  What would the redirector config / block look like to make this work?

Here's my config that I used for evilginx. The main site just displays a matrix picture and then accounts.example.com contains the phishing page. I deployed it for a few weeks, sent it to VirusTotal a lot of times, and still didn't end up in Safe Browsing blocklist.

I used nginx's Lua capabilities. It sends visitor IP to ipinfo.net so we can tell which organization the IP belongs to. If it belongs to a bad org we respond with a 404 page. Besides crawlers, you can also 404 specific countries. For example, I blocked all IPs coming from outside Estonia. The code is is a bit messy but I hope you get the point.

https://gist.github.com/TomAbel/551ed4fd8024d7554679419d59beaa0f

**Comment by epictendies** [comment]
This is great. Thanks so much for sharing. I look forward to playing with this. You’ve done all the hard work haha.
