### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by FreeHealthCareForEveryone** [drk1wi/Modlishka#248]
Hi can you please tell me how to properly adjust the "TargetResources" variable in the gsuite.json file when applying Modlishka to sites other than Google like FB or Insta? I get some DecodeSubdomain error [mabyt ] contains invalid characters. What do you have to change in the .json file to attack other websites, other than the "target" variable ofc?

**Comment by equation-group** [comment]
Credparams: here you have to put regex of target site whose credentials you want to extract.
