### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by thehillionaire** [drk1wi/Modlishka#25]
While testing Modlishka on a login portal with ReCaptcha v2 enabled, I received the following error when attempting to pass the captcha challenge to the victim's browser:

ERROR for site owner:
Invalid domain for site key

I recently noticed your tweet regarding Modlishka supporting ReCaptcha v2, is there any specific configurations that are needed to properly pass Captcha challenges?

**Comment by drk1wi** [comment]
It's possible that you will have to patch the relevant JS code.

If you test the default google config from the templates dir this works:
https://www.loopback.modlishka.io/recaptcha/api2/demo

**Comment by drk1wi** [comment]
Closing this issue since this is related to a specific JS bypass, that has to be created.

**Comment by thehillionaire** [comment]
Interesting, the error I am getting from the captcha challenge is "ERROR for site owner:
Invalid domain for site key". Any idea as to what a JS rule would look like to patch?
Thanks again!

**Comment by CyberTheReape** [comment]
@thehillionaire    i have same problem. could you do something about it?

**Comment by thehillionaire** [comment]
Not yet, but there's probably a JS substitution that has to be made using the -rules argument that could help.

**Comment by CyberTheReape** [comment]
@thehillionaire Do we need to add the in rules section in the config.json file? or Do we need to add the in jsRules section in the config.json file ? I share this information with you if I do

**Comment by f1h0** [comment]
problem with google recaptcha pass urgently need to decide what to do?

**Comment by Aulig** [comment]
Hey @drk1wi 
Just wondering what exactly you mean by patching the JS code. Do you mean intercepting the recaptcha JS and removing the domain check? Also, do you have that demo page somewhere still? It seems to be offline.

Thanks!
