### ISSUE TITLE
`Secure` cookie flag remove function breaks session handling for `SameSite=None;` cookies in Chrome 80+

### ISSUE THREAD

**Issue by awakenine** [drk1wi/Modlishka#250]
**Describe the bug**
The new cookie classification system, which was introduced in Chrome 80 earlier in 2020, is finally on all updated versions of the browser. The SameSite update changes how the web browser handles third-party cookies as a way to avoid possible cross-site request forgery (CSRF) attempts using cookies. Site owners need to explicitly label third-party cookies with `SameSite=None;` `Secure` in order to use them on other sites. Improperly labeled third-party cookies will be blocked by Chrome.

Strip out the secure flag causes conflict with this update, leading that cookie is blocked by Chrome.
https://github.com/drk1wi/Modlishka/blob/00a2385a0952c48202ed0e314b0be016e0613ba7/core/proxy.go#L228-L233

**Expected behavior**
`Secure` flag should not strip in case cookie has `SameSite=None;` attribute.

**Screenshots**
![image](https://user-images.githubusercontent.com/28957954/118608253-c95bc700-b7b9-11eb-97c1-dc88de275e6a.png)

**Comment by 1trackprojects1** [comment]
Yeah, i believe this is the cause of the problem which is causing the browser doesnt have cookies enabled when doing google.com.

I might be wrong but has anyone found any solutions to this yet?

**Comment by awakenine** [comment]
@1trackprojects1, Hello, I have changed 4 lines from 228 to fix it. Cookies works fine, but I am not sure that it won't cause other issues with user's session.
```golang
			//strip out the secure Flag - commented out as a hotfix for Chrome 80+
			//r := strings.NewReplacer("Secure", "", "secure", "")
			//cookie := r.Replace(v)
			cookie := runtime.RegexpFindSetCookie.ReplaceAllStringFunc(v, runtime.TranslateSetCookie)
```

**Comment by 1trackprojects1** [comment]
> @1trackprojects1, Hello, I have changed 4 lines from 228 to fix it. Cookies works fine, but I am not sure that it won't cause other issues with user's session.
> 
> ```go
> 			//strip out the secure Flag - commented out as a hotfix for Chrome 80+
> 			//r := strings.NewReplacer("Secure", "", "secure", "")
> 			//cookie := r.Replace(v)
> 			cookie := runtime.RegexpFindSetCookie.ReplaceAllStringFunc(v, runtime.TranslateSetCookie)
> ```

That is awesome, let me give it a try and see if it works.

**Comment by 1trackprojects1** [comment]
After making that change and compiling it solves the cookie problem but triggers a `This browser or app may not be secure.` issue.

Image: [https://i.ibb.co/8PtX410/image.png](https://i.ibb.co/8PtX410/image.png)

Google's learn more: [https://support.google.com/accounts/answer/7675428?hl=en](https://support.google.com/accounts/answer/7675428?hl=en)

**Comment by awakenine** [comment]
@1trackprojects1 Hey, can you share browser console output? And do you use letsencrypt cert, or self-signed cert?

**Comment by bf-cortex** [comment]
@awakenine @1trackprojects1 I have added "SameSite=None" to replacer. Isn't that a better solution?

**Comment by 1trackprojects1** [comment]
I don't think there was any error caused but i'll double check and send it to you. However this same error happens when you use selenium to login to any google account. I think its triggering something which is letting it know its not an "actual" chrome connection/browser
