### ISSUE TITLE
☆Modlishka Elementary question

### ISSUE THREAD

**Issue by knightdocomo** [drk1wi/Modlishka#251]
Hello!

I have been wrestling with Modlishka for days.
I can't proceed as I want.

In "Installation",
$ cd $ GOPATH / src / github.com/drk1wi/Modlishka/
$ make
You can't proceed from.

In the previous syntax
$ go get -u github.com/drk1wi/Modlishka
I don't know if I made a mistake or if the environment variables are bad.

It's rudimentary, but please teach me.

Thank you.

**Comment by equation-group** [comment]
follow answers from here: https://github.com/drk1wi/Modlishka/issues/253
