### ISSUE TITLE
credParams - office365

### ISSUE THREAD

**Issue by bsmithday** [drk1wi/Modlishka#26]
I'd appreciated if you can help me to figure out the regular expression for Office365. I passed the request through Burp to capture the following HTTP Post:

![http_post_o365](https://user-images.githubusercontent.com/34689042/51419895-a66e6900-1b53-11e9-93ab-5eb832d71c88.jpg)

**Comment by drk1wi** [comment]
I am sorry, but I cannot help with this one. You will have to prepare a regexp by yourself.
If you have any comments how the whole process could be improved or if you find any bugs, pls let me know
