### ISSUE TITLE
100$btc - Gmail Access Denied Issue - 100$btc Paying

### ISSUE THREAD

**Issue by equation-group** [drk1wi/Modlishka#262]
Hello,

I am trying modlishka to setup gmail reverse proxy- with prior permisison  for my red teaming assessment.
while doing so, as you already know it gives access denied after entering username.

Other said: remove gmail reverse proxy detection javascript, fingerprinintg , etc.

**Comment by TomAbel** [comment]
check out my repo. @tomkabel on TG if you need more help
