### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by akaymann** [drk1wi/Modlishka#265]
So i cant even pass the firs step, I am using i phone can i download it ?

**Comment by jbuhacoff** [comment]
Modlishka is an open source tool written in Go. If you want to use it, you need to install the Go compiler on your device. Here's the link: [Go](https://go.dev/). 

For iOS, you might want to check out [Go Mobile](https://github.com/golang/go/wiki/Mobile).

**Comment by George152-max** [comment]
I'm using nethunther Kali Linux how do I go about the compilation
