### ISSUE TITLE
tls: failed to find any PEM data in certificate input . Terminating.

### ISSUE THREAD

**Issue by enema-combatant** [drk1wi/Modlishka#27]
Launched:

`./proxy_linux -target https://www.targetdom.com -phishingDomain www.targetdom.me -tls -listeningAddress 0.0.0.0 -debug -cert ./cert.b64 -certKey ./privkey.b64`

- is '-tls' required?

- '-cert' is x509 **wildcard certificate** for *.targetdom.me signed by LetsEncrypt CA
-- original: _cert.pem_, converted: `cat cert.pem | base64 --wrap=0 > cert.b64`

- '-certKey' is x509 **private key** used to create request to [certbot](https://certbot.eff.org/) for submission to LetsEncrypt CA
-- original: _privkey.pem_, converted: `cat privkey.pm | base64 --wrap=0 > privkey.b64`

I may switch to in-package autocert and json, sounds simpler I suppose.

**Comment by drk1wi** [comment]
If you are using the cmd line parameteres, then you will have to : -cert `cat cert.b64` -certKey `cat privkey.b64`. Config files are more convenient to use.

**Comment by drk1wi** [comment]
This will be changed in the next release to read the certificates from a file.

**Comment by samraddha** [comment]
when i execute this command  ./dist/proxy  -config templates/google.com_gsuite.json
i get following error
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
	/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
	/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149
please tell me how to solve this error and start modlishka

**Comment by Ayushraj1** [comment]
I am using windows.
When I put the command  ./dist/proxy -config......

In cmd, says doesnot recognised as internal or external command..

**Comment by filebe777** [comment]
same here...im using kali ....result below
root@kali:~/go/src/github.com/drk1wi/Modlishka# sudo ./dist/proxy -config templates/google.com_gsuite.json
[Tue Mar 12 15:15:11 2019]  INF  Enabling plugin: autocert v0.1
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
	/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:105 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc00006a300)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc00002cc60, 0xc00002cc70, 0xc00002cc80, 0xc00002cc90, 0xc00002cca0, 0xc00002ccd0, 0xc00002cce0, 0xc00002ccb0, 0xc00002ccc0, 0xc00002ccf0, ...)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
	/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x18f

**Comment by c4udex** [comment]
Same for me on windows10 x64.

I've used the [quickstart-tutorial for local tests](https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial). After creating the certificate and inserting the file contents I get the same errors:

```shell
PS C:\Go\src\github.com\drk1wi\Modlishka> .\dist\proxy_windows -config templates/google.com_gsuite.json
[2m[Tue Apr  9 17:26:45 2019][0m [97m[42m INF [0m Enabling plugin: autocert v0.1
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
        c:/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:54 +0xc2f
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc0000a8120)
        c:/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0x102
github.com/drk1wi/Modlishka/plugin.Enable(0xc00005eb80, 0xc00005eb90, 0xc00005eba0, 0xc00005ebb0, 0xc00005ebc0, 0xc00005ebf0, 0xc00005ec00, 0xc00005ebd0, 0xc00005ebe0, 0xc00005ec10, ...)
        c:/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x119
main.main()
        c:/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x197
```

![ca_failed](https://user-images.githubusercontent.com/20425818/55821919-d7c95600-5afe-11e9-9a96-edeb53c2f297.png)

Looks legit for me. Any idea whats going wrong in here?

**Comment by c4udex** [comment]
> I am using windows.
> When I put the command ./dist/proxy -config......
> 
> In cmd, says doesnot recognised as internal or external command..

Use `make windows` to build it for windows and it will drop a `proxy_windows` file into the dist folder. Rename it to `proxy_windows.exe` and it will work.

Make sure to edit your command to `./dist/proxy_windows.exe` or, because windows is smart, `./dist/proxy_windows`.

**Comment by AnonyIND** [comment]
./dist/proxy -config templates/google.com_gsuite.json

listen tcp 0.0.0.0:443: bind: permission denied . Terminating.
How to fix ?

**Comment by morenikejiolawaletimothy** [comment]
tls: failed to find any PEM data in certificate input . Terminating.

Remove all the brakes on your fullchain.pem and privkey.pem before adding it to your modlishka.json file. that is make your fullchain.pem and privkey.pem be on a straight line.

**Comment by mdkiev0** [comment]
> when i execute this command ./dist/proxy -config templates/google.com_gsuite.json
> i get following error
> panic: tls: failed to find any PEM data in certificate input
> 
> goroutine 1 [running]:
> github.com/drk1wi/Modlishka/plugin.init.0.func1()
> /root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
> github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
> /root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
> github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
> /root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
> main.main()
> /root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149
> please tell me how to solve this error and start modlishka

the same problem, how to fix this ? 
ten sam problem, jak sobie z nim poradzic ?

**Comment by Immanuel2005** [comment]
WHEN I ENTER THIS COMMAND -  ./dist/proxy -config templates/google.com_gsuite.json

I got this error ... I tried more than 20 times

There is no solution for me
   
    panic: tls: failed to find any PEM data in certificate input

    goroutine 1 [running]:
    github.com/drk1wi/Modlishka/plugin.init.0.func1()
    /root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
    github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
    /root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
    github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
    /root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
    main.main()
    /root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149

PLEASE HELP ME !!!! TO START USING MODLISHKA TOOLS !!!! PLEASE

**Comment by danicastone** [comment]
> WHEN I ENTER THIS COMMAND - ./dist/proxy -config templates/google.com_gsuite.json
> 
> I got this error ... I tried more than 20 times
> 
> There is no solution for me
> 
> ```
> panic: tls: failed to find any PEM data in certificate input
> 
> goroutine 1 [running]:
> github.com/drk1wi/Modlishka/plugin.init.0.func1()
> /root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a

Looks like line 103 in autocert.go is where it takes whatever's in CA_CERT, and assigns it to a variable for the certificate. You need to open autocert.go and check what you pasted in under:

`// Paste your CA certificate and key in the following format
// Ref: https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial
const CA_CERT = `

It comes with a fake certificate filled in already, as an example. If you did not delete that, you need to delete it and replace it with your actual certificate data. If you did that already, you need to check what you pasted in, and make sure it's correct and doesn't contain any weird spaces or errors.

**Comment by Accessdenied0198** [comment]
If anybody is still having issues with this try reading how config.go works.  cert and certKey take a base64 encoded pem file.  This is why I was receiving the error about tls: failed to find any PEM data in certificate input
