### ISSUE TITLE
New Issues 

### ISSUE THREAD

**Issue by Ghostviewer01** [drk1wi/Modlishka#271]
Hello please I am getting an issue fetching 
go get -u github.com/drk1wi/Modlishka

**Comment by MemePorg** [comment]
have you tried using the command to get golang first?

sudo apt install -y golang

**Comment by Ghostviewer01** [comment]
Yes I tried but please I still have issues with some things like running modlishka, I can’t find it,  do you have a Skype or Telegram and maybe you can help me out better please? I hope to hear from you soon…Sent using the mobile mail appOn 2/16/22 at 7:57 PM, MemePorg wrote:
                
            
            
                
                    From: "MemePorg" ***@***.***>Date: February 16, 2022To: "drk1wi/Modlishka" ***@***.***>Cc: "Author" ***@***.***>,"Ghostviewer01" ***@***.***>Subject: Re: [drk1wi/Modlishka] New Issues  (Issue #271)
                
                
have you tried using the command to get golang first?
sudo apt install -y golang

**Comment by MemePorg** [comment]
So i can only get past the first step.

I recently opened an issue but they closed it saying it was "fixed".
While in reality, nothing changed.

The command i was having trouble with was the cd command.
Unfortunatly i cant help you because i cant do it either.
