### ISSUE TITLE
install

### ISSUE THREAD

**Issue by MemePorg** [drk1wi/Modlishka#277]
ive been trying to install modlishka on my kali linux virtual machine. the first command to install it works and i get

downloading github.com/drk1wi/Modlishka v0.0.0-20220212125659-478501469f12
go get: github.com/drk1wi/Modlishka@v0.0.0-20220212125659-478501469f12: parsing go.mod:
        module declares its path as: main
                but was required as: github.com/drk1wi/Modlishka
                                                                             
when i do the second command, i get this

no such file or directory: /src/github.com/drk1wi/Modlishka/

if someone could help me, it would be greatly appreciated.

**Comment by danchoixx** [comment]
same problem

**Comment by drk1wi** [comment]
fixed

**Comment by MemePorg** [comment]
im still getting the same message.
