### ISSUE TITLE
modlishka and windows

### ISSUE THREAD

**Issue by okofishe** [drk1wi/Modlishka#28]
Hello,
I try running modlishka on windows 10. It is not capturing any password or username even though the redirection works perfectly. Am missing something or modlishka will not run properly on windows 10. Any feedback will be highly appreciated

**Comment by ciberx** [comment]
Hi,  after cancel modlishka process, try kill all processes  
> sudo killall -r '.*'
and start modlishka again
or reboot Windows 10 and then start

**Comment by drk1wi** [comment]
I assume this solved the problem.

**Comment by Ayushraj1** [comment]
Hello I am trying to run modlishka in Windows 7, but can't run properly because

**Comment by Ayushraj1** [comment]
Reopen this or message me on discord ayush#0651
