### ISSUE TITLE
Kali Linux Modlishka Download Errors

### ISSUE THREAD

**Issue by jacmatmar** [drk1wi/Modlishka#280]
I am using this version of Golang https://go.dev/dl/go1.17.7.linux-amd64.tar.gz

I have been tryin to install Modlishka on Kali Linux & ran in to a few issues I'm not sure how to solve. 

go get -u github.com/drk1wi/Modlishka
This comes with the issue ;go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
So I try ;go install github.com/drk1wi/Modlishka 
This comes with the issue ;go install: version is required when current directory is not in a module
        Try 'go install github.com/drk1wi/Modlishka@latest' to install the latest version
So I try ;go install github.com/drk1wi/Modlishka@latest
This does not give me any further prompt but rather just resets the terminal. It does however comes with a 1 & red x.

Can someone help me with these issues? How do I get it to install?

Thank you in advance!

**Comment by AngelofFresno** [comment]
Huh. I couldn't replicate that, but I did run into other errors until I installed in the correct directory. Are you running `go get -u github.com/drk1wi/Modlishka` inside of go/src?
