### ISSUE TITLE
ayuda / help

### ISSUE THREAD

**Issue by theraphm** [drk1wi/Modlishka#281]
estoy instalando modlishka y tengo un problema en compilar , todos los pasos correctos hasta ese punto , hay que hacer algo especial con el autocert.go aparte de cambiar los codigos , como el certificarlo en el navegador?
si es asi como lo certifico antes de hacer el make.

**Comment by theraphm** [comment]
hamzahamzito15@penguin:~/go/src/github.com/drk1wi/Modlishka$ ls
config  extra   go.sum   log      main_test.go  MyCA.key  plugin     runtime    vendor
core    go.mod  LICENSE  main.go  Makefile      MyCA.pem  README.md  templates
hamzahamzito15@penguin:~/go/src/github.com/drk1wi/Modlishka$ make
-bash: make: command not found

**Comment by danicastone** [comment]
Si no encuentra make, debe ser que no has instalado go? Que ves si entras "go env"?
