### ISSUE TITLE
Tls SSl hanshake error

### ISSUE THREAD

**Issue by Chomikmarkus** [drk1wi/Modlishka#282]
**Describe the bug**

**Expected behavior**

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).

**Screenshots**

**Additional context**
Followed step by step full tutorial of install, all seems fine and working! When i run Modliska i get tls ssl error and webpage is blank!
![Screenshot_20220317-175132](https://user-images.githubusercontent.com/92059377/158840108-7b70c99e-59fc-41fe-9420-b0759e204a81.png)

**Comment by yeti-code** [comment]
You need to generate valid certificates "like with certbot", and include them in the modlishka JSON config file on runtime.

**Comment by Westsideff** [comment]
> You need to generate valid certificates "like with certbot", and include them in the modlishka JSON config file on runtime.
> 
> 

Bro please send your telegram or icq
