### ISSUE TITLE
droplet or system

### ISSUE THREAD

**Issue by a-bilal10** [drk1wi/Modlishka#285]
Hello, i am new to kali and pentensting... i have a confusion.
I have registered a domain, i just need to confirm should i also buy a VPS or can i use modlishka on my kali running on a virtual machine on my computer?

**Comment by 080Busybrain** [comment]
How did you know about modlishka so fast, if truly you are knew to Kali

**Comment by 080Busybrain** [comment]
Do you use WhatsApp?


*You can run it in a Virtualized env*
