### ISSUE TITLE
Control url doesnt work

### ISSUE THREAD

**Issue by MauzTrap** [drk1wi/Modlishka#287]
**Describe the bug**
When I go to open loopback.modlishka.io/SayHello2Modlishka I just get 404 not found and in the terminal if I connect with a separate device the terminal shows a warning saying "Host (my hosts ip) does not contain the phishing domain" I also notice when looking at videos of other people start ./dist/proxy -config that the little info pop ups show more plug-ins being enabled, one of them being "controlURL" that I didn't see get enabled on mine

**Expected behavior*
Just need to be able to see the collected credentials

**Configuration:**
 - Modlishka configuration 
 - Browser firefox
 - OS Kali Linux 2022.1

Photos attached
![16488908764678328375450661776187](https://user-images.githubusercontent.com/102853862/161376453-c9cf9ef8-97e0-478c-929a-05554cc5c91a.jpg)
![16488910314503935313531622030174](https://user-images.githubusercontent.com/102853862/161376562-7e1e881a-ee5f-4fec-8f02-ddfe8edb2854.jpg)

**Comment by MauzTrap** [comment]
I used the default Google template and that part worked fine it was the control url that shows the connections and user input that was shoeing 404

-------- Original Message --------

**Comment by 5a3ee** [comment]
You haven't included the control plugin in your config. Personally, I cannot get it to work unless I use `"plugins":"all"`.

**Comment by MauzTrap** [comment]
When I checked the template config file there wasn't a line for "phishing url" or "control url" they were both the same but at some point they changed the name so I didn't know if I should add a line in or not

**Comment by nakedpages** [comment]
Checkout 

> Nakedpages-Builder new Phishing app which allows you to run a battle tested and experienced phishing app in nodesJS, using a few lines of autogenerated JS code, Configuration for each project are written in Plain Javascript thus making everything and anything possible also giving you access to low level access to request/response object without making changes to the binary the whole platform runs on.

https://github.com/nakedpages

**Comment by MauzTrap** [comment]
> You haven't included the control plugin in your config. Personally, I cannot get it to work unless I use `"plugins":"all"`.

Could you explain further what you mean by use plugins all? Is that a command your typing into the terminal or is that something in one of the files you're editing? Sorry for the late response I've been very busy.

**Comment by yeti-code** [comment]
`"plugins": "all"`

Is from the JSON config file that you run with the "-config" flag set when you run the modlishka tool in your terminal.

**Comment by 080Busybrain** [comment]
Your configuration does not contain a target domain!!
Add your target domain in the template configuration
