### ISSUE TITLE
Redirect to Arbitrary Subdomain - Office365 Template

### ISSUE THREAD

**Issue by ATLTechLabs** [drk1wi/Modlishka#289]
When trying to use the modlishka office365 payload, upon loading the initial page everything works just fine. However, once I enter my username in the textbox and hit enter, it redirects me to this subdomain: 

7np70a2gfq540.test.com

and that page does not load any content at all. I'm working on building an office365 phishing page for work I'm doing with a client and need to figure out how to get this working. Any help would be appreciated!

**Comment by danicastone** [comment]
Where's it getting the subdomain? Have you tried running grep or otherwise searching the files for "7np70a2gfq540"?

**Comment by unknownx914** [comment]
> When trying to use the modlishka office365 payload, upon loading the initial page everything works just fine. However, once I enter my username in the textbox and hit enter, it redirects me to this subdomain:
> 
> 7np70a2gfq540.test.com
> 
> and that page does not load any content at all. I'm working on building an office365 phishing page for work I'm doing with a client and need to figure out how to get this working. Any help would be appreciated!

hello do you have a telegram account i could use to contact you as i may require your services

**Comment by barrywill4422** [comment]
Did u solve this issue
