### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by 4k1l3x** [drk1wi/Modlishka#29]
Hi and thanks a lot fot this amazing tool... can you help  me to solve this issue?
![issue](https://user-images.githubusercontent.com/46854743/51434113-93c56400-1c27-11e9-86a0-f6ddc62d2ba9.PNG)

**Comment by okofishe** [comment]
paste a copy of your json config file let us see

**Comment by drk1wi** [comment]
TODO: this error message should be handled internally without displaying it to the user.

**Comment by drk1wi** [comment]
Fixed in the latest release.
