### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by herosnevadie** [drk1wi/Modlishka#292]
using default gsuite,json
./dist/proxy -target https://google.com -config /home/kali/Modlishka/templates/google.com_gsuite.json
[Sun Jun 19 22:34:51 2022]  INF  Enabling plugin: autocert v0.1
[Sun Jun 19 22:34:51 2022]  INF  Autocert plugin: Auto-generating loopback.modlishka.io domain TLS certificate
[Sun Jun 19 22:34:51 2022]  INF  Enabling plugin: hijack v0.1
[Sun Jun 19 22:34:51 2022]  INF  

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [0.0.0.0:443]
Proxying HTTPS [google.com] via [https://loopback.modlishka.io]
Listening on [0.0.0.0:80]
Proxying HTTP [google.com] via [http://loopback.modlishka.io]
2022/06/19 18:34:58 http: TLS handshake error from 127.0.0.1:55928: remote error: tls: unknown certificate authority
2022/06/19 18:34:59 http: TLS handshake error from 127.0.0.1:55930: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55932: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55934: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55936: read tcp 127.0.0.1:443->127.0.0.1:55936: read: connection reset by peer
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55938: EOF
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55940: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55942: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55944: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55946: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55948: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55950: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55952: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55954: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55956: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55958: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55960: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55962: EOF
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55964: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55968: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55970: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55972: remote error: tls: unknown certificate authority
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55976: EOF
2022/06/19 18:35:06 http: TLS handshake error from 127.0.0.1:55974: remote error: tls: unknown certificate authority
2022/06/19 18:35:08 http: TLS handshake error from 127.0.0.1:55978: remote error: tls: unknown certificate authority

As you can see, got this unknown certificate error
Hello, I've heard that certbot fixes this error, but haven't the faintest idea on how to do this.

**Comment by George152-max** [comment]
We having same issue

**Comment by Rensodark** [comment]
You can reach out to @drk1wi on telegram for solutions
