### ISSUE TITLE
RPC executor service threw an error!

### ISSUE THREAD

**Issue by Cobycat780** [drk1wi/Modlishka#295]
When I sign into Google using Modlishka I get "RPC executor service threw an error!". How do I fix this?

**Comment by Voyts** [comment]
When i sign in i have "RPC executor service threw an error!". How this fix?

**Comment by Githack0** [comment]
Still No Solution?!!!

**Comment by Cobycat780** [comment]
> Still No Solution?!!!

Nope.

**Comment by nemobis** [comment]
This error appears when the login page fails to load cookies from google.com.
![Screenshot_20221021_084833](https://user-images.githubusercontent.com/901528/197122439-1f07944d-2fa8-49e8-b860-d015ea1739b0.png)
![Screenshot_20221021_085056](https://user-images.githubusercontent.com/901528/197122440-b4aeab82-1ad0-42c3-90f0-27f29f371b9e.png)

**Comment by Cobycat780** [comment]
> This error appears when the login page fails to load cookies from google.com. ![Screenshot_20221021_084833](https://user-images.githubusercontent.com/901528/197122439-1f07944d-2fa8-49e8-b860-d015ea1739b0.png) ![Screenshot_20221021_085056](https://user-images.githubusercontent.com/901528/197122440-b4aeab82-1ad0-42c3-90f0-27f29f371b9e.png)

Ok so how do we fix this?

**Comment by eatahn2001** [comment]
![D1048AE6-831F-4672-B691-71CDB5AAFE7F](https://user-images.githubusercontent.com/124448091/218778194-28aa4a13-dfd2-4e04-ac8a-d56e9709095a.jpeg)
![7E886600-4B7A-4DD8-A219-EDD3D11FDCC3](https://user-images.githubusercontent.com/124448091/218778208-c1d9b467-ef6c-4c56-958b-58419fa95102.jpeg)


Any solution ???

**Comment by Rensodark** [comment]
You can reach out to @drk1wi on telegram for solutions
