### ISSUE TITLE
>>>>>HELP PLEASE !!!<<<<<

### ISSUE THREAD

**Issue by anderzonzizz** [drk1wi/Modlishka#298]
GOOD EVENING, I TRIED TO INSTALL MODLISHKA ON PUTTY DEBIAN-VPS I FOLLOWED THE FOLLOWING TUTORIAL:
https://www.ired.team/offensive-security/red-team-infrastructure/how-to-setup-modliska-reverse-http-proxy-for-phishing
AFTER USING COMMANDS : ./Modlishka-linux-amd64 -config modlishka.json I SEE THE FOLLOWING ERROR:
![image](https://user-images.githubusercontent.com/113717414/193676846-dfeb940d-63b4-48ef-8df4-9d7fa1af2487.png)

>>

![image](https://user-images.githubusercontent.com/113717414/193678229-96d48f06-bf3c-4c54-801f-b78132b45886.png)
 NOW I CONFIG THE PROXY BY COMAND : ./Modlishka-linux-amd64 -proxyDomain mailu0inbox.com

![image](https://user-images.githubusercontent.com/113717414/193684153-3fed32c6-a545-4d8a-a681-c5f8fc8fb1cd.png)
 AFTER THIS SHOULD RUN AND WORK NORMAL BUT... WEHN I TRY ACCES THE DOMAIN DIDN'T WORK AND LOOKS LIKE THIS:
![image](https://user-images.githubusercontent.com/113717414/193684603-ab7e0f9a-9099-41e8-aa85-a23905f2f6ce.png)

IF SOMEONE CAN HELP ME WITH THE INSTALLATION I WILL REMAIN INDEBTED, THANK YOU!

**Comment by George152-max** [comment]
Yo let's chat on whatsapp

**Comment by George152-max** [comment]
@anderzonzizz reply me

**Comment by anderzonzizz** [comment]
Telegram ?

**Comment by George152-max** [comment]
Yeah give me your WhatsApp

**Comment by xkill** [comment]
1. Disable the autocert plugin. Otherwise it will create a new ssl cert signed by untrusted CA.
2. Check the JSON file, seems that it is wrong. (json_pp can help you)
