### ISSUE TITLE
TLS Renegotiation Error

### ISSUE THREAD

**Issue by arch4ngel** [drk1wi/Modlishka#3]
First of all, Modlishka is awesome! Thank you for all your hard work. I'm considering learning GO just to contribute.

Currently, I'm experiencing an issue with TLS renegotiation. The configuration file below is near identical to one that is working for ```accounts.google.com```, which leads me to believe the issue is stemming from a configuration on the target server. After renegotiation fails, a ```502 Bad Gateway``` response is received from the proxy.

I would normally provide a packet capture along with the items below but it would disclose sensitive client information (see screen capture).

Any insight would be greatly appreciated! Thanks again.

## Configuration File

```
{
  "phishingDomain": "evil-aa.local",
  "listeningPort": "443",
  "listeningAddress": "192.168.86.5",
  "target": "https://target-domain.com",
  "useTls":true,
  "targetRes": "target-subdomain",
  "trackingCookie": "malid",
  "trackingParam": "malid",
  "debug": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "requests.log",
  "plugins": "all",
  "cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS",                             
  "certKey": "LS0tLS1CRUdJTiBQUklWQVRFIEt",
  "credParams": "VXNlck5hbWU9KC4rKSY/,UGFzc3dvcmQ9KC4rKSY/"
}
```

## Debug Output

```
[Fri Jan  4 16:46:51 2019]  INF  Enabling plugin: autocert v0.1
[Fri Jan  4 16:46:51 2019]  INF  Enabling plugin: control_panel v0.1
[Fri Jan  4 16:46:51 2019]  INF  Control Panel: Collecting usernames with [UserName=(.+)&?] regex and passwords with [Password=(.+)&?] regex                                
[Fri Jan  4 16:46:51 2019]  INF  Enabling plugin: template v0.1
[Fri Jan  4 16:46:51 2019]  INF  Control Panel: SayHello2Modlishka handler registered
[Fri Jan  4 16:46:51 2019]  INF  Control Panel URL: /SayHello2Modlishka                                                                                                     
[Fri Jan  4 16:46:51 2019]  INF 

>>>> "Modlishka" Piotr Duszynski @drk1wi - Reverse Proxy started <<<<
                                                                                                                                                                            
 _______           __ __ __         __     __
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

Listening on: [192.168.86.5:443]                                                                                                                                            
Proxying [evil-aa.local:443] via --> [https://target-domain.com]                                                                                                                  
[Fri Jan  4 16:47:03 2019]  DBG  Subdomain: target-subdomain
[Fri Jan  4 16:47:03 2019]  DBG  Standard subdomain: target-subdomain
[Fri Jan  4 16:47:03 2019]  DBG  [RP] Checking domain: target-subdomain.target-domain.com
[Fri Jan  4 16:47:03 2019]  DBG  [RP] Checking IP: x.x.x.x
[Fri Jan  4 16:47:03 2019]  DBG  [P] Proxying target [https://target-subdomain.target-domain.com] via phishing [evil-aa.local]                                                                  
[Fri Jan  4 16:47:03 2019]  INF  [P] Tracking victim via initial parameter 6cb89440-b038-4bf2-982e-6a357c2e0252                                                             
[Fri Jan  4 16:47:03 2019]  DBG  PatchHeaders: HTTPRequest took 1.08µs
[Fri Jan  4 16:47:03 2019]  DBG  rewriteRequest took 221.56µs
2019/01/04 11:47:03 http: proxy error: local error: tls: no renegotiation
```

## Screen Capture

_Any redacted address is associated with the target server._

![2pcewqoaqm](https://user-images.githubusercontent.com/11574161/50711072-ea814a00-103a-11e9-800f-87c6213ce5f0.png)

**Comment by arch4ngel** [comment]
I can confirm that the following PR fixed the issue:

https://github.com/drk1wi/Modlishka/pull/4

**Comment by drk1wi** [comment]
Thank you :-) I am happy that the tool is helpful.  You are also very welcome to contribute to the project. There are stil a lot of features that are waiting to be implemented, so an extra pair of skilled coding hands would be great. I personally also started my adventure with Go for the first time with this project - it's actually really easy (something between C and scripted language, without any OOB).

In regard to the PR; that's a really nice find. thanks.

**Comment by CyberTheReape** [comment]
@arch4ngel  how to set certificate settings ? I have a wildcard certificate
ca_bundle.crt
certificate.crt
private_key

i am using debian 8 vps. What should I do to make the website safe ? how to set certificate settings ? please help me ?
