### ISSUE TITLE
!!!  listen tcp 0.0.0.0:443: bind: address already in use . Terminating.

### ISSUE THREAD

**Issue by greenwoodid** [drk1wi/Modlishka#300]
I want to use my domain name but there is a problem. can anyone help me to get Modlishka running?

Screenshot : 
![image](https://user-images.githubusercontent.com/97983996/203636075-7ed8240a-e9e8-46a0-8fdb-b875f7f04d9e.png)

I have searched but the result is still the same. but it is running on my kalilinux but using localhost domain

**Comment by xkill** [comment]
There is another process using the port 443, to check what program is using the port 443:
```
root# netstat -putan | grep :443
```
