### ISSUE TITLE
Bug when loading password section both on Microsoft office and gmail .

### ISSUE THREAD

**Issue by eatahn2001** [drk1wi/Modlishka#306]
**Describe the bug**
Hello , modlishka working for entering the email but when it goes to password section it doesn’t load . Just stays white blank screen.

**Expected behavior**
In order for modlishka to run right I need the password section to work in correlation 

**Configuration (please complete the following information):**
 - Browser being used is safari
 - 
**Additional context
If anyone had the same issue and can help me out be much appreciated

**Comment by eatahn2001** [comment]
![B734F42A-8645-402F-A661-34BABD7AF4F4](https://user-images.githubusercontent.com/124448091/218777288-75d2a1a1-cd83-4f04-b6e5-4c38daf2389a.jpeg)
![12AC8261-1424-4FFC-B02C-E328FE02BC26](https://user-images.githubusercontent.com/124448091/218777300-c45f72c9-a2eb-4f01-92f6-cc3e82f39c1f.jpeg)
![E586C2B0-2704-468F-AA7F-DF929D04A2F5](https://user-images.githubusercontent.com/124448091/218777310-4d1e79d0-6e3a-45fa-aa0b-ea0c5a76b820.jpeg)

**Comment by peterkels** [comment]
i'm having same issue with modlishka, it doesn't make it to the password section.


have you been able to resolve yours?

**Comment by shareblux** [comment]
i need help on the same issue too

**Comment by jahidislam1474** [comment]
same issue in my gmail tamplate
