### ISSUE TITLE
hi i have a problemo to install modlishka on mac os

### ISSUE THREAD

**Issue by johnMiller66** [drk1wi/Modlishka#307]
HI,can i know the procedure to install modlishka on mac os??
how i do to generate a key certificate about mac os for modlishka??
i have to use key acces to generate my certificate pem
My go version it's 1.20
after the procedure  it tell me this
[Thu Feb 23 13:32:03 2023]  INF  Enabling plugin: autocert v0.1
[Thu Feb 23 13:32:03 2023]  INF  Autocert plugin: Auto-generating  domain TLS certificate
[Thu Feb 23 13:32:03 2023]  ERR  Error creating certificate: x509: serial number must be positive
[Thu Feb 23 13:32:03 2023]  INF  Enabling plugin: control_panel v0.1
[Thu Feb 23 13:32:03 2023]  INF  Enabling plugin: hijack v0.1
[Thu Feb 23 13:32:03 2023]  INF  Enabling plugin: template v0.1
[Thu Feb 23 13:32:03 2023]  WAR  Missing required parameters in oder start the proxy. Terminating.
[Thu Feb 23 13:32:03 2023]  WAR  TIP: You will need to specify at least the following parameters to serve the page over HTTP: proxyDomain and target.

**Comment by Rensodark** [comment]
You can reach out to @drk1wi on telegram
