### ISSUE TITLE
Referer rewrite adds extra characters

### ISSUE THREAD

**Issue by kw2583** [drk1wi/Modlishka#31]
I've set up a simple login page to demonstrate the use of this tool. However, when I run it, I am running into issues, because it is rewriting location headers, and adding extra characters. 

`
{
  "phishingDomain": "www.xxxxxxxxxx.live",
  "listeningPort": "443",
  "listeningAddress": "xxx.xxx.xxx.29",
  "target": "https://www.yyyyyyyyyy.live/",
  "targetResources": "",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "",
  "trackingParam": "",
  "useTls": true,
  "jsRules":"",
  "debug": true,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "test.log",
  "plugins": "all",
  "credParams": "dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert" : "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----\n",
  "certkey": "-----BEGIN PRIVATE KEY-----\n-----BEGIN PRIVATE KEY-----",
  "certPool": ""
}
`
And here is the dubug output:

`
 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

Listening on: [xxx.xxx.xxx.29:443] 
Proxying [www.xxxxxxxxxx.live:443] via --> [https://www.yyyyyyyyyy.live/] 
[Tue Jan 22 05:46:44 2019]  DBG  [RP] Checking domain: www.yyyyyyyyyy.live/ 
[Tue Jan 22 05:46:44 2019]  DBG  [P] Proxying target [https://www.yyyyyyyyyy.live/] via phishing [www.xxxxxxxxxx.live]
[Tue Jan 22 05:46:44 2019]  DBG  PatchHeaders: HTTPRequest took 942ns
[Tue Jan 22 05:46:44 2019]  DBG  rewriteRequest took 194.134µs
[Tue Jan 22 05:46:44 2019]  DBG  Rewriting Set-Cookie Flags: from 
[PHPSESSID=li1g1getmc1l2la0masgk9h9t0; path=/]
 --> 
[PHPSESSID=li1g1getmc1l2la0masgk9h9t0; path=/]
[Tue Jan 22 05:46:44 2019]  DBG  Rewriting Location Header [https://www.yyyyyyyyyy.live/login.php] to [https://d8ngmj946qft2m20h6y4mk051ccg.www.xxxxxxxxxx.liveve/login.php]
[Tue Jan 22 05:46:44 2019]  DBG  PatchHeaders: HTTPResponse took 739.663µs
[Tue Jan 22 05:46:44 2019]  DBG  Fallback to default compression ()
[Tue Jan 22 05:46:44 2019]  DBG  [rw] Rewriting Response Body for (https://www.yyyyyyyyyy.live/): status[302] type[text/html; charset=UTF-8] encoding[] uncompressedBody[2121 bytes]
[Tue Jan 22 05:46:44 2019]  DBG  rewriteResponse took 25.570329ms
`

At least part of the problem seems to be in this line:

[Tue Jan 22 05:46:44 2019]  DBG  Rewriting Location Header [https://www.yyyyyyyyyy.live/login.php] to [https://d8ngmj946qft2m20h6y4mk051ccg.www.xxxxxxxxxx.live**ve**/login.php]

**Comment by drk1wi** [comment]
i will look into this.
Does the phishing domain name somehow overlaps with the target domain name ?

**Comment by kw2583** [comment]
There is some overlap in name. Something like mydomain.live and anothermydomain.live

**Comment by drk1wi** [comment]
that's the issue, i will fix it soon (probably it's related to some regexps). in the meantime if you use any other name that doesn't overlap it will work.

**Comment by kw2583** [comment]
Thanks. Tried with loopback on localhost, and got similar results:

`
Listening on: [127.0.0.1:80] 
Proxying [loopback.modlishka.io:80] via --> [https://www.yyyyyyyyyy.live] 
[Tue Jan 22 20:06:48 2019]  DBG  [RP] Checking domain: www.yyyyyyyyyy.live 
[Tue Jan 22 20:06:48 2019]  DBG  [RP] Checking IP: xxx.xxx.xxx.xxx 
[Tue Jan 22 20:06:48 2019]  DBG  [P] Proxying target [https://www.yyyyyyyyyy.live] via phishing [loopback.modlishka.io]
[Tue Jan 22 20:06:48 2019]  DBG  PatchHeaders: HTTPRequest took 1.129µs
[Tue Jan 22 20:06:48 2019]  DBG  rewriteRequest took 141.759µs
[Tue Jan 22 20:06:48 2019]  DBG  Rewriting Set-Cookie Flags: from 
[PHPSESSID=ab8oas1gmqhr564vvs8rbgf26h; path=/]
 --> 
[PHPSESSID=ab8oas1gmqhr564vvs8rbgf26h; path=/]
[Tue Jan 22 20:06:48 2019]  DBG  Rewriting Location Header [https://www.yyyyyyyyyy.live/login.php] to [http://d8ngmj946qft2m20h6y4mk051ccg.loopback.modlishka.iove/login.php]
[Tue Jan 22 20:06:48 2019]  DBG  PatchHeaders: HTTPResponse took 691.553µs
[Tue Jan 22 20:06:48 2019]  DBG  Fallback to default compression ()
[Tue Jan 22 20:06:48 2019]  DBG  [rw] Rewriting Response Body for (https://www.yyyyyyyyyy.live): status[302] type[text/html; charset=UTF-8] encoding[] uncompressedBody[2121 bytes]
[Tue Jan 22 20:06:48 2019]  DBG  rewriteResponse took 23.379423ms
[Tue Jan 22 20:06:48 2019]  DBG  [RP] Checking domain: www.yyyyyyyyyy.live 
[Tue Jan 22 20:06:48 2019]  DBG  [RP] Checking IP: xxx.xxx.xxx.xxx 
[Tue Jan 22 20:06:48 2019]  DBG  [P] Proxying target [https://www.yyyyyyyyyy.live] via phishing [loopback.modlishka.io]
[Tue Jan 22 20:06:48 2019]  DBG  Patching request Cookies [PHPSESSID=ab8oas1gmqhr564vvs8rbgf26h] -> [PHPSESSID=ab8oas1gmqhr564vvs8rbgf26h]
[Tue Jan 22 20:06:48 2019]  DBG  PatchHeaders: HTTPRequest took 40.673µs
[Tue Jan 22 20:06:48 2019]  DBG  rewriteRequest took 72.575µs
[Tue Jan 22 20:06:49 2019]  DBG  Rewriting Location Header [https://www.yyyyyyyyyy.live/login.php] to [http://d8ngmj946qft2m20h6y4mk051ccg.loopback.modlishka.iove/login.php]
[Tue Jan 22 20:06:49 2019]  DBG  PatchHeaders: HTTPResponse took 419.343µs
[Tue Jan 22 20:06:49 2019]  DBG  Fallback to default compression ()
[Tue Jan 22 20:06:49 2019]  DBG  [rw] Rewriting Response Body for (https://www.yyyyyyyyyy.live): status[302] type[text/html; charset=UTF-8] encoding[] uncompressedBody[2121 bytes]
[Tue Jan 22 20:06:49 2019]  DBG  rewriteResponse took 28.038856ms`

**Comment by drk1wi** [comment]
hm, try now. if it's still not working i would need the URL.

**Comment by kw2583** [comment]
I think the regex is good now. not sure why on redirect it's adding appending a string to the front of the URL though. for example, www.xxxxxxxxxx.live becomes d8ngmj946qft2m20h6y4mk051ccza.www.xxxxxxxxxx.live

Interestingly, it is the same string each time, regardless of the browser. I assume that is not related to the regex issue though.
