### ISSUE TITLE
  !!!  x509: malformed certificate . Terminating.

### ISSUE THREAD

**Issue by johnMiller66** [drk1wi/Modlishka#312]
**Describe the bug**

**Expected behavior**

**Configuration (please complete the following information):**
 - Modlishka configuration [e.g. command line flags, JSON config]
 - Browser [e.g. Chrome 72, Safari 12.0.0.1]
 - OS (e.g. Linux (Gentoo 12.1), OpenBSD 6.4, Windows XP).

**Screenshots**

**Additional context**

**Comment by johnMiller66** [comment]
error 509 certificate malformed 
system os arm 64
![IMG_20230314_170146](https://user-images.githubusercontent.com/125281510/225069480-c050cb8b-758d-47aa-938b-4b4449fab372.jpg)
![IMG_20230314_170151](https://user-images.githubusercontent.com/125281510/225069538-57a72eea-0f83-4d37-b727-ecbb8d4f2498.jpg)
browser firefox

**Comment by johnMiller66** [comment]
error 509 certificate malformed
system os arm 64
![IMG_20230314_170146](https://user-images.githubusercontent.com/125281510/225070086-97c39444-bb8b-4ae7-bc45-289ab8a2dd32.jpg)
![IMG_20230314_170151](https://user-images.githubusercontent.com/125281510/225070113-e9003a64-28ad-4719-8098-743920071b6d.jpg)
browser firefox

**Comment by Dilblouch99** [comment]
![Screenshot 2023-05-25 at 2 12 23 AM](https://github.com/drk1wi/Modlishka/assets/126294482/37dbed1e-d849-444a-b019-04caed8e79cc)
Guide me next, what to do now?

**Comment by jimbr0wn876** [comment]
was this resolved?

**Comment by Dilblouch99** [comment]
No sir, it's still there. I'm unable to install and run modlishka

**Comment by SalvayBTC** [comment]
I tried to change the SSL certificate with another one but still got same issue

**Comment by DarkFunct** [comment]
------------autocert.go---------
var n int32
binary.Read(rand.Reader, binary.LittleEndian, &n)

change int32 to uint32
