### ISSUE TITLE
Binding with ngrok.io

### ISSUE THREAD

**Issue by chaitanyakrishna** [drk1wi/Modlishka#32]
Instead of using self signed certificate is there any way to integrate [ngrok ](https://github.com/inconshreveable/ngrok) for Modlishka. Importing self signed certificates in to browsers would be challenging during red teaming operations.

**Comment by drk1wi** [comment]
i haven't checked ngrok before, what's the benefit of using it in comparison to a dedicated vm in the cloud with your own CA signed certificate?

**Comment by drk1wi** [comment]
interesting, I will have a look. 
sounds a bit like ssh -R 443:localhost:443 user@example.com

**Comment by aniketstark** [comment]
Oh shit dont use ngrok
Noob use ngrok 
Legend use ssh
😂😂

**Comment by ad0nis** [comment]
@chaitanyakrishna : Use a Let's Encrypt wildcard cert for a domain you own from a VPS instead of ngrok. Way easier, way more convincing-looking to the end-user, and you're not routing your customer's information through an additional platform you don't control (ngrok).
