### ISSUE TITLE
Idle. Not Working. Everything seems set

### ISSUE THREAD

**Issue by Norgery** [drk1wi/Modlishka#331]
┌──(kali㉿kali)-[~/Modlishka]
└─$ sudo ./dist/proxy -config  Modlishka.json                                                     
[Mon Nov 20 11:46:28 2023]  INF  Enabling plugin: autocert v0.1
[Mon Nov 20 11:46:28 2023]  INF  Enabling plugin: control_panel v0.1
[Mon Nov 20 11:46:28 2023]  INF  Enabling plugin: hijack v0.1
[Mon Nov 20 11:46:28 2023]  INF  Enabling plugin: template v0.1
[Mon Nov 20 11:46:28 2023]  INF  Control Panel: SayHello2Modlishka handler registered
[Mon Nov 20 11:46:28 2023]  INF  Control Panel URL: flip-node.com/SayHello2Modlishka
[Mon Nov 20 11:46:28 2023]  INF  

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [0.0.0.0:443]
Proxying HTTPS [gmail.com] via [https://flip-node.com]
Listening on [0.0.0.0:80]
Proxying HTTP [gmail.com] via [http://flip-node.com]

. it just stays idle forever. i try my host website and nothing changed. cant even access the control panel (404)
.i've been stuck here for days.

**Comment by Norgery** [comment]
i just tried with -debug and its same thing. But i'll check on the certs again.

**Comment by drk1wi** [comment]
check if this works: modlishka   -target google.com -proxyDomain loopback.modlishka.io

**Comment by Norgery** [comment]
(kali㉿kali)-[~/Modlishka]
└─$ ./dist/proxy -target google.com -proxyDomain loopback.modlishka.io
[Mon Nov 20 12:42:39 2023]  INF  Enabling plugin: autocert v0.1
[Mon Nov 20 12:42:39 2023]  INF  Autocert plugin: Auto-generating loopback.modlishka.io domain TLS certificate
[Mon Nov 20 12:42:39 2023]  INF  Enabling plugin: control_panel v0.1
[Mon Nov 20 12:42:39 2023]  INF  Enabling plugin: hijack v0.1
[Mon Nov 20 12:42:39 2023]  INF  Enabling plugin: template v0.1
[Mon Nov 20 12:42:39 2023]  INF  Control Panel: SayHello2Modlishka handler registered
[Mon Nov 20 12:42:39 2023]  INF  Control Panel URL: loopback.modlishka.io/SayHello2Modlishka
[Mon Nov 20 12:42:39 2023]  INF  

 _______           __ __ __         __     __          
|   |   |.-----.--|  |  |__|.-----.|  |--.|  |--.---.-.
|       ||  _  |  _  |  |  ||__ --||     ||    <|  _  |
|__|_|__||_____|_____|__|__||_____||__|__||__|__|___._|

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [127.0.0.1:443]
Proxying HTTPS [google.com] via [https://loopback.modlishka.io]
Listening on [127.0.0.1:80]
Proxying HTTP [google.com] via [http://loopback.modlishka.io]

Same thing.

**Comment by Norgery** [comment]
what am i doing wrong?

**Comment by drk1wi** [comment]
most likely you are not connecting with a browser, you should get at least a cert warning.

**Comment by Norgery** [comment]
![Screenshot 2023-11-20 065216](https://github.com/drk1wi/Modlishka/assets/151410884/640aba3a-082a-4e4b-a448-3b55be3ab3ce)
