### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by scotch123** [drk1wi/Modlishka#336]
Hello,
Is anyone who knows about this error : remote error: tls: bad certificate . the certs are made with certbot
certbot certonly --manual --preferred-challenges=dns --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.mydomain.com --email email@email.com . I've included the certs in the .json config. But after I fill in the username in the microsoftonline template, the page stays blank. Any idea why ? 

Thank you

**Comment by Dgoat201** [comment]
Capture cookies, load in iframe comes with AOL, google and office365 https://t.me/doomztar
