### ISSUE TITLE
improve 'control' plugin impersonation

### ISSUE THREAD

**Issue by samane68** [drk1wi/Modlishka#35]
when enter email and click on next btn 
it's not working!!!
help plz

**Comment by bordeux** [comment]
use tls instead of http protocol

**Comment by drk1wi** [comment]
sorry, but next button for what?

**Comment by bordeux** [comment]
@drk1wi im sure he is talking about next button in login form on google auth :)  It doesnt work, because there are no javascripts. There are not javascripts because trought https it loading http links what are blocked by browser

**Comment by drk1wi** [comment]
@bordeux hm, i just checked with  -target https://google.com -phishingDomain  loopback.modlishka.io -listeningPort 80. and the next button works. maybe it was an issue in the previous releases.

@samane68 use tls, or try to fetch the latest code and compile it.

**Comment by bordeux** [comment]
![image](https://drive.google.com/a/tourradar.com/uc?id=1HXvW1bw8vixY86DLPqXmJJRloaltEgr2)

**Comment by bordeux** [comment]
![image](https://drive.google.com/a/tourradar.com/uc?id=1Gvm5aJedeU-ONYMx9F8654vlnOjAv-tc)

If you want see it on live, write me on priv and i will send you link

**Comment by samane68** [comment]
> @bordeux hm, i just checked with -target https://google.com -phishingDomain loopback.modlishka.io -listeningPort 80. and the next button works. maybe it was an issue in the previous releases.
> 
> @samane68 use tls, or try to fetch the latest code and compile it.

use it 
but when login on redirecting to account stops and not get session on the admin panel

**Comment by samane68** [comment]
![image](https://user-images.githubusercontent.com/46978851/51643291-33b12380-1f81-11e9-86cd-ea36f1a18091.png)

**Comment by samane68** [comment]
![image](https://user-images.githubusercontent.com/46978851/51643774-01082a80-1f83-11e9-9ba9-6435201eec8b.png)
this session is confirmed but not open mailbox and not save information

**Comment by samane68** [comment]
@bordeux 
@drk1wi

**Comment by samane68** [comment]
detected a problem

**Comment by drk1wi** [comment]
what problem?

**Comment by Naeemkhosa** [comment]
> @bordeux hm, i just checked with -target https://google.com -phishingDomain loopback.modlishka.io -listeningPort 80. and the next button works. maybe it was an issue in the previous releases.
> 
> @samane68 use tls, or try to fetch the latest code and compile it.

It is working with loopback but not with paid domain. After first page (signin) not redirecting to password page.

**Comment by OpenSourceGuy77** [comment]
This is a valid problem it has occurred multiple times for me google login doesn't proceed to the passwords page after entering the username.
