### ISSUE TITLE
Cannot make

### ISSUE THREAD

**Issue by Meijeringw** [drk1wi/Modlishka#39]
I followed the stept, but making is not working:
make
go test -v main.go main_test.go
# github.com/drk1wi/Modlishka/core
core/proxy.go:498:10: rp.Proxy.ErrorHandler undefined (type *httputil.ReverseProxy has no field or method ErrorHandler)
FAIL	command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by drk1wi** [comment]
which go version are you using?

**Comment by Meijeringw** [comment]
Go version 1.10.4

I tried to update it and start all over, but when i try to download the source files, i get following error

go get -u github.com/drk1wi/Modlishka/

# github.com/drk1wi/Modlishka/core
go/src/github.com/drk1wi/Modlishka/core/proxy.go:498:10: rp.Proxy.ErrorHandler undefined (type *httputil.ReverseProxy has no field or method ErrorHandler)

Thanks.

**Comment by Meijeringw** [comment]
I have version go 1.11 installed now, same error??

**Comment by drk1wi** [comment]
It should be there for this version:
https://golang.org/pkg/net/http/httputil/
      
      // If nil, the default is to log the provided error and return
        // a 502 Status Bad Gateway response.
        ErrorHandler func(http.ResponseWriter, *http.Request, error) // Go 1.11

**Comment by kondekarshubham123** [comment]
first install go language in your system
using command
- apt install golang
if some error getting then try for update 
- apt-get update
after that try same commond
- apt install golanh

then follow a=same step which told
it will definately work

**Comment by fernandopaulista** [comment]
install Go 1.11.
using the following commands, i had the same issue and this worked for me

sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go

**Comment by drk1wi** [comment]
closing as resolved.

**Comment by tokiijnr** [comment]
@drk1wi 
hey i have :
@kali:~# go version
go version go1.11.6 linux/amd64

but i still get this problem:

root@kali:~/go/src/github.com/drk1wi/Modlishka# make
go test -v main.go main_test.go
# github.com/drk1wi/Modlishka/plugin
plugin/autocert.go:56:22: syntax error: unexpected -- after top level declaration
plugin/autocert.go:58:22: malformed floating-point constant exponent
plugin/autocert.go:63:3: malformed floating-point constant exponent
plugin/autocert.go:73:3: malformed floating-point constant exponent
plugin/autocert.go:82:31: newline in character literal
FAIL	command-line-arguments [build failed]
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by HsounaZinoubi** [comment]
@tokiijnr 
try this:
wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
go get -u github.com/drk1wi/Modlishka
cd $GOPATH/src/github.com/drk1wi/Modlishka/
make
./dist/proxy -h

**Comment by sabu2011** [comment]
@HsounaZinoubi 
hey 
afteter try this still test 1 error https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz

**Comment by atanu2679** [comment]
go test -v main.go main_test.go
main.go:18:2: no required module provides package github.com/drk1wi/Modlishka/config: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:19:2: no required module provides package github.com/drk1wi/Modlishka/core: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:20:2: no required module provides package github.com/drk1wi/Modlishka/log: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:21:2: no required module provides package github.com/drk1wi/Modlishka/plugin: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:22:2: no required module provides package github.com/drk1wi/Modlishka/runtime: go.mod file not found in current directory or any parent directory; see 'go help modules'
make: *** [Makefile:23: test] Error 1
