### ISSUE TITLE
quickstart tutorial error

### ISSUE THREAD

**Issue by Rostiwhite** [drk1wi/Modlishka#40]
I follow step by step tutorial and after start sudo ./dist/proxy  -config templates/google.com_gsuite.json the  local url doesnt start.  Thank you!
![a](https://user-images.githubusercontent.com/46712651/51744825-ae755e00-20a9-11e9-9b1e-b31d3fcf3b6c.png)

**Comment by Decompiler** [comment]
You have to awk the certs and then put them into the config.json file.  Use this command after you generate the certs.

awk '{printf "%s\\n", $0}' MyRootCA.key > MyRootCA2.key
awk '{printf "%s\\n", $0}' MyRootCA.pem > MyRootCA2.pem

**Comment by Rostiwhite** [comment]
That error is after awk...

**Comment by drk1wi** [comment]
Exactly. Also make sure to compile the app.

**Comment by Rostiwhite** [comment]
Two days and still nothing... I follow exactly step by step guide and still nothing.. anyway thank yuo guys. I will wait video guide.

**Comment by drk1wi** [comment]
actually, if you follow the quickstart step by step as it is written, you will manage to run it.
