### ISSUE TITLE
TLS - Template json file unable to be read

### ISSUE THREAD

**Issue by senalifo** [drk1wi/Modlishka#43]
After obtaining a cert and key files from letsencrypt and running awk '{printf "%s\\n", $0}' file on each file. Pasting the contents into the .sjon template files causes the below error when starting the proxy. 

 !!!  Error unmarshalling JSON configuration (templates/facebook.json): invalid character '\n' in string literal . Terminating.

**Comment by drk1wi** [comment]
There's probably a double quote missing.

**Comment by drk1wi** [comment]
closing as resolved.
