### ISSUE TITLE
Failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by 0x00xx** [drk1wi/Modlishka#44]
I tried to follow the tutorial on /Modlishka/wiki/Quickstart-tutorial, but that didn't quite work.

I tried to copy the content of my certificate into the autocert.go file, (with and without \n) but I get the error message stated in the title.

After that I tried to directly put the certificate details into the template.json file, which resulted in the error message "Error unmarshalling JSON configuration (templates/google.com_gsuite.json): invalid character '\n' in string literal . Terminating."

**Comment by drk1wi** [comment]
You just have to c&p the cert and key to the autocert.go and "make".  no need to add any '\n'  chars. no need to add anything to json after this. autocert generates certificates on its own.

**Comment by 0x00xx** [comment]
Hmm sorry, it works with https://loopback.modlishka.io/ but not with "loopback.modlishka.io:443" as stated in the console output.

Sorry and thanks for the help, I guess the issue can be closed

**Comment by filebe777** [comment]
none of this worked forme. i followed the proper installation ...result below
root@kali:~/go/src/github.com/drk1wi/Modlishka# ./dist/proxy -config templates/google.com_gsuite.json
[Tue Mar 12 15:05:28 2019]  INF  Enabling plugin: autocert v0.1
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
	/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:105 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000070300)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000032c60, 0xc000032c70, 0xc000032c80, 0xc000032c90, 0xc000032ca0, 0xc000032cd0, 0xc000032ce0, 0xc000032cb0, 0xc000032cc0, 0xc000032cf0, ...)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
	/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x18f
