### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Beatsbykees** [drk1wi/Modlishka#45]
I followed the quick guide steps, and i still dont get it working.

When i go the domain i redicted to ip to, it straight redicts me to the target website.

**Comment by okofishe** [comment]
show us a screen shot

**Comment by Beatsbykees** [comment]
Now i got the first problem working, but now everytime i go to my website wont load.
In my console i get : 

Listening on: [195.X.X.X:80]
Proxying [XX.tk:80] via --> [https://google.com]
2019/02/06 11:11:37 http: TLS handshake error from 77.XX.XX.XX:XXXXX: tls: fi                                                                                        rst record does not look like a TLS handshake

**Comment by drk1wi** [comment]
This error message can be ignored. it doesn't affect the traffic flow.
