### ISSUE TITLE
Browser certificate warnings

### ISSUE THREAD

**Issue by skandaI** [drk1wi/Modlishka#46]
![ttt](https://user-images.githubusercontent.com/4047379/51804304-6730ce00-225f-11e9-852c-83e8b238f224.png)

Can anything be done about it?

**Comment by drk1wi** [comment]
https://github.com/drk1wi/Modlishka/wiki

**Comment by skandaI** [comment]
I read it. Can you tell me which part of the wiki can be the solution to my problem? My domain has a valid certificate. The problem is that it conflicts with the name of other sites, for example Google.

**Comment by drk1wi** [comment]
Did you create a wildcard certificate for your phishing domain?

**Comment by drk1wi** [comment]
that's not a wildcard cert. check out the acme.sh documentation.

**Comment by thecityofhereafter** [comment]
acme.sh --issue --force -d *.verify.computer -d *.com.verify.computer -d *.google.com.verify.computer -d *.accounts.google.com.verify.computer --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please

CREATE THE TXT RECORDS IT SAYS, DONT INCLUDE THE ''

acme.sh --renew --force -d *.verify.computer -d *.com.verify.computer -d *.google.com.verify.computer -d *.accounts.google.com.verify.computer --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please

USE THE AWK COMMAND IN THE WIKI TO CONVERT THEM TO BASE64

PASTE THEM INTO YOUR JSON FILE.

MAKE SURE TO USE CA.cer for certPool field and NOT yourdomain.CSR file.

(this is how I managed to get everything working for myself).

GL

**Comment by drk1wi** [comment]
assuming as resolved due to lack of response to @thecityofhereafter feedback.
