### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by 50UM3N** [drk1wi/Modlishka#48]
when I try tho install this i get some error like this.. 
# github.com/drk1wi/Modlishka/core
/root/go/src/github.com/drk1wi/Modlishka/core/proxy.go:498:10: rp.Proxy.ErrorHandler undefined (type *httputil.ReverseProxy has no field or method ErrorHandler)

**Comment by Bharat1950** [comment]
I want get this tools .what is processing please show me.

**Comment by drk1wi** [comment]
it's a duplicate issue: https://github.com/drk1wi/Modlishka/issues/39
