### ISSUE TITLE
page cannot be displayed ?

### ISSUE THREAD

**Issue by CyberTheReape** [drk1wi/Modlishka#5]
hello. I started the program with the domain name , but cannot be displayed.. page opens with local domain name..it does not work with the domain I received from freenom ?

**Comment by CyberTheReape** [comment]
I noticed something new right now . I want to listen to port 80 when I start the program. but port 80 looks closed ?? I'm using vps server and port 80 appears open when I start apache server,.I close apache server and start Modlishka with port 80, Port number 80 looks off ?

**Comment by drk1wi** [comment]
there can be several issues here:
- domain isn't pointing to your host, where you run the proxy 
- fw is not properly set up
- you are listening on 127.0.0.1. 

Please also check the wiki page. If something needs clarifying I will be happy to update.

**Comment by CyberTheReape** [comment]
this is my command :    
sudo ./dist/proxy   -target https://accounts.google.com -phishingDomain pentesting.tk -listeningrt 80

freenom cname : 
accounts.pentesting.tk
myaccount.pentesting.tk
ssl.pentesting.tk
www.pentesting.tk

i have willcard certificate. i have saved the certificate information into autocert.go ..
I placed my certificates in the secure certificate area ...

I am using debian 8 vps.. 
go version -- go1.10
ufw security not active

**Comment by drk1wi** [comment]
there's a typo in "-listeningrt 80" 
also you should set up a wildcard CNAME for *.pentesting.tk or *.demo.pentesting.tk to point to your IP. 
also set target to just google.com . you will be able to switch between subdomains.

**Comment by CyberTheReape** [comment]
(-listeningrt 80  ) I wrote wrong here .. 
I wrote correctly in the terminal
sudo ./dist/proxy -target https://accounts.google.com -phishingDomain pentesting.tk -listeningPort 80

i have willcard ... The certificate I received with cname records has nothing to do with.. i am sure that only the cname and A records are made correctly..wildcard certificate also received correctly.there is no wrong here.

![5](https://user-images.githubusercontent.com/42475284/50740401-d423eb80-11fe-11e9-9979-c534cda62986.png)


![6](https://user-images.githubusercontent.com/42475284/50740403-ddad5380-11fe-11e9-9d7e-5071697296d5.png)


if you give me mail address , i can send you , my vps password and you can look it

**Comment by CyberTheReape** [comment]
this is my mail address : tumerayaz31@gmail.com

Send me mail. İ will send my vps password you

**Comment by drk1wi** [comment]
you are listening on 127.0.0.1. change this to 0.0.0.0.

**Comment by CyberTheReape** [comment]
yes .. it is worked now

![deneme1](https://user-images.githubusercontent.com/42475284/50763345-9bc4f180-1280-11e9-9fbe-d2a77255a932.png)

![deneme2](https://user-images.githubusercontent.com/42475284/50763464-e2b2e700-1280-11e9-9c30-38885dae45d8.png)


why my certificate looks like this ? this is my autocert.go configure

![deneme3](https://user-images.githubusercontent.com/42475284/50763564-30c7ea80-1281-11e9-8195-a7536ab14b13.png)

this is true ?

**Comment by CyberTheReape** [comment]
Will autocert.go configuration look like in the picture? 
i did take wildcart certificate like the this >>   https://www.youtube.com/watch?v=ioQ_L2fjRcs   [0:00 - 3:49]
can you write some more information in wiki page to configure the certificate

**Comment by drk1wi** [comment]
I don't see any wildcard record in your domain configuration. You will have to set it up.
This might be causing the trouble. 
In regard to the certificate, can you c&p information about the certificate from your browser?

**Comment by CyberTheReape** [comment]
really ? this records not enough? >> _ACME-CHALLENGE
                                                          _ACME-CHALLENGE

ah my head started to ache..because we do not know English, we also have difficulty understanding.
I've looked at the articles on wiki with google translate.. If you've typed one letter incorrectly, the meaning of the article is changing. I think I need to watch someone's installation video

**Comment by drk1wi** [comment]
Hi,
This record is only for the letsencrypt certificate generation via acme.sh.
You will need
- a '*' CNAME and an A record that points to your IP address
- generate a certificate via acme.sh and place the generated key and certificate in the JSON configuration file. ( use this to convert to the right JSON format: awk '{printf "%s\\n", $0}' file).

This should get you going

**Comment by drk1wi** [comment]
happy that i could help :-)

**Comment by CyberTheReape** [comment]
@drk1wi Thank you for your help. site is working without problems . some questions were stuck in my mind. all login information is registered in google.log. but nothing appears on the user panel .

my credParams =       username=\],"([^"]*)"\]$       (base64)   dXNlcm5hbWU9XF0sIihbXiJdKikiXF0k
                                   password=,\["([^"]*)",           (base64)   cGFzc3dvcmQ9LFxbIihbXiJdKikiLA==

"credParams": "dXNlcm5hbWU9XF0sIihbXiJdKikiXF0k,cGFzc3dvcmQ9LFxbIihbXiJdKikiLA==",

i am using these values ​​for evilginx google phishlet. Do you think this could be the reason why their passwords didn't appear on the control panel?

If I use the values ​​we write on the wiki page, do the passwords appear on the control panel?

These are the information on your page
"password=([^\W]+)&" 
"username=([^\W]+)"

**Comment by zenaze** [comment]
Please can you share with me your google phishlet. .yaml?

**Comment by hadiabounader** [comment]
@cyberthereape can you give me your email address? I want to ask you something

**Comment by prabachandar1989** [comment]
hi Phoenix1112

can you please help me out to config the Freenom domain with Modliksha. This host is running in my Kali Machine (Not VPS).. 

I ahve already configured the Modlishka locally and it was working fine in locally, But i need to test it outside of the localhost.

SO please help me out on this. Thanks in advance..

**Comment by Phoenix1112** [comment]
@prabachandar1989

You need vps server for wildcard dns configuration. Freenom not support wildcard dns configuration... 

You need change domain company or you need take vps server.

Amazon and google giving free vps server. (1 year)

İf you use vps server , you can do wildcard dns configuration

**Comment by prabachandar1989** [comment]
> yes .. it is worked now
> 
> ![deneme1](https://user-images.githubusercontent.com/42475284/50763345-9bc4f180-1280-11e9-9fbe-d2a77255a932.png)
> 
> ![deneme2](https://user-images.githubusercontent.com/42475284/50763464-e2b2e700-1280-11e9-9c30-38885dae45d8.png)
> 
> why my certificate looks like this ? this is my autocert.go configure
> 
> ![deneme3](https://user-images.githubusercontent.com/42475284/50763564-30c7ea80-1281-11e9-8195-a7536ab14b13.png)
> 
> this is true ? why my certificate not trust ?
> 
> ![deneme4](https://user-images.githubusercontent.com/42475284/50763880-22c69980-1282-11e9-8f99-61c8c8463f8c.png)

Thanks for your response, But i could see that you have used freenom for your domain. So you have also used VPS for hosting Modlishka. 

It can appreciated if you provide step by step instructions for configuring it.

**Comment by prabachandar1989** [comment]
> @prabachandar1989
> 
> You need vps server for wildcard dns configuration. Freenom not support wildcard dns configuration...
> 
> You need change domain company or you need take vps server.
> 
> Amazon and google giving free vps server. (1 year)
> 
> İf you use vps server , you can do wildcard dns configuration

Thanks for your response, But i could see that you have used freenom for your domain. So you have also used VPS for hosting Modlishka.

It can appreciated if you provide step by step instructions for configuring it.

**Comment by Phoenix1112** [comment]
No. İ did buy vps server. İf you buy vps server , you can use freenom. You will redirect your freenom dns settings to the site where you purchased the vps server.. 
modlishka dns settings will be done with the site where you get the vps server.

freenom does not allow me to add this dns record.

*.        Cname        yourdomain.com


so you need to do the dns settings with the vps server. 

If you don't want to get vps server, you should get another domain.

You can add wildcard dns record with namecheap or godaddy.

You will either buy a VPS server, or purchase a paid domain.

The decision is yours

**Comment by prabachandar1989** [comment]
I got it,


which is the better option as per your view?

do you have any detailed instructions to configure the DNS for modlishka

or if you have detailed instruction with VPS and config DNS with Freenom.

so that i will purchase either VPS or domain

**Comment by Phoenix1112** [comment]
Only you need to buy vps.. you can buy vps in digitalocean.   İ did use modlishka with digitaloceand vs & freenom

**Comment by jmdersonm** [comment]
pls fam im having issues with freenom domain with 
evilginx  site unable to connect
pls i need how to get it working

**Comment by jmdersonm** [comment]
im using vps from digitalocean

**Comment by scclive** [comment]
> 
> 
> @drk1wi Thank you for your help. site is working without problems . some questions were stuck in my mind. all login information is registered in google.log. but nothing appears on the user panel .
> 
> my credParams =
> username=],"([^"]_)"]$ (base64) dXNlcm5hbWU9XF0sIihbXiJdKikiXF0k password=,["([^"]_)", (base64) cGFzc3dvcmQ9LFxbIihbXiJdKikiLA==
> 
> "credParams": "dXNlcm5hbWU9XF0sIihbXiJdKikiXF0k,cGFzc3dvcmQ9LFxbIihbXiJdKikiLA==",
> 
> i am using these values ​​for evilginx google phishlet. Do you think this could be the reason why their passwords didn't appear on the control panel?
> 
> If I use the values ​​we write on the wiki page, do the passwords appear on the control panel?
> 
> These are the information on your page
> "password=([^\W]+)&"
> "username=([^\W]+)"
> ## i am edit this article
> 
> i did use this method now
> "password=([^\W]+)&"
> "username=([^\W]+)"
> 
> shows only passwords
> 
> ![de](https://user-images.githubusercontent.com/42475284/51036149-46a91880-15bd-11e9-8bcc-767bed58a90f.png)
> 
> can you write me a nice regex value? I do not understand from regex.what is the regex value you use in your video ?

I am all new to this especially Evilginx2. May I have any phishlets (.yaml) of any site like google! I have tried every one available but without any luck.
