### ISSUE TITLE
Can not capture Username

### ISSUE THREAD

**Issue by th1k404** [drk1wi/Modlishka#50]
First of all the project is perfectly installed in my kali linux 2018.4 VMware . No change any string or syntax in the project accepted ssl part (i tested on local).

Okay here is the details what i did and what i get.

For capture the UUID i used Version 4 UUID Generator from this site "www.uuidgenerator.net" and put the syntax as below:

> https://loopback.modlishka.io:443/?ident=fe502484-1778-4434-a17f-xxxxxx

When i hit enter the url to request, it browse to the google interface as normal and get the uuid from the terminal:

> [P] Tracking victim via initial parameter fe502484-1778-4434-a17f-xxxxxx

When i login with the password it logged in perfectly and get something like this on terminal:

> Password collected ID:[fe502484-1778-4434-a17f-xxxxxx] password: !oxxxxxxxxxxx

Okay now here the part of issue, when i go to the panel page "/SayHello2Modlishka" i see only the "UUID, Password and Session" and show the user credential but only on Username that did't show any string.

And when i try to use the session function "Impersonate user (beta)" to login, it progress to the loading page and redirect to the main page without any account log in.

Thanks,

**Comment by drk1wi** [comment]
Hi, Thanks for you feedback. 
Regex for the username collection works currently on a particular login flow (only when the user logs in for the first time, with clear cookie state). You would have to update the regular expression to support other requests that set the username. 
In regard to the impersonation feature, yes. there are some cases that do not work, this is also why it's in 'beta' state. I will probably move on that part after improving some of the 'core' functionalities.

**Comment by th1k404** [comment]
Okay sir, noted with thanks.

**Comment by drk1wi** [comment]
closing as resolved.

**Comment by johnnash999** [comment]
@th1k404, sir do you got any solution for capturing username.. 

do you mind sharing with us please :)

**Comment by GregorioSecurity** [comment]
@johnnash999 @th1k404 and @drk1wi 
I have found a solution,in this case, even if the cookies are clear and everything is running properly, the username is not collected if it contains a period. Still working on a solution.
