### ISSUE TITLE
Url can not be open although Modlishka is successfully run

### ISSUE THREAD

**Issue by darkcoder992** [drk1wi/Modlishka#51]
![mod error](https://user-images.githubusercontent.com/46774722/52007467-5fea0a00-2483-11e9-95ef-868bdd53bd17.JPG)

recently I can start modlishka but unfortunatly this error come and this tool can not run, please anyone help me to sort out this issue

kindly help me to open this.

thanks in Advance

**Comment by th1k404** [comment]
For my experienced with this issues, i just re-config the certificate file and run make.

note: make sure when u put the ./dist/proxy -config....... u do not copy and past through terminal....please type it manually. :)

**Comment by darkcoder992** [comment]
> For my experienced with this issues, i just re-config the certificate file and run make.
> 
> note: make sure when u put the ./dist/proxy -config....... u do not copy and past through terminal....please type it manually. :)

fist of all really thank you for your answer  :)

sir I can create certificate file but can not configure it because I can use codeanyhere.com website to run kali. And on this site I can not open any file for editing...can you pls tell me how I can open that kind file on codeanywhere.com :)

**Comment by th1k404** [comment]
Make sure you run this url as https:// (https://loopback.modlishka.io:443/)

**Comment by darkcoder992** [comment]
> Make sure you run this url as https:// (https://loopback.modlishka.io:443/)

sir I can use this url but got error 'the site can not be reached' (I am using online some websites to run Modlishka on kali ubunto)

**Comment by th1k404** [comment]
i think it about the domain name proxy setting or CNAME bla bla bla....you should check your setting and reconfig with this guide [https://github.com/drk1wi/Modlishka/wiki/How-to-use].

for me i use local network to test...so it working fine accepted the issue that i complained on this [https://github.com/drk1wi/Modlishka/issues/50]

**Comment by drk1wi** [comment]
assuming as resolved due to lack of response to @th1k404  feedback.
