### ISSUE TITLE
targetRules parameter not documented

### ISSUE THREAD

**Issue by donpool** [drk1wi/Modlishka#52]
Hi Piotr,

Wonderful tool! but can't find **targetRules** meaning/use on any of the documentation. Could you explain and/or add the correspondig section to https://github.com/drk1wi/Modlishka/wiki/How-to-use

Thanks!

**Comment by drk1wi** [comment]
Hi, Thank you for pointing this out. This is in fact the same parameter as rules for the cmd line. I will change 'rules' to 'targetRules' and update the WIKI in the upcoming update.

**Comment by drk1wi** [comment]
resolved
