### ISSUE TITLE
Redirecting modlishka to path

### ISSUE THREAD

**Issue by 0x00xx** [drk1wi/Modlishka#53]
I am currently playing around with Modlishka, and managed to run it properly. Now I am trying to create a new template.
I try to create a proxy for: 
`https://ab.cd.com/p1/p2/?a1=XXXX&a2=XXXX&a3=XXXX`
Is this possible? Because when I set this as my target, it does not load. But when I set the target to https://ab.cd.com/ it loads, but the mainpage, which I do not want.

Is there a way to load a target path from a subdomain including some parameters (a1-a3)?

EDIT: Okey managed it to make it work. Had a thinking error..I needed to set the target to https://cd.com/ and in targetResource add the subdomain.

Put I've got another problem now: Modlishka does not report a login attempt (eventhough I set the trackingParam to the username and password). Or does Modlishka only report valid login attempts?

The post request of the login is saved correctly in the log file

**Comment by drk1wi** [comment]
In regard to the trackingParam, please check the WIKI. It's used to set the UUID for tracking the user.  Do you mean that you would like display the login/pass in the control panel web page?

**Comment by 0x00xx** [comment]
Ooh, I see. Well when I first executed Modlishka with the Google template, it showed the login parameters on the console output (where I started Modlishka).
But not with my testing page. In order to find the typed in login details, I need to manually open the logfile and check the POST request there
