### ISSUE TITLE
Error with next button when using TLS 

### ISSUE THREAD

**Issue by fernandopaulista** [drk1wi/Modlishka#55]
The tool is working perfectly without the TLS and everything is captured however when using tls and adding the certificate parameters, google page loads fine and the login page also, however when i add the mail and click next nothing happens, looks like the next button is not working

**Comment by drk1wi** [comment]
Hi, Are you using the config files from the templates directory?

**Comment by fernandopaulista** [comment]
yes, using google-config.json

**Comment by drk1wi** [comment]
Hm, which browser are you using. I just checked on chrome a sec. ago and everything is fine.

**Comment by fernandopaulista** [comment]
firefox on ubuntu

**Comment by fernandopaulista** [comment]
i just tested on chrome and encountered the same issue

**Comment by drk1wi** [comment]
I am not sure what's the issue, it works on chrome. 
Do you have any errors in the console?

**Comment by drk1wi** [comment]
did you issue $make command and added c&p the previously generate CA cert?

**Comment by fernandopaulista** [comment]
yes i copied the certificate and key parameters in the json and the autocert.go 
i added them as trusted CA in my browsers but it keeps giving me not secure alert when i load the page 
i proceed to google login page but the next button does nothing

**Comment by drk1wi** [comment]
please follow the tutorial. there's nothing about copying the certificate to the json file.

**Comment by fernandopaulista** [comment]
i have tried this before to keep the certificate parameters empty in the json but it doesn't work
i get the following error:
panic: tls: failed to find any PEM data in certificate input

**Comment by fernandopaulista** [comment]
okay i reinstalled on a fresh new vm and now it works fine looks like it was an inetrnal error 
thanks for your support :)

**Comment by drk1wi** [comment]
ok, cool :-)
