### ISSUE TITLE
Modlishka error

### ISSUE THREAD

**Issue by samraddha** [drk1wi/Modlishka#57]
You just have to c&p the cert and key to the autocert.go and "make". no need to add any '\n' chars. no need to add anything to json after this. autocert generates certificates on its own.
I have applied this method but it is showing this error
when i execute this command ./dist/proxy -config templates/google.com_gsuite.json
i get following error
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149
please tell me how to solve this error and start modlishka
Please read full comment and then tag it duplicate or close it

**Comment by drk1wi** [comment]
Hi, Please follow the https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial step by step. It will get you started.

**Comment by samraddha** [comment]
I have followed all steps properly but when i execute this command ./dist/proxy -config templates/google.com_gsuite.json
i get following error
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:103 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000062300)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000054c50, 0xc000054c60, 0xc000054c70, 0xc000054c80, 0xc000054c90, 0xc000054cc0, 0xc000054cd0, 0xc000054ca0, 0xc000054cb0, 0xc000054ce0, ...)
/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x149
please tell me how to solve this error and start modlishka

**Comment by drk1wi** [comment]
did you run $ make command ?

**Comment by samraddha** [comment]
I had run $make command but it it showing same error
You are developer so sir please tell me how to solve this because it is very good program and I want to run it

**Comment by drk1wi** [comment]
if you follow the https://github.com/drk1wi/Modlishka/wiki/Quickstart-tutorial  it will work. Works for everyone ;-)

**Comment by sabu2011** [comment]
remote error: tls: unknown certificate authority

how i can solve this error not capturing anything not working  always showing  (remote error: tls: unknown certificate authority
)

**Comment by nizamuddin541** [comment]
!!!  Error opening JSON configuration (templates/google.com): open templates/google.com: no such file or directory . Terminating.

Hi 
am getting this msg once i run this cmd "./dist/proxy -config templates/google.com"

please help
