### ISSUE TITLE
The page is not working in browser

### ISSUE THREAD

**Issue by aniketstark** [drk1wi/Modlishka#59]
![screenshot_2019-02-06-14-52-16-100_com termux](https://user-images.githubusercontent.com/31062805/52331790-12d7dc00-2a1f-11e9-89eb-907225421866.png)
Perminssion denied error

**Comment by kondekarshubham123** [comment]
try
-to import certificates in browser under setting -> Certificates -> Import Certificates ->(Select the path of generated Certificate)

**Comment by aniketstark** [comment]
Ha no i think you dont see image the listening tcp 127.0.0.1:443 is not binding permission denied

**Comment by 0x00xx** [comment]
you need to write sudo ./dist...

**Comment by aniketstark** [comment]
I dont have sudo
I am normal linux user

**Comment by drk1wi** [comment]
This will not work without root privileges.

**Comment by drk1wi** [comment]
Closing as resolved.
