### ISSUE TITLE
Issue with certificate

### ISSUE THREAD

**Issue by Sara123984** [drk1wi/Modlishka#6]
Hi,

Thank you for a beautiful project, managed to get it up and running without the https.
I am trying to install the certificate i got from acme.sh script and i can't understand what to put in the json file, could you please explain ( i am new at all the CA sigining).
FYI i did transform the key into pem format but dont understand what goes where.

Also can we issue a certificate from lets encrypt with all the subdomains needed in order to not need a wildcard certificate ?

**Comment by CyberTheReape** [comment]
same problem...
i have 3 certificate

ca_bundle.crt
certificate.crt
private.key

i did edit autocert.go... but i dont know..

**Comment by drk1wi** [comment]
I think that the autocert plugin, which is enabled doesn’t have the right CA cert. 
Please check the wiki, how to generate one and put it in the autocert plugin. 

You will also have to trust the self-signed CA certificate locally, so the browser will trust it.
