### ISSUE TITLE
Browser doesnt load the URL

### ISSUE THREAD

**Issue by randomgenerateduser** [drk1wi/Modlishka#62]
Hey there 
I have set up everything successfully (Certificates etc.); and the Modlishka runs normally but when I try to load the URL in the browser it just spits out an error. (Unable to connect) 

![err](https://user-images.githubusercontent.com/47398024/52366578-c0b0ae00-2a52-11e9-99b4-092338ca3f80.jpg)

I'd really appreciate a little helps its really bugging me out 👍

**Comment by drk1wi** [comment]
Hi, please remember that you are listening on a loopback addr. 127.0.0.1.

**Comment by randomgenerateduser** [comment]
> 
> 
> Hi, please remember that you are listening on a loopback addr. 127.0.0.1.

Hello **drk1wi**;

There is actually another error when I try to load the 127.0.0.1:443 (or loopback.modlishka.io:443) in the browser : �
![errr](https://user-images.githubusercontent.com/47398024/52467465-4f761580-2b8e-11e9-88a2-c5ff5a60d2cb.jpg)

And this is the response from Modlishka:
_2019/02/08 03:40:39 http: TLS handshake error from 127.0.0.1:40142: tls: first record does not look like a TLS handshake_

+Thank you for the reply, appreciate it)

**Comment by jelledesnelle** [comment]
Do you have a WiFi adapter in kali Linux ? For testing at localhost?

**Comment by curiousm3** [comment]
try adding using https instead of http ie:
https://loopback.modlishka.io
assuming you've added the record to your hosts file

**Comment by jelledesnelle** [comment]
> 
> 
> try adding using https instead of http ie:
> https://loopback.modlishka.io
> assuming you've added the record to your hosts file

I got also the same problem, but i din not add a record yet?
You mean the hosts file in etc map? and add this record: https://loopback.modlishka.io on ip 127.0.0.1.?

**Comment by Ayushraj1** [comment]
where is host file, and wheere is etc map.

**Comment by jelledesnelle** [comment]
> 
> 
> where is host file, and wheere is etc map.

I asked curiousm3 where to add the record.

**Comment by mathieu-aubin** [comment]
hostfile is /etc/hosts

    127.0.0.1 loopback.modlishka.io

is the format you need to stick to in order to map the localhost ip (lo) to whatever domain name.

it should resolve in your browser after and also via most command line appsjy

**Comment by mathieu-aubin** [comment]
> > Hi, please remember that you are listening on a loopback addr. 127.0.0.1.
> 
> Hello **drk1wi**;
> 
> There is actually another error when I try to load the 127.0.0.1:443 (or loopback.modlishka.io:443) in the browser : ������
> ![errr](https://user-images.githubusercontent.com/47398024/52467465-4f761580-2b8e-11e9-88a2-c5ff5a60d2cb.jpg)
> 
> And this is the response from Modlishka:
> _2019/02/08 03:40:39 http: TLS handshake error from 127.0.0.1:40142: tls: first record does not look like a TLS handshake_
> 
> +Thank you for the reply, appreciate it)

this would be the ssl handshake behind gebrishly shown to you  - mapping the lo address to the domain and using https instead of http with port will give the result you need

**Comment by drk1wi** [comment]
did you manage to run everything properly?

**Comment by mathieu-aubin** [comment]
i vote to close this issue

**Comment by drk1wi** [comment]
I agree.
