### ISSUE TITLE
Impersonate feature: 2FA bypass not working

### ISSUE THREAD

**Issue by DeKoning93** [drk1wi/Modlishka#63]
Hi guys,

First of all, thank you for building this great tool. It will certainly help making the world more aware of the need for strong authentication methods such as YubiKeys or other FIDO-capable hardware authenticators.

I have tested Modlishka on both Google/Gsuite accounts and the webmail (Outlook Web Access) from our company. It seems to me that the "impersonate" button only works for accounts which are protected with a username and password (no 2FA), or accounts which used 2FA in the first place but are whitelisted after the first log-in.

For example: if you authenticate through the proxy with a Google account with 2FA enabled, the impersonate function only works if the user has selected "do not ask 2FA again for this device" during the Google login. If this is the case, you can just take over the account. But if the user has unticked the "trust device" option, you will just land on the Google homepage without being logged in when you click the impersonate button.

Another example: we are running Outlook Web Access on our own IIS servers and have some commercial 2FA software (such as DUO / Securenvoy / RSA / Gemalto / Onespan / SMS Passcode) for SMS authentication installed using an ISAPI filter on the webserver. The authentication works via the proxy, but when clicking the impersonate button the hacker/pentester lands on the 2FA challenge page. Only when the specific user or network IP is whitelisted, the hacker/pentester is logged in using the impersonate function.

I'm not sure why bypassing the 2FA does not work, I would assume that after succesful log-in with 2FA the users gets a session cookie, and using SayHello2Modlishka I should be able to import this / these cookie(s).

Could you guys check out how/why this does not work and advise if there are any workarounds?

Thanks,
Davey

**Comment by Beatsbykees** [comment]
Is there a way i can get in contact with you?
Send me your discord/whatsapp

**Comment by drk1wi** [comment]
Hi, thank you for you feedback. I am happy that the tool is doing what it was meant to :-) 
The impersonate function is still in beta, there's a lot to be improved in there and that's also why you are having these issues. Regardless of this you can find all of the http requests in the log file, including cookies.
ps. you can contact me on twitter.

**Comment by LazyLinks** [comment]
Can someone help me set up Modlishka? I tried it a few times now, but i dont know where I can put the website i tryna remake in the tool..

**Comment by LazyLinks** [comment]
If someone can leave there discord, we talk on it.

**Comment by Beatsbykees** [comment]
@LazyLinks add me: John Eight#0072

**Comment by LazyLinks** [comment]
@Dekoning93 add my discord: LazyLinks101 #4581

**Comment by DeKoning93** [comment]
Hi guys,

It's not that I don't want to contribute to the community, but to be honest I find it a bit strange that I have some serious questions about the tool and then people try to contact me if I can help them install Modlishka. It is not hard if you want to install it for testing purposes:

- Run Kali Linux on a virtual machine (e.g. VirtualBox)
- Install Golang on your machine
- Follow the Modlishka "how to install" guide, import the certificate in your browser and it works.

This video will help you as well: https://www.youtube.com/watch?v=ZQPvcKzW46g

Cheers,
Davey
