### ISSUE TITLE
Modlishka All Errors and Issues

### ISSUE THREAD

**Issue by Ayushraj1** [drk1wi/Modlishka#66]
1.Phishing domain-Https://loopback.modlishka.io:443 doesnot open the website google.com, says SSL_Connection_error and Invalid Response.

2. Phishing domain- loopback.modlishka.io:80 works ,but doesnot capture data , and Gmail sign-in Next button doesnot work,

Redirects to original Google.com website.

3. Shows not secure connection, already installed SSL certificate in browser.

**Comment by kennyyy53** [comment]
Did u resolve your second problem? because  i have the same

**Comment by drk1wi** [comment]
Hi, Did you follow the tutorial on wiki?

**Comment by kennyyy53** [comment]
yes obviously

**Comment by drk1wi** [comment]
i rechecked the config and everything works. this looks like a fw or ssl certificate issue.

**Comment by kennyyy53** [comment]
yes i think to because i don't arrive to put *.domain.com for cname. I the error is coming from this no ?

**Comment by drk1wi** [comment]
you need a wildcard certificate as described on the wiki ;-) please follow all of the steps and you'll get it running

**Comment by kennyyy53** [comment]
I don't understand guys because the site is running and appears like a secure site (with HTTPS ) because i get the cert wityh lets encrypt( like say in wiki) but when i try to log in the next button don't work

**Comment by drk1wi** [comment]
how can you get a certificate for loopback.modlishka.io if you don't own it? that's why the autocert plugin was created, so you can test it locally. CA signed certificates can be only used on domains that you own.

**Comment by kennyyy53** [comment]
No i was saying that i get cert on my domains because  i tried before to run it locally on an other PC whith kali linux and everything worked, I could log in etc... but when i tried to configure the tools for my domains i couldn't log in

**Comment by drk1wi** [comment]
ok, it's most probably a wildcard domain SSL cert issue

**Comment by kennyyy53** [comment]
and what have I to check to know where is the error in the configuration please ?

**Comment by drk1wi** [comment]
both console log in the browser and debug view in Modlishka. this should give you more feedback on what is wrong.

**Comment by kennyyy53** [comment]
debug view in the screen which is showing when the tool is launch right ? because it is don't showing me anything

**Comment by drk1wi** [comment]
you have to enable it in the config, in browser - debug tools.

**Comment by kennyyy53** [comment]
This error is happening. How can I resolve it pls ?
![error Modlishka](https://user-images.githubusercontent.com/48528907/55741518-ba788700-5a2d-11e9-8998-927269f47886.png)

**Comment by Ayushraj1** [comment]
Hello sir, why don't you try yourself in Windows and rewrite the wiki to counter this problem

**Comment by kennyyy53** [comment]
Because the wiki is good and my problem here came of the fact that I cannot  get the wildcard *.domain.com

**Comment by drk1wi** [comment]
this should be resolved in v.1.1
