### ISSUE TITLE
Modlishka working issue

### ISSUE THREAD

**Issue by Ayushraj1** [drk1wi/Modlishka#67]
It's work only on same computer or same network.

I tried to run the url loopback.modlishka.io:80 or https://loopback.modlishka.io:443 ,
On my mobile phone , both pc and phone connected to internet,
Says Connection Refused.

I need help ,. Well I am just 16yrs old only from India.
I am using windows pc.

**Comment by jelledesnelle** [comment]
You have WiFi in Linux to use your local host? Without WiFi in Linux is not possible to use local host i think

**Comment by Ayushraj1** [comment]
no, you can use WAMP or XAMPP server to create localhost in your computer. i am using localhost, please view my other issues also

**Comment by jelledesnelle** [comment]
I got the same issue.. cant open the link also..
