### ISSUE TITLE
How to setup Modlishka to pass real ip of users to server?

### ISSUE THREAD

**Issue by antouraj** [drk1wi/Modlishka#69]
Dear Piotr,
Thanks again for your revolutionary soft!
Just would like to know, how to setup Modlishka to transfer their real ip to end server!
By default it's pass server (Modlishka) ip!
Thanks again! 
Would be glad for any respond!
Good luck!

**Comment by LazyLinks** [comment]
I have the same issue, can you please contact me if u have the solution

**Comment by antouraj** [comment]
Any idea?

**Comment by fipso** [comment]
This is not possible. U cant just spoof the IP. The target Page will always get the Server IP, because thats the one who actually does the login.

**Comment by antouraj** [comment]
May be other alternative way?

**Comment by drk1wi** [comment]
what do you exactly want to achieve? passing client IP to the target server should be possible, but what's the benefit from that?

**Comment by antouraj** [comment]
The goal is to detect traffic for fake! 
If we use clients ip, then we can setup correctly traffic analysers!
Fake traffic bots - is a big problem! 
Modlishka can help to avoid it!

**Comment by patrick4real83** [comment]
Please who can guide me how to set up Modlishka or evilginx2

**Comment by ArunDinfinity** [comment]
> Please who can guide me how to set up Modlishka or evilginx2

if you can pay me well i can setup evilginx for you

**Comment by patrick4real83** [comment]
Yes. I will pay you. Let talk. Send me your email.

**Comment by ArunDinfinity** [comment]
it's a fake email 
Due to security reasons but u can still contact with me
pastryelite2@gmail.com

**Comment by drk1wi** [comment]
There's a WIKI with information how to set up the tool. This isn't a trade forum.

**Comment by JDarzan** [comment]
Please reopen this issue, i need send real ip in connection!
