### ISSUE TITLE
Proxying on localhost

### ISSUE THREAD

**Issue by jelledesnelle** [drk1wi/Modlishka#70]
![6c598054-5bb0-4ab6-bc0d-4553471c283c](https://user-images.githubusercontent.com/47040887/52535706-066ebe80-2d52-11e9-93c5-09bc23a3b791.jpeg)

Everything works fine. But if i type the link in my browser it wont open the Google.com link.
Any solution? Have i forgot something?

**Comment by LazyLinks** [comment]
Hi JelledeSnelle,

Add my discord: LazyLinks101 #4581.  So we can talk

Greets,

LazyLinks

**Comment by LazyLinks** [comment]
@jelledesnelle u can add my discord: LazyLinks101 #4581

**Comment by Ayushraj1** [comment]
Yes use loopback.modlishka.io:80 
Which operating system you are using, windows?

**Comment by Ayushraj1** [comment]
My discord-.   ayush#0651
