### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by w00dpacker** [drk1wi/Modlishka#72]
I have TLS handshake error in my log
http: TLS handshake error from xxx.xxx.x.xx:21312: remote error : tls unknown certificate authority

**Comment by drk1wi** [comment]
can you provide more information about the backend server. what type of tls certificate it's using?

**Comment by w00dpacker** [comment]
I'm using wildcard certificate .

**Comment by johnnash999** [comment]
same issue for me too :)

i'm using Lets Encrypt wildcard SSL

**Comment by w00dpacker** [comment]
@johnnash999 I buy wildcard certificate not Lets Encrypt

**Comment by An0nshy** [comment]
Hi drk1wi,

thx for share your'e nice prog. :) 
I have the TLS Handshake error, and on the Website i only get a whitescreen with a "?" in the mid to see. 

Errorcode : Listening on: [127.0.0.1:443] 
Proxying [loopback.modlishka.io:443] via --> [https://microsoftonline.com] 
2019/02/20 06:06:13 http: TLS handshake error from 127.0.0.1:47856: tls: first record does not look like a TLS handshake.

Do you have any ideas? 
The Certificate ist already loaded in the browser and i am running Linux Kali.

**Comment by thecityofhereafter** [comment]
Be sure to follow the wiki TO THE LETTER. use acme.sh to generate your certificates, and make sure you use CA.cer in the certpool field and not yourdomain.csr (dont use the certificate signing request in certpool) these were amateur mistakes I made that the wiki doesn't cover. Don't use the SSL commands and autocert like the wiki says, I couldn't get that to work anyway... and there are still issues with large nested subdomains, so avoid them if you can.

**Comment by tehseensagar** [comment]
@anonuser78 kindly share your config , so we may help you in better way.

if you are using default settings then  page suppose to be access via `
loopback.modlishka.io`  . if you want to setup a domain name then make sure you have generated correct certificates for it. kindly check my thread it will help you.

Regards
Scorpoin

**Comment by drk1wi** [comment]
Hi, Does this affect the traffic in any way? I have seen these errors in the past but I was always able to support the website anyway.

**Comment by drk1wi** [comment]
fixed in v.1.1

**Comment by kom82** [comment]
Hi @drk1wi 
I'm still havning this issue.
The error message is: http: TLS handshake error from 127.0.0.1:57270: remote error: tls: bad certificate

I'm using a wildcard certificate, signed by a Public CA.

thanks
