### ISSUE TITLE
Phishing domain not work!

### ISSUE THREAD

**Issue by tungto2006** [drk1wi/Modlishka#75]
Thank you for your great tool!

+) I have domain "hanwool.tk" and setup dns on CloudFlare like this with SSL :

![cloudflare](https://user-images.githubusercontent.com/47519035/52695474-378ffe80-2f9f-11e9-84ac-4b7c85919627.PNG)

+) And point to my IPv4 Public of VPS running Modlishka
+) This is my JSON config:
![json](https://user-images.githubusercontent.com/47519035/52695053-124ec080-2f9e-11e9-8023-42c1008c98a0.PNG)

but when I run "./dist/proxy -config myconfig " then access to hanwook.tk, it's not responding. Just Error .
![errro](https://user-images.githubusercontent.com/47519035/52695321-c81a0f00-2f9e-11e9-91bd-1711ba0ef968.PNG)

Can you help meee >< ???

**Comment by johnnash999** [comment]
similar, completed setup. 

but getting "Unable to connect" / "Connection Refused" in browser

**Comment by 0x00xx** [comment]
I've got a similar problem, where the tool does not resolve any subdomains. Any help on that one?

**Comment by kennyyy53** [comment]
> Thank you for your great tool!
> 
> +) I have domain "hanwool.tk" and setup dns on CloudFlare like this with SSL :
> 
> ![cloudflare](https://user-images.githubusercontent.com/47519035/52695474-378ffe80-2f9f-11e9-84ac-4b7c85919627.PNG)
> 
> +) And point to my IPv4 Public of VPS running Modlishka
> +) This is my JSON config:
> ![json](https://user-images.githubusercontent.com/47519035/52695053-124ec080-2f9e-11e9-8023-42c1008c98a0.PNG)
> 
> but when I run "./dist/proxy -config myconfig " then access to hanwook.tk, it's not responding. Just Error .
> ![errro](https://user-images.githubusercontent.com/47519035/52695321-c81a0f00-2f9e-11e9-91bd-1711ba0ef968.PNG)
> 
> Can you help meee >< ???

how did you do also to resolve your problem ?
