### ISSUE TITLE
Connection Refused in browser

### ISSUE THREAD

**Issue by johnnash999** [drk1wi/Modlishka#76]
Setup done. did everything as mentioned  in Wiki :) 

when i do run wget in server   "wget 127.0.0.1:443" .  i'm geting google page as response.    [so its working fine]

but website, i'm unable to open in browser... getting "Unable to connect" / "Connection Refused"

<img width="1129" alt="screenshot 2019-02-14 at 12 20 14 am" src="https://user-images.githubusercontent.com/27825133/52735854-7e591500-2fee-11e9-8356-17cd75865ad2.png">

**Comment by johnnash999** [comment]
Fixed after changing  listeningaddress to 0.0.0.0 in config file

**Comment by Ayushraj1** [comment]
Message me on discord ayush#7766
