### ISSUE TITLE
Discord Group Modlishks

### ISSUE THREAD

**Issue by Ayushraj1** [drk1wi/Modlishka#77]
Guys, join.
A discord server devoted to modlishka.
I've made a fantastic modlushka server on discord .
Join and discuss the issue and add more members 
https://discord.gg/BgVnEXS

**Comment by drk1wi** [comment]
This is unrelated to any issue, bug.

**Comment by johnnash999** [comment]
+ don't trust this guy.

he is just a ripper. not here to help anyone.

<img width="340" alt="screenshot 2019-02-14 at 3 30 25 pm" src="https://user-images.githubusercontent.com/27825133/52779139-97ed7180-306d-11e9-80c7-19e253e8ab65.png">
<img width="551" alt="screenshot 2019-02-14 at 3 29 06 pm" src="https://user-images.githubusercontent.com/27825133/52779140-98860800-306d-11e9-86e1-fc6a2053c463.png">
