### ISSUE TITLE
SSL Error: NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by tungto2006** [drk1wi/Modlishka#79]
+) I get SSL Certificate by using CertBot of LetEncrypt . But when access phishing domain, it return **NET::ERR_CERT_AUTHORITY_INVALID.**

+) Scanning on SSLLab . The issue is "Incomplete chain
![ssllab](https://user-images.githubusercontent.com/47519035/52873615-058ac200-3182-11e9-97e9-52804d9fb656.PNG)
" 

What should I do??

**Comment by johnnash999** [comment]
Same Issue. looking for solution. nothing found yet.

i'm too using letsencrypt ssl.

**Comment by vishnudath** [comment]
@tungto2006 

you need to add SSL Keys in json-config file.  [in base64 formate] :)

**Comment by tungto2006** [comment]
@vishnudath 
i added cert and key into autocert plugin and run ./dist/proxy -config myconfig .
so now i have to remove SSL in autocert plugin and add them in json file?

**Comment by tungto2006** [comment]
but i have new issues. Access phishing domain is successfully, but when i access some function, Modlishka warning like: 
**tls: no cipher suite supported by both client and server**
