### ISSUE TITLE
Combine Modlishka + DNS Spoof ?

### ISSUE THREAD

**Issue by tungto2006** [drk1wi/Modlishka#80]
I have setup successfully. But i want to ask:

+) My phishing domain point to my VPS running modlihka of course.So i want to test dns spoofing on my lan network, the dns spoofing require IP of domain.

+)  But when i access phishing domain by IP ( VPS IP) , instead of returning my phishing domain, it return my target website?

What should I do? Can combine modlishka with dns spoofing?

**Comment by Ayushraj1** [comment]
Message me on discord ayush#7766
