### ISSUE TITLE
Proxy / Socks support . [Feature Request] [Suggestion]

### ISSUE THREAD

**Issue by johnnash999** [drk1wi/Modlishka#81]
i can't really use this as a Phishing service, gmail will block my server IP ;) 

is there anyway, i can keep few proxies, and Modlishka uses those proxies to communicate with google / target website.  ;) :) :)

**Comment by johnnash999** [comment]
i'm ready to pay for this improvement :) if anyone can do.

**Comment by fipso** [comment]
I am currently doing this @johnnash999

**Comment by Ayushraj1** [comment]
I  can help you.
Message me on discor- #0651

**Comment by drk1wi** [comment]
this isn't a feature marketplace if you want to contribute to the project create PR.

**Comment by Ayushraj1** [comment]
Can you solve my issue, of Modlishka on windows

**Comment by johnnash999** [comment]
@fipso  anyway, we can get in touch wiht you ? ;) discord / skype ? :)
