### ISSUE TITLE
 WAR   DecodeSubdomain: domain [gse,.  wain an terengw] contains invalid characters

### ISSUE THREAD

**Issue by johnnash999** [drk1wi/Modlishka#84]
i'm using default config file,
- changed  localhost Address
- changed added SSL details
- changed Phishing Domain

<img width="1317" alt="screenshot 2019-02-18 at 7 37 35 pm" src="https://user-images.githubusercontent.com/27825133/52956292-d6a86200-33b4-11e9-9b07-a4002acda365.png">
<img width="1288" alt="screenshot 2019-02-18 at 7 37 29 pm" src="https://user-images.githubusercontent.com/27825133/52956309-df993380-33b4-11e9-8d43-9c3d0f4caf41.png">
<img width="1668" alt="screenshot 2019-02-18 at 7 39 50 pm" src="https://user-images.githubusercontent.com/27825133/52956391-140cef80-33b5-11e9-84c2-77c6d0c5a06e.png">

**Comment by drk1wi** [comment]
Hi, what do you mean by "
* changed added SSL details ? The CA cert should be trusted in the browser and you shouldn't get any SSL related errors.

**Comment by drk1wi** [comment]
The FDQN you are pointing to is actually why the tool works :-).  closing as resolved, due to lack of response.
