### ISSUE TITLE
Can't load the webpage, help!

### ISSUE THREAD

**Issue by anonuser78** [drk1wi/Modlishka#87]
The webpage doesn't load ... What can be an issue? I have tried everything. From changing the listening address to embedding the certificates and CNAME.

![modlishka issue](https://user-images.githubusercontent.com/47336246/53364103-0fdc5700-390c-11e9-95e7-9901c719f74e.PNG)
![unable](https://user-images.githubusercontent.com/47336246/53364231-5cc02d80-390c-11e9-95ff-3746a41f3415.PNG)

**Comment by jelledesnelle** [comment]
Use https://..loopback and use 443 for localhost

**Comment by anonuser78** [comment]
> Use https://..loopback and use 443 for localhost

It still doesn't work :(

**Comment by Ayushraj1** [comment]
Message me on discord ayush#7766

**Comment by drk1wi** [comment]
The URL for you config is: http://loopback.modlishka.io/ . Try to access it through a private mode.

**Comment by drk1wi** [comment]
closing as resolved, due to lack of response.
