### ISSUE TITLE
page does not load properly[Solved]

### ISSUE THREAD

**Issue by tehseensagar** [drk1wi/Modlishka#89]
Greetings,

I've created a test template for facebook

>
{
  "phishingDomain": "my-domain",
  "listeningPort": "443",
  "listeningAddress": "0.0.0.0",
  "target": "https://www.facebook.com",
  "targetResources": "",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "ident",
  "trackingParam": "ident",
  "useTls": true,
  "jsRules":"",
  "debug": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "facebook.log",
  "plugins": "all",
  "credParams": "dHJ1ZVxdLCIoW15cV10rKSJd,XGJudWxsLFxbIihbYS16QS1aMC05IiEiIyQlJicoKSorLC0uLzo7PD0+P0BeX2B7fH1+XSspIixudWxsXGI=",
  "cert": "add-cert-generated-from-letsencrypt",
  "certKey": "add-key-generated-from-letsencrypt",
  "certPool": "<add-chain-full>"
}
>

when I browse https://my-domain it does not load page properly , no images layout alignment is out. like evey thing is break and no css load. 

One more thing do I need to configure first apache or nignx to make this work if I do Im afraid i wont be able to use port 443 then. Looking forward to your kind response.

Regards
====================== Solved =========================

What I did is install certbot and followed the follwoing url to generated wildcard 

`https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7`

Make sure you add proper txt record into dns of your domain in DNS server.

then after cert is done using awk to get ehn I.E

`awk '{printf "%s\\n", $0}' <cert-file>`

also paste those cert and private-key into following file

` plugin/autocert.go`
`const CA_CERT =<ur-certicate>`
`const CA_CERT_KEY =<you-cert-key>`

every thing is done now your page will load properly without any issue .

**Comment by drk1wi** [comment]
# # @
