### ISSUE TITLE
Add subdomains

### ISSUE THREAD

**Issue by jelledesnelle** [drk1wi/Modlishka#92]
Hello, i added in config file at target resources my specify subdomains, i used pen test tools to search them. But modlishka does not respone to them? 

Something else need to change to get subdomains working?

**Comment by tehseensagar** [comment]
kindly share little more details so we may help you.

Regards

**Comment by jelledesnelle** [comment]
Modlishka does not supports every site automaticly, for my page login wont work. So i searched the login  subdomain with pen test tools.com

I wrote the subdomain in config file at target resources. I tested again. Still login page wont open.

**Comment by drk1wi** [comment]
please read the wiki, you are using the wrong parameter . target resources isn't meant for that.

**Comment by jelledesnelle** [comment]
Where do i need to fill in the extra subdomains. I read it many times before i asked here.

**Comment by drk1wi** [comment]
nowhere. they will be mapped automatically. point to the target parameter to the root domain.

**Comment by jelledesnelle** [comment]
Okay. But login page wont load propely. Thats why i add extra subdomains for the login page. You have a solution ?

**Comment by drk1wi** [comment]
please paste in you config file. I will check this out.

**Comment by jelledesnelle** [comment]
"phishingDomain": "loopback.modlishka.io",
  "listeningPort": "443",
  "listeningAddress": "127.0.0.1",
  "target": "https://www.ing.nl",
  "targetResources": "m.ing.nl",
  "targetRules": "",
  "terminateTriggers": "",
  "terminateRedirectUrl": "",
  "trackingCookie": "id",
  "trackingParam": "id",
  "useTls": true,
  "jsRules":"",
  "debug": false,
  "logPostOnly": false,
  "disableSecurity": false,
  "log": "ms.log",
  "plugins": "all",
  "cert": "",
  "certKey": "",
  "certPool": ""

m.ing.nl is the login subdomain. i added because login wont load properly. Its just a normal config nothing major changed yet.

**Comment by drk1wi** [comment]
please send me an approval for a pentest from ing for the tests contact@modlishka.io and I will try to help you.
