### ISSUE TITLE
Using the tool not only on the local computer

### ISSUE THREAD

**Issue by k0stQs** [drk1wi/Modlishka#93]
Hello,

Ηow can I use the tool by sending the phishing url (loopback.modlishka.io) to a target pc?
Βecause so far I have seen that it only works on the local pc.
For example if the attacker has ip: 192.168.1.10 and we send the phishing url: "192.168.1.10.modlishka.io" to the victim, this is doesn't work.

Can you please help me?

Thanks in advance!

**Comment by jelledesnelle** [comment]
The registered domain should point to the IP of the host where Modlishka is currently running.

Add 'A' record with the right IP address and a wildcard 'CNAME' '*' record.

**Comment by chefcarter** [comment]
please i need someone to help me set this up

**Comment by drk1wi** [comment]
Hi, everything is described on : https://github.com/drk1wi/Modlishka/wiki/How-to-use. If something is missing, please let me know.
