### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ewhitman1** [drk1wi/Modlishka#95]
Hi,
@drk1wi is it possible to use socks or https proxy with modlishka?

**Comment by drk1wi** [comment]
Hi,

Do you mean from the client side or for modlishka to use a proxy?

**Comment by ewhitman1** [comment]
Hi, 
@drk1wi I meant for modlishka.

**Comment by drk1wi** [comment]
resolved in dca3251b0aa2b1caab4eee3e7afe10dfbd879c92
