### ISSUE TITLE
Tls failed to see PEM

### ISSUE THREAD

**Issue by filebe777** [drk1wi/Modlishka#96]
root@kali:~/go/src/github.com/drk1wi/Modlishka# ./dist/proxy -config templates/google.com_gsuite.json
[Tue Mar 12 15:05:28 2019]  INF  Enabling plugin: autocert v0.1
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/drk1wi/Modlishka/plugin.init.0.func1()
	/root/go/src/github.com/drk1wi/Modlishka/plugin/autocert.go:105 +0xc0a
github.com/drk1wi/Modlishka/plugin.(*Property).Enable(0xc000070300)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:71 +0xef
github.com/drk1wi/Modlishka/plugin.Enable(0xc000032c60, 0xc000032c70, 0xc000032c80, 0xc000032c90, 0xc000032ca0, 0xc000032cd0, 0xc000032ce0, 0xc000032cb0, 0xc000032cc0, 0xc000032cf0, ...)
	/root/go/src/github.com/drk1wi/Modlishka/plugin/core_plugin.go:105 +0x11a
main.main()
	/root/go/src/github.com/drk1wi/Modlishka/main.go:65 +0x18f

**Comment by kennyyy53** [comment]
I have the same problem. Is someone knowing how to resolve this?

**Comment by kennyyy53** [comment]
I resolved this you just have to put the CA.key and pem in your .json file the predefined emplacement

**Comment by drk1wi** [comment]
closing as resolved.
