### ISSUE TITLE
Issue blocking page

### ISSUE THREAD

**Issue by jelledesnelle** [drk1wi/Modlishka#97]
Hello Piotr,

Modlishka works fine, but if i open a particular site page, it wont open.
I opened Inspect Element and next i clicked on console. I get the following message: **An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing** 

Wich file do i need to adjust in plugin folder to help solve this issue.
Some people say i need to adjust the ID to this: document.getElementById('someID').innerHTML = '<div>stuff</div>';  but i dont know where to change in Modlishka.

**Comment by drk1wi** [comment]
Please check the wiki. There's a parameter called 'targetRules' to replace content in the page.
